"""Catalogue massif d'alias sites — batch 3."""
from __future__ import annotations


def get_batch3() -> dict[str, str]:
    d: dict[str, str] = {}

    def add(alias: str, domain: str) -> None:
        d[alias.strip().lower()] = domain

    def adds(items: dict[str, str]) -> None:
        for k, v in items.items():
            add(k, v)

    # ── Stack Exchange & Q&A ──
    stacks = {
        "serverfault": "serverfault.com",
        "superuser": "superuser.com",
        "askubuntu": "askubuntu.com",
        "unix stackexchange": "unix.stackexchange.com",
        "unix se": "unix.stackexchange.com",
        "dba stackexchange": "dba.stackexchange.com",
        "softwareengineering se": "softwareengineering.stackexchange.com",
        "codereview se": "codereview.stackexchange.com",
        "security se": "security.stackexchange.com",
        "crypto se": "crypto.stackexchange.com",
        "math se": "math.stackexchange.com",
        "stats se": "stats.stackexchange.com",
        "datascience se": "datascience.stackexchange.com",
        "ai se": "ai.stackexchange.com",
        "physics se": "physics.stackexchange.com",
        "chemistry se": "chemistry.stackexchange.com",
        "biology se": "biology.stackexchange.com",
        "electronics se": "electronics.stackexchange.com",
        "arduino se": "arduino.stackexchange.com",
        "raspberrypi se": "raspberrypi.stackexchange.com",
        "gaming se": "gaming.stackexchange.com",
        "rpg se": "rpg.stackexchange.com",
        "boardgames se": "boardgames.stackexchange.com",
        "aviation se": "aviation.stackexchange.com",
        "travel se": "travel.stackexchange.com",
        "french se": "french.stackexchange.com",
        "linguistics se": "linguistics.stackexchange.com",
        "worldbuilding se": "worldbuilding.stackexchange.com",
        "writing se": "writing.stackexchange.com",
        "graphicdesign se": "graphicdesign.stackexchange.com",
        "photo se": "photo.stackexchange.com",
        "video se": "video.stackexchange.com",
        "music se": "music.stackexchange.com",
        "sound se": "sound.stackexchange.com",
        "blender se": "blender.stackexchange.com",
        "gamedev se": "gamedev.stackexchange.com",
        "unity se": "unity.stackexchange.com",
        "unreal se": "unrealengine.com",
        "webapps se": "webapps.stackexchange.com",
        "webmasters se": "webmasters.stackexchange.com",
        "wordpress se": "wordpress.stackexchange.com",
        "magento se": "magento.stackexchange.com",
        "shopify se": "shopify.stackexchange.com",
        "salesforce se": "salesforce.stackexchange.com",
        "law se": "law.stackexchange.com",
        "workplace se": "workplace.stackexchange.com",
        "pm se": "pm.stackexchange.com",
        "ux se": "ux.stackexchange.com",
        "parenting se": "parenting.stackexchange.com",
        "money se": "money.stackexchange.com",
        "personal finance se": "money.stackexchange.com",
        "expats se": "expats.stackexchange.com",
        "quora": "quora.com",
        "answers": "answers.com",
        "stackexchange": "stackexchange.com",
        "stack exchange": "stackexchange.com",
    }
    adds(stacks)

    # ── Wikimedia & encyclopédies ──
    wikis = {
        "wikimedia": "wikimedia.org",
        "wikidata": "wikidata.org",
        "wiktionary": "fr.wiktionary.org",
        "wiktionary fr": "fr.wiktionary.org",
        "wiktionary en": "en.wiktionary.org",
        "wikiquote": "fr.wikiquote.org",
        "wikibooks": "fr.wikibooks.org",
        "wikisource": "fr.wikisource.org",
        "wikinews": "fr.wikinews.org",
        "wikivoyage": "fr.wikivoyage.org",
        "commons": "commons.wikimedia.org",
        "wikimedia commons": "commons.wikimedia.org",
        "wikipedia en": "en.wikipedia.org",
        "wikipedia de": "de.wikipedia.org",
        "wikipedia es": "es.wikipedia.org",
        "wikipedia it": "it.wikipedia.org",
        "wikipedia pt": "pt.wikipedia.org",
        "wikipedia ja": "ja.wikipedia.org",
        "wikipedia zh": "zh.wikipedia.org",
        "wikipedia ru": "ru.wikipedia.org",
        "wikipedia ar": "ar.wikipedia.org",
        "britannica": "britannica.com",
        "larousse en ligne": "larousse.fr",
        "universalis": "universalis.fr",
        "encyclopedia": "britannica.com",
        "archive org": "archive.org",
        "internet archive": "archive.org",
        "wayback machine": "web.archive.org",
        "wayback": "web.archive.org",
        "gutenberg": "gutenberg.org",
        "project gutenberg": "gutenberg.org",
        "gallica": "gallica.bnf.fr",
        "bnf": "bnf.fr",
        "persee": "persee.fr",
        "cairn": "cairn.info",
        "jstor fr": "jstor.org",
        "hal": "hal.science",
        "hal science": "hal.science",
        "theses fr": "theses.fr",
        "openedition": "openedition.org",
        "hypotheses": "hypotheses.org",
        "doaj": "doaj.org",
        "plos one": "journals.plos.org/plosone",
        "biorxiv": "biorxiv.org",
        "medrxiv": "medrxiv.org",
        "ssrn": "ssrn.com",
        "zenodo": "zenodo.org",
        "figshare": "figshare.com",
        "osf": "osf.io",
        "open science framework": "osf.io",
    }
    adds(wikis)

    # ── Jeux de plateau en ligne ──
    board = {
        "board game arena": "boardgamearena.com",
        "bga": "boardgamearena.com",
        "yucata": "yucata.de",
        "boiteajeux": "boiteajeux.net",
        "tabletopia": "tabletopia.com",
        "tabletop simulator": "tabletopsimulator.com",
        "tts": "tabletopsimulator.com",
        "vassal": "vassalengine.org",
        "cyberboard": "cyberboard.net",
        "boardgamegeek": "boardgamegeek.com",
        "bgg": "boardgamegeek.com",
        "ludopedia": "ludopedia.com.br",
        "trictrac": "trictrac.net",
        "philibert": "philibertnet.com",
        "philibert": "philibertnet.com",
        "espritjeu": "espritjeu.com",
        "ludum": "ludum.fr",
        "ludum fr": "ludum.fr",
        "millenium store": "millenium.org",
        "asmodee": "asmodee.com",
        "asmodee store": "asmodee.com",
        "iello": "iellogames.com",
        "days of wonder": "daysofwonder.com",
        "daysofwonder": "daysofwonder.com",
        "fantasy flight": "fantasyflightgames.com",
        "ffg": "fantasyflightgames.com",
        "repos production": "repos-production.com",
        "stella montis": "stella-montis.com",
        "stella-montis": "stella-montis.com",
        "stella montis games": "stella-montis.com",
        "stella-montis games": "stella-montis.com",
        "stella montis impero": "impero-game.fr",
        "impero site": "impero-game.fr",
        "impero plateau": "impero-game.fr",
        "impero jeu": "impero-game.fr",
        "matagot": "matagot.com",
        "libellud": "libellud.com",
        "space cowboys": "spacecowboys.fr",
        "spacecowboys": "spacecowboys.fr",
        "gigamic": "gigamic.com",
        "hurrican": "hurrican.fr",
        "rebel": "rebel.pl",
        "czech games": "czechgames.com",
        "cge": "czechgames.com",
        "lookout games": "lookout-games.com",
        "lookout": "lookout-games.com",
        "eggertspiele": "eggertspiele.de",
        "kosmos": "kosmos.de",
        "ravensburger": "ravensburger.com",
        "hasbro": "hasbro.com",
        "wizards of the coast": "wizards.com",
        "wizards": "wizards.com",
        "wotc": "wizards.com",
        "magic the gathering": "magic.wizards.com",
        "mtg": "magic.wizards.com",
        "magic arena": "magic.wizards.com/en/mtgarena",
        "mtga": "magic.wizards.com/en/mtgarena",
        "dnd beyond": "dndbeyond.com",
        "d&d beyond": "dndbeyond.com",
        "roll20": "roll20.net",
        "foundry vtt": "foundryvtt.com",
        "foundryvtt": "foundryvtt.com",
        "foundry": "foundryvtt.com",
        "fantasy grounds": "fantasygrounds.com",
        "owlbear rodeo": "owlbear.rodeo",
        "owlbear": "owlbear.rodeo",
        "demiplane": "demiplane.com",
        "pathbuilder": "pathbuilder2e.com",
        "dnd 5e tools": "dnd5e.tools",
        "5etools": "5etools.xyz",
        "aidedd": "aidedd.org",
        "donjon": "donjon.bin.sh",
        "kobold fight club": "koboldplus.club",
        "kfc dnd": "koboldplus.club",
    }
    adds(board)

    # ── Linux & open source ──
    linux = {
        "ubuntu": "ubuntu.com",
        "debian": "debian.org",
        "fedora": "fedora-project.org",
        "centos": "centos.org",
        "rocky linux": "rockylinux.org",
        "rockylinux": "rockylinux.org",
        "almalinux": "almalinux.org",
        "arch linux": "archlinux.org",
        "archlinux": "archlinux.org",
        "manjaro": "manjaro.org",
        "opensuse": "opensuse.org",
        "mint": "linuxmint.com",
        "linux mint": "linuxmint.com",
        "elementary os": "elementary.io",
        "elementary": "elementary.io",
        "pop os": "pop.system76.com",
        "popos": "pop.system76.com",
        "kali": "kali.org",
        "kali linux": "kali.org",
        "parrot os": "parrotsec.org",
        "parrot": "parrotsec.org",
        "tails": "tails.net",
        "alpine linux": "alpinelinux.org",
        "alpine": "alpinelinux.org",
        "nixos": "nixos.org",
        "gentoo": "gentoo.org",
        "slackware": "slackware.com",
        "freebsd": "freebsd.org",
        "openbsd": "openbsd.org",
        "netbsd": "netbsd.org",
        "kernel org": "kernel.org",
        "linux kernel": "kernel.org",
        "gnu": "gnu.org",
        "fsf": "fsf.org",
        "sourcehut": "sourcehut.org",
        "sr ht": "sourcehut.org",
        "savannah": "savannah.gnu.org",
        "launchpad": "launchpad.net",
        "apache projects": "projects.apache.org",
        "eclipse": "eclipse.org",
        "jetbrains": "jetbrains.com",
        "intellij": "jetbrains.com/idea",
        "pycharm": "jetbrains.com/pycharm",
        "webstorm": "jetbrains.com/webstorm",
        "phpstorm": "jetbrains.com/phpstorm",
        "rider": "jetbrains.com/rider",
        "clion": "jetbrains.com/clion",
        "goland": "jetbrains.com/go",
        "datagrip": "jetbrains.com/datagrip",
        "fleet": "jetbrains.com/fleet",
        "android studio": "developer.android.com/studio",
        "xcode": "developer.apple.com/xcode",
        "visual studio": "visualstudio.microsoft.com",
        "vs": "visualstudio.microsoft.com",
        "vscode marketplace": "marketplace.visualstudio.com",
        "vim": "vim.org",
        "neovim": "neovim.io",
        "emacs": "gnu.org/software/emacs",
        "helix": "helix-editor.com",
        "zed": "zed.dev",
        "lapce": "lapce.dev",
        "micro editor": "micro-editor.github.io",
        "nano": "nano-editor.org",
        "homebrew": "brew.sh",
        "brew": "brew.sh",
        "chocolatey": "chocolatey.org",
        "scoop": "scoop.sh",
        "winget": "learn.microsoft.com/windows/package-manager/winget",
        "apt": "wiki.debian.org/Apt",
        "pacman": "archlinux.org/pacman",
        "flatpak": "flatpak.org",
        "snapcraft": "snapcraft.io",
        "appimage": "appimage.org",
        "distrowatch": "distrowatch.com",
        "linuxquestions": "linuxquestions.org",
        "linuxfr": "linuxfr.org",
        "linux fr": "linuxfr.org",
        "presse citron linux": "presse-citron.net",
        "9to5linux": "9to5linux.com",
        "omg ubuntu": "omgubuntu.co.uk",
        "omgubuntu": "omgubuntu.co.uk",
        "itsfoss": "itsfoss.com",
        "phoronix": "phoronix.com",
        "lwn": "lwn.net",
        "lwn net": "lwn.net",
    }
    adds(linux)

    # ── Cybersécurité & réseau ──
    security = {
        "cve": "cve.mitre.org",
        "nvd": "nvd.nist.gov",
        "cwe": "cwe.mitre.org",
        "owasp": "owasp.org",
        "have i been pwned": "haveibeenpwned.com",
        "hibp": "haveibeenpwned.com",
        "virustotal": "virustotal.com",
        "urlscan": "urlscan.io",
        "shodan": "shodan.io",
        "censys": "censys.io",
        "crt.sh": "crt.sh",
        "ssl labs": "ssllabs.com",
        "ssllabs": "ssllabs.com",
        "dnsdumpster": "dnsdumpster.com",
        "mxtoolbox": "mxtoolbox.com",
        "dnschecker": "dnschecker.org",
        "whois": "whois.com",
        "icann lookup": "lookup.icann.org",
        "bgp he": "bgp.he.net",
        "bgp tools": "bgp.tools",
        "ipinfo": "ipinfo.io",
        "whatismyip": "whatismyipaddress.com",
        "ipleak": "ipleak.net",
        "dns leak test": "dnsleaktest.com",
        "browserleaks": "browserleaks.com",
        "exploit db": "exploit-db.com",
        "exploitdb": "exploit-db.com",
        "packet storm": "packetstormsecurity.com",
        "mitre attack": "attack.mitre.org",
        "mitre att&ck": "attack.mitre.org",
        "att&ck": "attack.mitre.org",
        "hackthebox": "hackthebox.com",
        "htb": "hackthebox.com",
        "tryhackme": "tryhackme.com",
        "thm": "tryhackme.com",
        "root me": "root-me.org",
        "rootme": "root-me.org",
        "overthewire": "overthewire.org",
        "picoctf": "picoctf.org",
        "cyberdefenders": "cyberdefenders.org",
        "malwarebytes": "malwarebytes.com",
        "kaspersky": "kaspersky.fr",
        "bitdefender": "bitdefender.fr",
        "eset": "eset.com",
        "avast": "avast.com",
        "avg": "avg.com",
        "norton": "norton.com",
        "mcafee": "mcafee.com",
        "crowdstrike": "crowdstrike.com",
        "palo alto": "paloaltonetworks.com",
        "fortinet": "fortinet.com",
        "cloudflare zero trust": "one.dash.cloudflare.com",
        "lets encrypt": "letsencrypt.org",
        "letsencrypt": "letsencrypt.org",
        "certbot": "certbot.eff.org",
        "acme": "letsencrypt.org",
    }
    adds(security)

    # ── Cloud & infra (complément) ──
    cloud = {
        "ibm cloud": "cloud.ibm.com",
        "oracle cloud": "cloud.oracle.com",
        "oci": "cloud.oracle.com",
        "alibaba cloud": "alibabacloud.com",
        "tencent cloud": "cloud.tencent.com",
        "huawei cloud": "huaweicloud.com",
        "hetzner": "hetzner.com",
        "contabo": "contabo.com",
        "ionos": "ionos.fr",
        "1and1": "ionos.fr",
        "hostinger": "hostinger.fr",
        "ovhcloud": "ovhcloud.com",
        "online net": "online.net",
        "gandi": "gandi.net",
        "namecheap": "namecheap.com",
        "godaddy": "godaddy.com",
        "porkbun": "porkbun.com",
        "dynadot": "dynadot.com",
        "cloudflare dns": "dash.cloudflare.com",
        "cloudflare pages": "pages.cloudflare.com",
        "cloudflare workers": "workers.cloudflare.com",
        "cloudflare r2": "dash.cloudflare.com",
        "vercel templates": "vercel.com/templates",
        "netlify templates": "netlify.com",
        "fly io": "fly.io",
        "flyio": "fly.io",
        "deno deploy": "deno.com/deploy",
        "deno": "deno.com",
        "bun": "bun.sh",
        "cloudflare tunnel": "developers.cloudflare.com/cloudflare-one",
        "tailscale funnel": "tailscale.com",
        "nomad": "developer.hashicorp.com/nomad",
        "consul": "developer.hashicorp.com/consul",
        "vault": "developer.hashicorp.com/vault",
        "packer": "developer.hashicorp.com/packer",
        "vagrant": "developer.hashicorp.com/vagrant",
        "pulumi": "pulumi.com",
        "crossplane": "crossplane.io",
        "argocd": "argo-cd.readthedocs.io",
        "argo cd": "argo-cd.readthedocs.io",
        "fluxcd": "fluxcd.io",
        "flux": "fluxcd.io",
        "istio": "istio.io",
        "linkerd": "linkerd.io",
        "envoy": "envoyproxy.io",
        "traefik": "traefik.io",
        "caddy": "caddyserver.com",
        "haproxy": "haproxy.org",
        "minio": "min.io",
        "ceph": "ceph.io",
        "longhorn": "longhorn.io",
        "rook": "rook.io",
        "harbor": "goharbor.io",
        "nexus": "sonatype.com/products/sonatype-nexus-repository",
        "artifactory": "jfrog.com/artifactory",
        "jfrog": "jfrog.com",
    }
    adds(cloud)

    # ── Langages & docs (complément massif) ──
    langs = {
        "typescript docs": "typescriptlang.org/docs",
        "typescript": "typescriptlang.org",
        "javascript docs": "developer.mozilla.org/en-US/docs/Web/JavaScript",
        "nodejs docs": "nodejs.org/docs",
        "node docs": "nodejs.org/docs",
        "deno docs": "docs.deno.com",
        "bun docs": "bun.sh/docs",
        "php docs": "php.net/docs",
        "php": "php.net",
        "ruby docs": "ruby-doc.org",
        "ruby": "ruby-lang.org",
        "perl docs": "perldoc.perl.org",
        "perl": "perl.org",
        "lua docs": "lua.org/manual",
        "lua": "lua.org",
        "haskell docs": "haskell.org/documentation",
        "haskell": "haskell.org",
        "elixir docs": "hexdocs.pm/elixir",
        "elixir": "elixir-lang.org",
        "erlang docs": "erlang.org/doc",
        "erlang": "erlang.org",
        "clojure docs": "clojure.org",
        "clojure": "clojure.org",
        "scala docs": "docs.scala-lang.org",
        "scala": "scala-lang.org",
        "kotlin docs": "kotlinlang.org/docs",
        "kotlin": "kotlinlang.org",
        "swift docs": "swift.org/documentation",
        "swift": "swift.org",
        "objc docs": "developer.apple.com/documentation/objectivec",
        "objective c": "developer.apple.com/documentation/objectivec",
        "dart docs": "dart.dev",
        "dart": "dart.dev",
        "flutter docs": "docs.flutter.dev",
        "flutter": "flutter.dev",
        "react native docs": "reactnative.dev",
        "react native": "reactnative.dev",
        "expo docs": "docs.expo.dev",
        "expo": "expo.dev",
        "capacitor": "capacitorjs.com",
        "ionic": "ionicframework.com",
        "electron docs": "electronjs.org/docs",
        "electron": "electronjs.org",
        "tauri": "tauri.app",
        "wails": "wails.io",
        "zig docs": "ziglang.org/documentation",
        "zig": "ziglang.org",
        "nim docs": "nim-lang.org/docs",
        "nim": "nim-lang.org",
        "crystal docs": "crystal-lang.org/reference",
        "crystal": "crystal-lang.org",
        "v lang": "vlang.io",
        "vlang": "vlang.io",
        "ocaml docs": "ocaml.org/docs",
        "ocaml": "ocaml.org",
        "fsharp docs": "learn.microsoft.com/dotnet/fsharp",
        "f#": "learn.microsoft.com/dotnet/fsharp",
        "csharp docs": "learn.microsoft.com/dotnet/csharp",
        "c#": "learn.microsoft.com/dotnet/csharp",
        "dotnet docs": "learn.microsoft.com/dotnet",
        "dotnet": "dotnet.microsoft.com",
        "aspnet docs": "learn.microsoft.com/aspnet/core",
        "asp.net": "learn.microsoft.com/aspnet/core",
        "powershell docs": "learn.microsoft.com/powershell",
        "powershell": "learn.microsoft.com/powershell",
        "bash docs": "gnu.org/software/bash/manual",
        "bash": "gnu.org/software/bash/manual",
        "zsh docs": "zsh.sourceforge.io/Doc",
        "fish shell": "fishshell.com",
        "fish": "fishshell.com",
        "nushell": "nushell.sh",
        "nu shell": "nushell.sh",
        "assembly docs": "wiki.osdev.org",
        "riscv docs": "riscv.org/technical/specifications",
        "riscv": "riscv.org",
        "wasm docs": "webassembly.org",
        "webassembly": "webassembly.org",
        "wasm": "webassembly.org",
        "wasi": "wasi.dev",
        "llvm docs": "llvm.org/docs",
        "llvm": "llvm.org",
        "gcc docs": "gcc.gnu.org/onlinedocs",
        "gcc": "gcc.gnu.org",
        "clang docs": "clang.llvm.org/docs",
        "clang": "clang.llvm.org",
        "cmake docs": "cmake.org/documentation",
        "cmake": "cmake.org",
        "make docs": "gnu.org/software/make/manual",
        "ninja build": "ninja-build.org",
        "meson": "mesonbuild.com",
        "bazel docs": "bazel.build",
        "bazel": "bazel.build",
        "buck2": "buck2.build",
        "gradle docs": "docs.gradle.org",
        "gradle": "gradle.org",
        "maven docs": "maven.apache.org/guides",
        "maven": "maven.apache.org",
        "ant docs": "ant.apache.org/manual",
        "sbt docs": "scala-sbt.org",
        "cargo docs": "doc.rust-lang.org/cargo",
        "cargo": "doc.rust-lang.org/cargo",
        "pip docs": "pip.pypa.io/en/stable",
        "setuptools": "setuptools.pypa.io",
        "wheel": "wheel.readthedocs.io",
        "virtualenv": "virtualenv.pypa.io",
        "venv": "docs.python.org/3/library/venv.html",
        "tox": "tox.wiki",
        "nox": "nox.thea.codes",
        "invoke py": "docs.pyinvoke.org",
        "fabric py": "docs.fabfile.org",
        "click docs": "click.palletsprojects.com",
        "click": "click.palletsprojects.com",
        "typer docs": "typer.tiangolo.com",
        "typer": "typer.tiangolo.com",
        "rich docs": "rich.readthedocs.io",
        "rich": "rich.readthedocs.io",
        "textual docs": "textual.textualize.io",
        "textual": "textual.textualize.io",
        "streamlit docs": "docs.streamlit.io",
        "streamlit": "streamlit.io",
        "gradio docs": "gradio.app/docs",
        "gradio": "gradio.app",
        "panel docs": "panel.holoviz.org",
        "panel": "panel.holoviz.org",
        "dash plotly": "dash.plotly.com",
        "dash": "dash.plotly.com",
        "bokeh docs": "docs.bokeh.org",
        "bokeh": "bokeh.org",
        "altair docs": "altair-viz.github.io",
        "altair": "altair-viz.github.io",
        "seaborn docs": "seaborn.pydata.org",
        "seaborn": "seaborn.pydata.org",
        "polars docs": "docs.pola.rs",
        "polars": "pola.rs",
        "duckdb docs": "duckdb.org/docs",
        "duckdb": "duckdb.org",
        "apache spark docs": "spark.apache.org/docs",
        "spark": "spark.apache.org",
        "apache kafka docs": "kafka.apache.org/documentation",
        "kafka": "kafka.apache.org",
        "apache airflow docs": "airflow.apache.org/docs",
        "airflow": "airflow.apache.org",
        "dbt docs": "docs.getdbt.com",
        "dbt": "getdbt.com",
        "snowflake docs": "docs.snowflake.com",
        "snowflake": "snowflake.com",
        "databricks docs": "docs.databricks.com",
        "databricks": "databricks.com",
        "bigquery docs": "cloud.google.com/bigquery/docs",
        "bigquery": "cloud.google.com/bigquery",
        "redshift docs": "docs.aws.amazon.com/redshift",
        "redshift": "aws.amazon.com/redshift",
        "clickhouse docs": "clickhouse.com/docs",
        "clickhouse": "clickhouse.com",
        "timescaledb docs": "docs.timescale.com",
        "timescaledb": "timescale.com",
        "influxdb docs": "docs.influxdata.com",
        "influxdb": "influxdata.com",
        "questdb docs": "questdb.io/docs",
        "questdb": "questdb.io",
        "cassandra docs": "cassandra.apache.org/doc",
        "cassandra": "cassandra.apache.org",
        "dynamodb docs": "docs.aws.amazon.com/dynamodb",
        "dynamodb": "aws.amazon.com/dynamodb",
        "fauna docs": "docs.fauna.com",
        "fauna": "fauna.com",
        "couchdb docs": "docs.couchdb.org",
        "couchdb": "couchdb.apache.org",
        "realm docs": "mongodb.com/docs/realm",
        "realm": "mongodb.com/realm",
        "watermelon db": "watermelondb.dev",
        "sqlite docs": "sqlite.org/docs.html",
        "libsql docs": "docs.turso.tech/libsql",
        "libsql": "docs.turso.tech/libsql",
    }
    adds(langs)

    # ── IA / ML (complément) ──
    ai = {
        "xai grok": "x.ai",
        "grok": "x.ai",
        "x ai": "x.ai",
        "character ai": "character.ai",
        "characterai": "character.ai",
        "poe ai": "poe.com",
        "poe": "poe.com",
        "you com": "you.com",
        "you.com": "you.com",
        "phind": "phind.com",
        "kagi": "kagi.com",
        "andisearch": "andisearch.com",
        "andi search": "andisearch.com",
        "brave search": "search.brave.com",
        "brave search ai": "search.brave.com",
        "duckduckgo ai": "duckduckgo.com",
        "ddg": "duckduckgo.com",
        "duckduckgo": "duckduckgo.com",
        "ecosia": "ecosia.org",
        "qwant": "qwant.com",
        "startpage": "startpage.com",
        "searx": "searx.space",
        "whoogle": "github.com/benbusby/whoogle-search",
        "llama cpp": "github.com/ggerganov/llama.cpp",
        "llamacpp": "github.com/ggerganov/llama.cpp",
        "llamafile": "mozilla.ai/llamafile",
        "text generation webui": "github.com/oobabooga/text-generation-webui",
        "oobabooga": "github.com/oobabooga/text-generation-webui",
        "kobold ai": "koboldai.net",
        "koboldai": "koboldai.net",
        "oob": "github.com/oobabooga/text-generation-webui",
        "vllm docs": "docs.vllm.ai",
        "vllm": "docs.vllm.ai",
        "tensorrt llm": "developer.nvidia.com/tensorrt-llm",
        "llama index docs": "docs.llamaindex.ai",
        "langgraph docs": "langchain-ai.github.io/langgraph",
        "langgraph": "langchain-ai.github.io/langgraph",
        "langsmith": "smith.langchain.com",
        "weights and biases": "wandb.ai",
        "wandb": "wandb.ai",
        "mlflow docs": "mlflow.org/docs",
        "mlflow": "mlflow.org",
        "dvc docs": "dvc.org/doc",
        "dvc": "dvc.org",
        "clearml": "clear.ml",
        "neptune ai": "neptune.ai",
        "comet ml": "comet.com",
        "comet": "comet.com",
        "roboflow docs": "docs.roboflow.com",
        "roboflow": "roboflow.com",
        "labelbox": "labelbox.com",
        "label studio": "labelstud.io",
        "labelstudio": "labelstud.io",
        "cvat": "cvat.ai",
        "supervisely": "supervisely.com",
        "fiftyone docs": "docs.voxel51.com",
        "fiftyone": "voxel51.com",
        "opencv docs": "docs.opencv.org",
        "opencv": "opencv.org",
        "mediapipe docs": "developers.google.com/mediapipe",
        "mediapipe": "developers.google.com/mediapipe",
        "onnx docs": "onnx.ai",
        "onnx": "onnx.ai",
        "tensorrt docs": "developer.nvidia.com/tensorrt",
        "tensorrt": "developer.nvidia.com/tensorrt",
        "triton inference": "developer.nvidia.com/triton-inference-server",
        "triton server": "developer.nvidia.com/triton-inference-server",
        "nvidia ai": "developer.nvidia.com/ai",
        "cuda docs": "docs.nvidia.com/cuda",
        "cuda": "developer.nvidia.com/cuda-zone",
        "cudnn docs": "developer.nvidia.com/cudnn",
        "cudnn": "developer.nvidia.com/cudnn",
        "rocm docs": "rocm.docs.amd.com",
        "rocm": "rocm.docs.amd.com",
        "openvino docs": "docs.openvino.ai",
        "openvino": "docs.openvino.ai",
        "coreml docs": "developer.apple.com/documentation/coreml",
        "coreml": "developer.apple.com/documentation/coreml",
        "tflite docs": "tensorflow.org/lite",
        "tflite": "tensorflow.org/lite",
        "mlx docs": "ml-explore.github.io/mlx",
        "mlx": "ml-explore.github.io/mlx",
        "apple ml": "machinelearning.apple.com",
        "suno ai": "suno.com",
        "suno": "suno.com",
        "udio": "udio.com",
        "stable audio": "stableaudio.com",
        "stableaudio": "stableaudio.com",
        "udio ai": "udio.com",
        "heygen": "heygen.com",
        "synthesia": "synthesia.io",
        "d-id": "d-id.com",
        "did": "d-id.com",
        "runway gen3": "runwayml.com",
        "luma ai": "lumalabs.ai",
        "luma": "lumalabs.ai",
        "krea ai": "krea.ai",
        "krea": "krea.ai",
        "magnific ai": "magnific.ai",
        "magnific": "magnific.ai",
        "clipdrop": "clipdrop.co",
        "remove bg": "remove.bg",
        "removebg": "remove.bg",
        "cleanup pictures": "cleanup.pictures",
        "cleanup": "cleanup.pictures",
        "photoroom": "photoroom.com",
        "pixelcut": "pixelcut.ai",
        "recraft ai": "recraft.ai",
        "recraft": "recraft.ai",
        "vectorizer ai": "vectorizer.ai",
        "vectorizer": "vectorizer.ai",
        "svg trace": "svgtrace.com",
        "svgtrace": "svgtrace.com",
    }
    adds(ai)

    # ── Médias FR régionaux (massif) ──
    regional_press = {
        "la montagne": "lamontagne.fr",
        "lamontagne": "lamontagne.fr",
        "le populaire du centre": "lepopulaire.fr",
        "lepopulaire": "lepopulaire.fr",
        "le berry republicain": "leberry.fr",
        "leberry": "leberry.fr",
        "la nouvelle republique": "lanouvellerepublique.fr",
        "lanouvellerepublique": "lanouvellerepublique.fr",
        "nr": "lanouvellerepublique.fr",
        "le courrier de l ouest": "courrierdelouest.fr",
        "courrier de l ouest": "courrierdelouest.fr",
        "courrierdelouest": "courrierdelouest.fr",
        "le telegramme": "letelegramme.fr",
        "letelegramme": "letelegramme.fr",
        "telegramme": "letelegramme.fr",
        "ouest france rennes": "ouest-france.fr",
        "le journal de saone et loire": "lejsl.com",
        "lejsl": "lejsl.com",
        "le bien public": "bienpublic.com",
        "bienpublic": "bienpublic.com",
        "l est eclair": "estrepublicain.fr",
        "le republicain lorrain": "republicain-lorrain.fr",
        "republicain lorrain": "republicain-lorrain.fr",
        "rl": "republicain-lorrain.fr",
        "dna": "dna.fr",
        "dernieres nouvelles d alsace": "dna.fr",
        "l alsace": "lalsace.fr",
        "lalsace": "lalsace.fr",
        "le progres lyon": "leprogres.fr",
        "le phare dunkerquois": "pharedunord.fr",
        "pharedunord": "pharedunord.fr",
        "voix du nord": "lavoixdunord.fr",
        "lavoixdunord": "lavoixdunord.fr",
        "la voix du nord": "lavoixdunord.fr",
        "nordeclair": "nordeclair.fr",
        "nord eclair": "nordeclair.fr",
        "paris normandie rouen": "paris-normandie.fr",
        "actu fr": "actu.fr",
        "actu": "actu.fr",
        "france bleu": "francebleu.fr",
        "francebleu": "francebleu.fr",
        "ici": "francebleu.fr",
        "radio france ici": "francebleu.fr",
        "france 3 regions": "france.tv/france-3",
        "france 3 pays de la loire": "france.tv/france-3/pays-de-la-loire",
        "france 3 bretagne": "france.tv/france-3/bretagne",
        "france 3 normandie": "france.tv/france-3/normandie",
        "france 3 grand est": "france.tv/france-3/grand-est",
        "france 3 occitanie": "france.tv/france-3/occitanie",
        "france 3 nouvelle aquitaine": "france.tv/france-3/nouvelle-aquitaine",
        "france 3 hauts de france": "france.tv/france-3/hauts-de-france",
        "france 3 provence": "france.tv/france-3/provence-alpes",
        "france 3 corse": "france.tv/france-3/corse",
        "france 3 alpine": "france.tv/france-3/alpes",
        "france 3 centre": "france.tv/france-3/centre-val-de-loire",
        "france 3 bourgogne": "france.tv/france-3/bourgogne-franche-comte",
        "france 3 picardie": "france.tv/france-3/hauts-de-france",
        "france 3 limousin": "france.tv/france-3/nouvelle-aquitaine",
        "france 3 lorraine": "france.tv/france-3/grand-est",
        "france 3 champagne": "france.tv/france-3/grand-est",
        "france 3 aquitaine": "france.tv/france-3/nouvelle-aquitaine",
        "france 3 midi pyrenees": "france.tv/france-3/occitanie",
        "france 3 languedoc": "france.tv/france-3/occitanie",
        "france 3 cote d azur": "france.tv/france-3/provence-alpes",
        "france 3 rhone alpes": "france.tv/france-3/alpes",
        "france 3 poitou charentes": "france.tv/france-3/nouvelle-aquitaine",
        "france 3 basse normandie": "france.tv/france-3/normandie",
        "france 3 haute normandie": "france.tv/france-3/normandie",
        "france 3 nord pas de calais": "france.tv/france-3/hauts-de-france",
        "france 3 alsace": "france.tv/france-3/grand-est",
        "france 3 franche comte": "france.tv/france-3/bourgogne-franche-comte",
        "france 3 auvergne": "france.tv/france-3/alpes",
        "france 3 nord pas calais": "france.tv/france-3/hauts-de-france",
    }
    adds(regional_press)

    # ── Villes & communes FR (100+) ──
    cities = [
        "paris", "marseille", "lyon", "toulouse", "nice", "nantes", "montpellier",
        "strasbourg", "bordeaux", "lille", "rennes", "reims", "saint-etienne",
        "toulon", "le havre", "grenoble", "dijon", "angers", "nimes", "villeurbanne",
        "saint-denis", "le mans", "aix-en-provence", "clermont-ferrand", "brest",
        "tours", "amiens", "limoges", "annecy", "perpignan", "boulogne-billancourt",
        "metz", "besancon", "orleans", "rouen", "mulhouse", "caen", "argenteuil",
        "saint-paul", "montreuil", "nancy", "roubaix", "tourcoing", "nanterre",
        "avignon", "vitry-sur-seine", "creteil", "dunkerque", "poitiers", "asnieres",
        "courbevoie", "versailles", "colombes", "aubervilliers", "aulnay-sous-bois",
        "rueil-malmaison", "champigny-sur-marne", "saint-maur-des-fosses", "antibes",
        "cannes", "merignac", "drancy", "colmar", "ajaccio", "bourges", "beziers",
        "la rochelle", "saint-nazaire", "calais", "quimper", "valence", "pau",
        "chambery", "bayonne", "troyes", "niort", "lorient", "vannes", "cholet",
        "saint-herblain", "frejus", "hyeres", "saint-priest", "narbonne", "meaux",
        "bezons", "evry", "cergy", "pontoise", "melun", "fontainebleau", "chartres",
        "blois", "tours nord", "saumur", "angouleme", "la roche-sur-yon", "les sables",
        "sables d olonne", "laval", "vannes centre", "saint-brieuc", "morlaix",
        "quimperle", "douarnenez", "concarneau", "vannes golfe", "rennes centre",
        "saint-malo", "dinan", "fougeres", "vitre", "redon", "pornichet", "la baule escoublac",
        "coueron", "saint-sebastien-sur-loire", "reze centre", "orvault centre",
        "carquefou mairie", "bouguenais mairie", "saint-nazaire centre", "ancenis centre",
        "chateaubriant centre", "clisson chateau", "nantes centre", "nantes ile",
        "nantes erdre", "nantes loire", "nantes atlantique", "nantes nord",
        "nantes sud", "nantes est", "nantes ouest", "nantes chateau", "nantes commerce",
        "nantes gare", "nantes beaujoire", "nantes malakoff", "nantes dervallieres",
        "nantes breil", "nantes bellevue", "nantes doulon", "nantes saint-donatien",
    ]
    for city in cities:
        slug = city.replace(" ", "-").replace("'", "")
        add(city, f"{slug}.fr")
        add(f"mairie {city}", f"{slug}.fr")
        add(f"ville {city}", f"{slug}.fr")

    # ── Universités internationales ──
    unis = {
        "mit": "web.mit.edu",
        "harvard": "harvard.edu",
        "stanford": "stanford.edu",
        "berkeley": "berkeley.edu",
        "caltech": "caltech.edu",
        "yale": "yale.edu",
        "princeton": "princeton.edu",
        "columbia": "columbia.edu",
        "cornell": "cornell.edu",
        "upenn": "upenn.edu",
        "penn": "upenn.edu",
        "nyu": "nyu.edu",
        "ucla": "ucla.edu",
        "usc": "usc.edu",
        "cmu": "cmu.edu",
        "carnegie mellon": "cmu.edu",
        "georgia tech": "gatech.edu",
        "gatech": "gatech.edu",
        "umich": "umich.edu",
        "michigan": "umich.edu",
        "uiuc": "illinois.edu",
        "illinois": "illinois.edu",
        "uw": "washington.edu",
        "washington uni": "washington.edu",
        "oxford": "ox.ac.uk",
        "cambridge": "cam.ac.uk",
        "imperial": "imperial.ac.uk",
        "ucl": "ucl.ac.uk",
        "lse": "lse.ac.uk",
        "edinburgh": "ed.ac.uk",
        "manchester": "manchester.ac.uk",
        "warwick": "warwick.ac.uk",
        "bristol": "bristol.ac.uk",
        "eth zurich": "ethz.ch",
        "ethz": "ethz.ch",
        "epfl": "epfl.ch",
        "tu munich": "tum.de",
        "tum": "tum.de",
        "rwth aachen": "rwth-aachen.de",
        "rwth": "rwth-aachen.de",
        "heidelberg": "uni-heidelberg.de",
        "humboldt berlin": "hu-berlin.de",
        "tu berlin": "tu-berlin.de",
        "freie berlin": "fu-berlin.de",
        "amsterdam": "uva.nl",
        "uva": "uva.nl",
        "tu delft": "tudelft.nl",
        "delft": "tudelft.nl",
        "leiden": "universiteitleiden.nl",
        "copenhagen": "ku.dk",
        "kth": "kth.se",
        "lund": "lu.se",
        "oslo": "uio.no",
        "helsinki": "helsinki.fi",
        "trinity dublin": "tcd.ie",
        "tcd": "tcd.ie",
        "ucd": "ucd.ie",
        "toronto": "utoronto.ca",
        "mcgill": "mcgill.ca",
        "ubc": "ubc.ca",
        "waterloo": "uwaterloo.ca",
        "melbourne": "unimelb.edu.au",
        "sydney uni": "sydney.edu.au",
        "anu": "anu.edu.au",
        "nus": "nus.edu.sg",
        "ntu singapore": "ntu.edu.sg",
        "tsinghua": "tsinghua.edu.cn",
        "peking uni": "pku.edu.cn",
        "pku": "pku.edu.cn",
        "fudan": "fudan.edu.cn",
        "zhejiang uni": "zju.edu.cn",
        "zju": "zju.edu.cn",
        "tokyo uni": "u-tokyo.ac.jp",
        "utokyo": "u-tokyo.ac.jp",
        "kyoto uni": "kyoto-u.ac.jp",
        "osaka uni": "osaka-u.ac.jp",
        "seoul national": "snu.ac.kr",
        "snu": "snu.ac.kr",
        "kaist": "kaist.ac.kr",
        "technion": "technion.ac.il",
        "tel aviv uni": "tau.ac.il",
        "tau": "tau.ac.il",
        "sorbonne universite": "sorbonne-universite.fr",
        "universite paris saclay": "universite-paris-saclay.fr",
        "paris saclay": "universite-paris-saclay.fr",
        "psl": "psl.eu",
        "universite paris cite": "u-paris.fr",
        "universite lyon 1": "univ-lyon1.fr",
        "universite lyon 2": "univ-lyon2.fr",
        "universite lyon 3": "univ-lyon3.fr",
        "universite aix marseille": "univ-amu.fr",
        "amu": "univ-amu.fr",
        "universite toulouse 3": "univ-tlse3.fr",
        "universite paul sabatier": "univ-tlse3.fr",
        "universite montpellier 2": "umontpellier.fr",
        "universite lorraine": "univ-lorraine.fr",
        "universite de lorraine": "univ-lorraine.fr",
        "universite de rennes": "univ-rennes.fr",
        "universite de nantes": "univ-nantes.fr",
        "universite d angers": "univ-angers.fr",
        "universite de tours": "univ-tours.fr",
        "universite d orleans": "univ-orleans.fr",
        "universite de poitiers": "univ-poitiers.fr",
        "universite de la rochelle": "univ-lr.fr",
        "universite de brest": "univ-brest.fr",
        "universite de rennes 2": "univ-rennes2.fr",
        "universite de nantes st nazaire": "univ-nantes.fr",
        "universite catholique ouest": "uco.fr",
        "uco": "uco.fr",
        "icam": "icam.fr",
        "icam nantes": "icam.fr",
        "polytech nantes": "polytech-nantes.fr",
        "polytech rennes": "polytech-rennes.fr",
        "polytech angers": "polytech-angers.fr",
        "polytech tours": "polytech-tours.fr",
        "polytech montpellier": "polytech-montpellier.fr",
        "polytech grenoble": "polytech-grenoble.fr",
        "polytech nice": "polytech-nice.fr",
        "polytech marseille": "polytech-marseille.fr",
        "polytech lille": "polytech-lille.fr",
        "polytech sorbonne": "polytech-sorbonne.fr",
        "ensam": "ensam.eu",
        "arts et metiers": "ensam.eu",
        "ensta": "ensta.fr",
        "ensta paris": "ensta.fr",
        "ensta bretagne": "ensta-bretagne.fr",
        "imt atlantique": "imt-atlantique.fr",
        "imt atlantique nantes": "imt-atlantique.fr",
        "imt atlantique brest": "imt-atlantique.fr",
        "imt mines": "mines-telecom.fr",
        "mines paristech": "minesparis.psl.eu",
        "mines nancy": "mines-nancy.univ-lorraine.fr",
        "mines saint etienne": "mines-stetienne.fr",
        "telecom paris": "telecom-paris.fr",
        "telecom sudparis": "telecom-sudparis.eu",
        "telecom paris saclay": "telecom-paris.fr",
        "telecom nancy": "telecom-nancy.eu",
        "telecom bretagne": "imt-atlantique.fr",
        "ensae": "ensae.fr",
        "ensai": "ensai.fr",
        "enac": "enac.fr",
        "enac toulouse": "enac.fr",
        "isae supaero": "isae-supaero.fr",
        "supaero": "isae-supaero.fr",
        "isae ensma": "isae-ensma.fr",
        "ensma": "isae-ensma.fr",
        "estaca": "estaca.fr",
        "estaca nantes": "estaca.fr",
        "estaca paris": "estaca.fr",
        "cesi": "cesi.fr",
        "cesi nantes": "cesi.fr",
        "cesi rennes": "cesi.fr",
        "cesi angers": "cesi.fr",
        "cesi le mans": "cesi.fr",
        "cesi arras": "cesi.fr",
        "cesi montpellier": "cesi.fr",
        "cesi marseille": "cesi.fr",
        "cesi toulouse": "cesi.fr",
        "cesi bordeaux": "cesi.fr",
        "cesi lyon": "cesi.fr",
        "cesi paris": "cesi.fr",
        "cesi lille": "cesi.fr",
        "cesi strasbourg": "cesi.fr",
        "cesi rouen": "cesi.fr",
        "cesi reims": "cesi.fr",
        "cesi nancy": "cesi.fr",
        "cesi poitiers": "cesi.fr",
        "cesi la rochelle": "cesi.fr",
        "cesi brest": "cesi.fr",
        "cesi caen": "cesi.fr",
        "cesi dijon": "cesi.fr",
        "cesi grenoble": "cesi.fr",
        "cesi nice": "cesi.fr",
        "cesi saint nazaire": "cesi.fr",
        "cesi coueron": "cesi.fr",
        "cesi saint herblain": "cesi.fr",
        "cesi orvault": "cesi.fr",
        "cesi carquefou": "cesi.fr",
        "cesi reze": "cesi.fr",
        "cesi bouguenais": "cesi.fr",
        "cesi treillieres": "cesi.fr",
        "cesi indre": "cesi.fr",
        "cesi chateaubriant": "cesi.fr",
        "cesi ancenis": "cesi.fr",
        "cesi clisson": "cesi.fr",
        "cesi pornic": "cesi.fr",
        "cesi la baule": "cesi.fr",
        "cesi vannes": "cesi.fr",
        "cesi lorient": "cesi.fr",
        "cesi quimper": "cesi.fr",
        "cesi brest centre": "cesi.fr",
        "cesi saint malo": "cesi.fr",
        "cesi dinan": "cesi.fr",
        "cesi fougeres": "cesi.fr",
        "cesi vitre": "cesi.fr",
        "cesi redon": "cesi.fr",
        "cesi pornichet": "cesi.fr",
        "cesi nantes centre": "cesi.fr",
        "cesi nantes sud": "cesi.fr",
        "cesi nantes nord": "cesi.fr",
        "cesi nantes est": "cesi.fr",
        "cesi nantes ouest": "cesi.fr",
        "cesi nantes ile": "cesi.fr",
        "cesi nantes erdre": "cesi.fr",
        "cesi nantes loire": "cesi.fr",
        "cesi nantes atlantique": "cesi.fr",
        "cesi nantes chateau": "cesi.fr",
        "cesi nantes commerce": "cesi.fr",
        "cesi nantes gare": "cesi.fr",
        "cesi nantes beaujoire": "cesi.fr",
        "cesi nantes malakoff": "cesi.fr",
        "cesi nantes dervallieres": "cesi.fr",
        "cesi nantes breil": "cesi.fr",
        "cesi nantes bellevue": "cesi.fr",
        "cesi nantes doulon": "cesi.fr",
        "cesi nantes saint donatien": "cesi.fr",
    }
    adds(unis)

    # ── Domotique & maker ──
    domo = {
        "home assistant": "home-assistant.io",
        "homeassistant": "home-assistant.io",
        "hass": "home-assistant.io",
        "openhab": "openhab.org",
        "domoticz": "domoticz.com",
        "node red": "nodered.org",
        "nodered": "nodered.org",
        "mqtt": "mqtt.org",
        "mosquitto": "mosquitto.org",
        "zigbee2mqtt": "zigbee2mqtt.io",
        "zwave js": "zwave-js.io",
        "zwavejs": "zwave-js.io",
        "esphome": "esphome.io",
        "tasmota": "tasmota.github.io",
        "openwrt": "openwrt.org",
        "pfsense": "pfsense.org",
        "opnsense": "opnsense.org",
        "truenas": "truenas.com",
        "freenas": "truenas.com",
        "unraid": "unraid.net",
        "proxmox": "proxmox.com",
        "esxi": "vmware.com/products/esxi-and-esx.html",
        "vmware": "vmware.com",
        "virtualbox": "virtualbox.org",
        "qemu": "qemu.org",
        "kvm": "linux-kvm.org",
        "hyper-v": "learn.microsoft.com/virtualization/hyper-v-on-windows",
        "parallels": "parallels.com",
        "utm mac": "mac.getutm.app",
        "utm": "mac.getutm.app",
        "synology": "synology.com",
        "qnap": "qnap.com",
        "asustor": "asustor.com",
        "terramaster": "terra-master.com",
        "pi hole": "pi-hole.net",
        "pihole": "pi-hole.net",
        "adguard home": "adguard.com/adguard-home",
        "adguard": "adguard.com",
        "nextdns": "nextdns.io",
        "opendns": "opendns.com",
        "unifi": "ui.com",
        "ubiquiti": "ui.com",
        "mikrotik": "mikrotik.com",
        "tp link omada": "tp-link.com/omada",
        "omada": "tp-link.com/omada",
        "homebridge": "homebridge.io",
        "matter smart home": "csa-iot.org/all-solutions/matter",
        "matter iot": "csa-iot.org/all-solutions/matter",
        "smartthings": "smartthings.com",
        "tuya smart": "tuya.com",
        "tuya": "tuya.com",
        "philips hue": "philips-hue.com",
        "hue": "philips-hue.com",
        "lifx": "lifx.com",
        "nanoleaf": "nanoleaf.me",
        "govee": "govee.com",
        "aqara": "aqara.com",
        "sonoff": "sonoff.tech",
        "shelly": "shelly.com",
        "fibaro": "fibaro.com",
        "netatmo": "netatmo.com",
        "somfy": "somfy.com",
        "tado": "tado.com",
        "nest": "nest.com",
        "ring": "ring.com",
        "arlo": "arlo.com",
        "wyze": "wyze.com",
        "eufy": "eufylife.com",
        "reolink": "reolink.com",
        "hikvision": "hikvision.com",
        "dahua": "dahuasecurity.com",
        "frigate nvr": "frigate.video",
        "frigate": "frigate.video",
        "scrypted": "scrypted.app",
        "blue iris": "blueirissoftware.com",
    }
    adds(domo)

    # ── Automotive ──
    auto = {
        "renault": "renault.fr",
        "peugeot": "peugeot.fr",
        "citroen": "citroen.fr",
        "ds automobiles": "dsautomobiles.fr",
        "ds": "dsautomobiles.fr",
        "dacia": "dacia.fr",
        "alpine": "alpine-cars.fr",
        "bugatti": "bugatti.com",
        "volkswagen": "volkswagen.fr",
        "vw": "volkswagen.fr",
        "audi": "audi.fr",
        "skoda": "skoda.fr",
        "seat": "seat.fr",
        "cupra": "cupraofficial.fr",
        "porsche": "porsche.fr",
        "bmw": "bmw.fr",
        "mini": "mini.fr",
        "mercedes": "mercedes-benz.fr",
        "mercedes benz": "mercedes-benz.fr",
        "smart": "smart.com",
        "opel": "opel.fr",
        "fiat": "fiat.fr",
        "abarth": "abarth.fr",
        "alfa romeo": "alfaromeo.fr",
        "lancia": "lancia.fr",
        "maserati": "maserati.com",
        "ferrari": "ferrari.com",
        "lamborghini": "lamborghini.com",
        "pagani": "pagani.com",
        "mclaren": "mclaren.com",
        "aston martin": "astonmartin.com",
        "bentley": "bentley.com",
        "rolls royce": "rolls-roycemotorcars.com",
        "rolls-royce": "rolls-roycemotorcars.com",
        "jaguar": "jaguar.fr",
        "land rover": "landrover.fr",
        "landrover": "landrover.fr",
        "range rover": "landrover.fr",
        "volvo": "volvocars.com",
        "polestar": "polestar.com",
        "tesla": "tesla.com",
        "rivian": "rivian.com",
        "lucid": "lucidmotors.com",
        "nio": "nio.com",
        "xpeng": "xpeng.com",
        "byd": "byd.com",
        "hyundai": "hyundai.fr",
        "kia": "kia.fr",
        "genesis": "genesis.com",
        "toyota": "toyota.fr",
        "lexus": "lexus.fr",
        "honda": "honda.fr",
        "mazda": "mazda.fr",
        "nissan": "nissan.fr",
        "infiniti": "infiniti.fr",
        "mitsubishi": "mitsubishi-motors.fr",
        "subaru": "subaru.fr",
        "suzuki": "suzuki.fr",
        "isuzu": "isuzu.fr",
        "jeep": "jeep.fr",
        "dodge": "dodge.com",
        "chrysler": "chrysler.com",
        "ram trucks": "ramtrucks.com",
        "ford": "ford.fr",
        "lincoln": "lincoln.com",
        "chevrolet": "chevrolet.fr",
        "cadillac": "cadillac.fr",
        "gmc": "gmc.com",
        "buick": "buick.com",
        "lada": "lada.ru",
        "tata motors": "tatamotors.com",
        "mahindra": "auto.mahindra.com",
        "geely": "global.geely.com",
        "great wall": "gwm-global.com",
        "gwm": "gwm-global.com",
        "chery": "cheryinternational.com",
        "saic": "saicmotor.com",
        "mg motor": "mgmotor.fr",
        "mg": "mgmotor.fr",
        "l auto journal": "largus.fr",
        "largus": "largus.fr",
        "caradisiac": "caradisiac.com",
        "autoplus": "autoplus.fr",
        "auto moto": "auto-moto.com",
        "automoto": "auto-moto.com",
        "motor1": "motor1.com",
        "top gear": "topgear.com",
        "topgear": "topgear.com",
        "car and driver": "caranddriver.com",
        "caranddriver": "caranddriver.com",
        "road and track": "roadandtrack.com",
        "roadandtrack": "roadandtrack.com",
        "autotrader": "autotrader.fr",
        "lacentrale": "lacentrale.fr",
        "la centrale": "lacentrale.fr",
        "autoscout24": "autoscout24.fr",
        "auto scout": "autoscout24.fr",
        "heycar": "heycar.fr",
        "spoticar": "spoticar.fr",
        "argus auto": "largus.fr",
        "mobile de": "mobile.de",
        "mobilede": "mobile.de",
        "autotrader uk": "autotrader.co.uk",
        "cars com": "cars.com",
        "cars.com": "cars.com",
        "edmunds": "edmunds.com",
        "kbb": "kbb.com",
        "kelley blue book": "kbb.com",
    }
    adds(auto)

    # ── Crypto / Web3 (complément) ──
    crypto = {
        "etherscan": "etherscan.io",
        "bscscan": "bscscan.com",
        "polygonscan": "polygonscan.com",
        "arbiscan": "arbiscan.io",
        "optimistic etherscan": "optimistic.etherscan.io",
        "basescan": "basescan.org",
        "snowtrace": "snowtrace.io",
        "ftmscan": "ftmscan.com",
        "solscan": "solscan.io",
        "solana fm": "solana.fm",
        "solanafm": "solana.fm",
        "mempool space": "mempool.space",
        "mempool": "mempool.space",
        "blockchair": "blockchair.com",
        "blockchain com": "blockchain.com",
        "blockchain.com": "blockchain.com",
        "blockstream": "blockstream.com",
        "lightning network": "lightning.network",
        "lightning": "lightning.network",
        "metamask": "metamask.io",
        "phantom wallet": "phantom.app",
        "phantom": "phantom.app",
        "rabby wallet": "rabby.io",
        "rabby": "rabby.io",
        "rainbow wallet": "rainbow.me",
        "rainbow": "rainbow.me",
        "ledger live": "ledger.com",
        "ledger": "ledger.com",
        "trezor": "trezor.io",
        "uniswap": "app.uniswap.org",
        "sushiswap": "sushi.com",
        "pancakeswap": "pancakeswap.finance",
        "curve finance": "curve.fi",
        "curve": "curve.fi",
        "aave": "aave.com",
        "compound finance": "compound.finance",
        "compound": "compound.finance",
        "makerdao": "makerdao.com",
        "maker dao": "makerdao.com",
        "lido": "lido.fi",
        "rocket pool": "rocketpool.net",
        "rocketpool": "rocketpool.net",
        "opensea": "opensea.io",
        "blur io": "blur.io",
        "blur nft": "blur.io",
        "blur": "blur.io",
        "magiceden": "magiceden.io",
        "magic eden": "magiceden.io",
        "looksrare": "looksrare.org",
        "foundation nft": "foundation.app",
        "foundation": "foundation.app",
        "zora": "zora.co",
        "manifold": "manifold.xyz",
        "debank": "debank.com",
        "zapper": "zapper.xyz",
        "zerion": "zerion.io",
        "dexscreener": "dexscreener.com",
        "dextools": "dextools.io",
        "geckoterminal": "geckoterminal.com",
        "defillama": "defillama.com",
        "defi llama": "defillama.com",
        "dune analytics": "dune.com",
        "dune": "dune.com",
        "nansen": "nansen.ai",
        "glassnode": "glassnode.com",
        "cryptoquant": "cryptoquant.com",
        "messari": "messari.io",
        "the block": "theblock.co",
        "theblock": "theblock.co",
        "decrypt": "decrypt.co",
        "cointelegraph": "cointelegraph.com",
        "bitcoin org": "bitcoin.org",
        "bitcoin": "bitcoin.org",
        "ethereum org": "ethereum.org",
        "ethereum": "ethereum.org",
        "solana com": "solana.com",
        "solana": "solana.com",
        "cardano org": "cardano.org",
        "cardano": "cardano.org",
        "polkadot network": "polkadot.network",
        "polkadot": "polkadot.network",
        "cosmos network": "cosmos.network",
        "cosmos": "cosmos.network",
        "near protocol": "near.org",
        "near": "near.org",
        "aptos": "aptosfoundation.org",
        "sui network": "sui.io",
        "sui": "sui.io",
        "arbitrum": "arbitrum.io",
        "optimism io": "optimism.io",
        "optimism": "optimism.io",
        "base chain": "base.org",
        "base org": "base.org",
        "zksync": "zksync.io",
        "starknet": "starknet.io",
        "linea": "linea.build",
        "scroll io": "scroll.io",
        "scroll": "scroll.io",
        "polygon technology": "polygon.technology",
        "polygon": "polygon.technology",
        "chainlink": "chain.link",
        "the graph": "thegraph.com",
        "thegraph": "thegraph.com",
        "ipfs": "ipfs.io",
        "filecoin": "filecoin.io",
        "arweave": "arweave.org",
        "ens domains": "ens.domains",
        "ens": "ens.domains",
        "unstoppable domains": "unstoppabledomains.com",
        "snapshot org": "snapshot.org",
        "snapshot": "snapshot.org",
        "gnosis safe": "safe.global",
        "safe wallet": "safe.global",
        "safe global": "safe.global",
    }
    adds(crypto)

    # ── Productivité & créatif (complément) ──
    productivity = {
        "loom": "loom.com",
        "tango": "tango.us",
        "screencastify": "screencastify.com",
        "obs studio": "obsproject.com",
        "obsproject": "obsproject.com",
        "streamlabs": "streamlabs.com",
        "stream elements": "streamelements.com",
        "streamelements": "streamelements.com",
        "lightstream": "lightstream.com",
        "restream": "restream.io",
        "riverside fm": "riverside.fm",
        "riverside": "riverside.fm",
        "cleanfeed": "cleanfeed.net",
        "zencastr": "zencastr.com",
        "anchor fm": "anchor.fm",
        "anchor": "anchor.fm",
        "spotify for podcasters": "podcasters.spotify.com",
        "podcasters spotify": "podcasters.spotify.com",
        "buzzsprout": "buzzsprout.com",
        "transistor fm": "transistor.fm",
        "transistor": "transistor.fm",
        "podbean": "podbean.com",
        "captivate fm": "captivate.fm",
        "captivate": "captivate.fm",
        "webflow": "webflow.com",
        "framer sites": "framer.com",
        "framer": "framer.com",
        "squarespace": "squarespace.com",
        "wix": "wix.com",
        "shopify store": "shopify.com",
        "shopify admin": "admin.shopify.com",
        "woocommerce": "woocommerce.com",
        "prestashop": "prestashop.com",
        "magento": "business.adobe.com/products/magento/magento-commerce.html",
        "bigcommerce": "bigcommerce.com",
        "stripe dashboard": "dashboard.stripe.com",
        "paypal business": "paypal.com/business",
        "gumroad": "gumroad.com",
        "lemonsqueezy": "lemonsqueezy.com",
        "paddle": "paddle.com",
        "fastspring": "fastspring.com",
        "itch io store": "itch.io",
        "itchio": "itch.io",
        "ko fi": "ko-fi.com",
        "kofi": "ko-fi.com",
        "patreon": "patreon.com",
        "buymeacoffee": "buymeacoffee.com",
        "buy me a coffee": "buymeacoffee.com",
        "tipeee": "tipeee.com",
        "utip": "utip.io",
        "helloasso": "helloasso.com",
        "hello asso": "helloasso.com",
        "donorbox": "donorbox.org",
        "givebutter": "givebutter.com",
        "crowdfund": "kickstarter.com",
        "indiegogo": "indiegogo.com",
        "ulule": "ulule.com",
        "kisskissbankbank": "kisskissbankbank.com",
        "kkbb": "kisskissbankbank.com",
        "wemakeit": "wemakeit.com",
        "goteo": "goteo.org",
        "crowdcube": "crowdcube.com",
        "seedrs": "seedrs.com",
        "angellist": "wellfound.com",
        "wellfound": "wellfound.com",
        "crunchbase": "crunchbase.com",
        "pitchbook": "pitchbook.com",
        "dealroom": "dealroom.co",
        "tracxn": "tracxn.com",
        "product hunt": "producthunt.com",
        "producthunt": "producthunt.com",
        "ph": "producthunt.com",
        "betalist": "betalist.com",
        "launching next": "launchingnext.com",
        "saas hub": "saashub.com",
        "saashub": "saashub.com",
        "g2 reviews": "g2.com",
        "g2": "g2.com",
        "capterra": "capterra.com",
        "getapp": "getapp.com",
        "software advice": "softwareadvice.com",
        "trustpilot": "trustpilot.com",
        "avis verifies": "avis-verifies.com",
        "avis verifiés": "avis-verifies.com",
    }
    adds(productivity)

    # ── Génération programmatic : docs npm populaires ──
    npm_packages = [
        "react", "vue", "angular", "svelte", "next", "nuxt", "remix", "astro",
        "express", "fastify", "koa", "hono", "nestjs", "trpc", "prisma",
        "drizzle-orm", "typeorm", "sequelize", "mongoose", "axios", "got",
        "node-fetch", "undici", "ws", "socket.io", "puppeteer", "playwright",
        "cypress", "jest", "vitest", "mocha", "chai", "eslint", "prettier",
        "webpack", "vite", "rollup", "esbuild", "turbo", "nx", "lerna",
        "storybook", "tailwindcss", "sass", "postcss", "styled-components",
        "emotion", "framer-motion", "three", "d3", "chart.js", "lodash",
        "date-fns", "moment", "dayjs", "uuid", "nanoid", "zod", "yup",
        "joi", "class-validator", "dotenv", "winston", "pino", "debug",
        "commander", "yargs", "inquirer", "chalk", "ora", "nodemon",
        "ts-node", "tsx", "typescript", "babel", "swc", "esbuild-register",
    ]
    for pkg in npm_packages:
        add(f"npm {pkg}", f"npmjs.com/package/{pkg}")
        add(f"{pkg} npm", f"npmjs.com/package/{pkg}")

    # ── Génération : PyPI populaires ──
    pypi_packages = [
        "requests", "httpx", "aiohttp", "fastapi", "flask", "django", "starlette",
        "uvicorn", "gunicorn", "pydantic", "sqlalchemy", "alembic", "psycopg2",
        "asyncpg", "redis", "celery", "rq", "dramatiq", "pytest", "hypothesis",
        "black", "ruff", "mypy", "isort", "flake8", "pylint", "bandit",
        "numpy", "pandas", "scipy", "matplotlib", "seaborn", "plotly",
        "scikit-learn", "sklearn", "tensorflow", "torch", "pytorch", "keras",
        "transformers", "datasets", "accelerate", "peft", "trl", "bitsandbytes",
        "langchain", "llama-index", "chromadb", "faiss-cpu", "sentence-transformers",
        "openai", "anthropic", "tiktoken", "pillow", "opencv-python", "moviepy",
        "beautifulsoup4", "lxml", "scrapy", "selenium", "playwright", "typer",
        "click", "rich", "textual", "streamlit", "gradio", "panel", "dash",
        "polars", "duckdb", "pyarrow", "dask", "ray", "mlflow", "wandb",
        "poetry", "pipenv", "uv", "hatch", "setuptools", "wheel", "twine",
    ]
    for pkg in pypi_packages:
        add(f"pypi {pkg}", f"pypi.org/project/{pkg}")
        add(f"{pkg} pypi", f"pypi.org/project/{pkg}")

    # ── Génération : crates Rust populaires ──
    rust_crates = [
        "serde", "tokio", "reqwest", "axum", "actix-web", "rocket", "warp",
        "hyper", "tungstenite", "sqlx", "diesel", "sea-orm", "clap", "anyhow",
        "thiserror", "tracing", "log", "env_logger", "rand", "regex", "chrono",
        "uuid", "serde_json", "toml", "yaml-rust", "candle-core", "burn",
        "polars", "ndarray", "image", "png", "webp", "ffmpeg-next", "rodio",
        "bevy", "macroquad", "ggez", "wgpu", "winit", "egui", "iced",
        "tauri", "dioxus", "leptos", "yew", "ratatui", "crossterm",
    ]
    for crate in rust_crates:
        add(f"crate {crate}", f"crates.io/crates/{crate}")
        add(f"{crate} crate", f"crates.io/crates/{crate}")
        add(f"rust {crate}", f"docs.rs/{crate}")

    # ── Fonts, icônes, assets ──
    assets = {
        "google fonts": "fonts.google.com",
        "fonts google": "fonts.google.com",
        "fontshare": "fontshare.com",
        "dafont": "dafont.com",
        "font squirrel": "fontsquirrel.com",
        "fontsquirrel": "fontsquirrel.com",
        "myfonts": "myfonts.com",
        "fontspace": "fontspace.com",
        "1001fonts": "1001fonts.com",
        "font awesome": "fontawesome.com",
        "fontawesome": "fontawesome.com",
        "heroicons": "heroicons.com",
        "lucide icons": "lucide.dev",
        "lucide": "lucide.dev",
        "phosphor icons": "phosphoricons.com",
        "phosphor": "phosphoricons.com",
        "tabler icons": "tabler.io/icons",
        "tabler": "tabler.io/icons",
        "bootstrap icons": "icons.getbootstrap.com",
        "material icons": "fonts.google.com/icons",
        "material symbols": "fonts.google.com/icons",
        "ionicons": "ionic.io/ionicons",
        "feather icons": "feathericons.com",
        "feathericons": "feathericons.com",
        "remix icon": "remixicon.com",
        "remixicon": "remixicon.com",
        "iconify": "iconify.design",
        "svg repo": "svgrepo.com",
        "svgrepo": "svgrepo.com",
        "undraw": "undraw.co",
        "storyset": "storyset.com",
        "freepik": "freepik.com",
        "flaticon": "flaticon.com",
        "icons8": "icons8.com",
        "thenounproject": "thenounproject.com",
        "noun project": "thenounproject.com",
        "unsplash": "unsplash.com",
        "pexels": "pexels.com",
        "pixabay": "pixabay.com",
        "burst shopify": "burst.shopify.com",
        "burst": "burst.shopify.com",
        "coverr": "coverr.co",
        "mixkit": "mixkit.co",
        "videvo": "videvo.net",
        "freesound": "freesound.org",
        "zapsplat": "zapsplat.com",
        "opengameart": "opengameart.org",
        "kenney": "kenney.nl",
        "itch io assets": "itch.io/game-assets",
        "unity asset store": "assetstore.unity.com",
        "unreal marketplace": "unrealengine.com/marketplace",
        "sketchfab": "sketchfab.com",
        "poly pizza": "poly.pizza",
        "polypizza": "poly.pizza",
        "turbosquid": "turbosquid.com",
        "cgtrader": "cgtrader.com",
        "blend swap": "blendswap.com",
        "blendswap": "blendswap.com",
        "poly haven": "polyhaven.com",
        "polyhaven": "polyhaven.com",
        "hdri haven": "polyhaven.com",
        "texture haven": "polyhaven.com",
        "ambientcg": "ambientcg.com",
        "cc0 textures": "cc0textures.com",
        "3dtextures": "3dtextures.me",
        "quixel megascans": "quixel.com/megascans",
        "megascans": "quixel.com/megascans",
        "substance 3d assets": "substance3d.adobe.com/assets",
        "adobe stock": "stock.adobe.com",
        "shutterstock": "shutterstock.com",
        "getty images": "gettyimages.fr",
        "gettyimages": "gettyimages.fr",
        "istock": "istockphoto.com",
        "depositphotos": "depositphotos.com",
        "123rf": "123rf.com",
        "envato elements": "elements.envato.com",
        "envato": "envato.com",
        "creative market": "creativemarket.com",
        "creativemarket": "creativemarket.com",
        "design cuts": "designcuts.com",
        "designcuts": "designcuts.com",
        "fontbundles": "fontbundles.net",
        "dafont free": "dafont.com",
        "behance": "behance.net",
        "dribbble": "dribbble.com",
        "artstation": "artstation.com",
        "deviantart": "deviantart.com",
        "pixiv": "pixiv.net",
        "newgrounds": "newgrounds.com",
        "coolors": "coolors.co",
        "colorhunt": "colorhunt.co",
        "adobe color": "color.adobe.com",
        "color adobe": "color.adobe.com",
        "paletton": "paletton.com",
        "colormind": "colormind.io",
        "happy hues": "happyhues.co",
        "happyhues": "happyhues.co",
        "realtime colors": "realtimecolors.com",
        "contrast checker": "webaim.org/resources/contrastchecker",
        "webaim": "webaim.org",
        "a11y project": "a11yproject.com",
        "a11yproject": "a11yproject.com",
        "wave tool": "wave.webaim.org",
        "wave accessibility": "wave.webaim.org",
        "axe devtools": "deque.com/axe/devtools",
        "deque": "deque.com",
        "pa11y": "pa11y.org",
        "lighthouse": "developer.chrome.com/docs/lighthouse",
        "pagespeed insights": "pagespeed.web.dev",
        "pagespeed": "pagespeed.web.dev",
        "web dev": "web.dev",
        "webdev": "web.dev",
        "developers google": "developers.google.com",
        "developer chrome": "developer.chrome.com",
        "developer mozilla": "developer.mozilla.org",
        "developer apple": "developer.apple.com",
        "developer android": "developer.android.com",
        "developer microsoft": "developer.microsoft.com",
        "learn microsoft": "learn.microsoft.com",
        "docs microsoft": "learn.microsoft.com",
        "azure docs": "learn.microsoft.com/azure",
        "aws docs": "docs.aws.amazon.com",
        "gcp docs": "cloud.google.com/docs",
    }
    adds(assets)

    # ── Gouvernements & administrations (EU + monde) ──
    gov_sites = {
        "gouvernement fr": "gouvernement.fr",
        "gouvernement": "gouvernement.fr",
        "elysee": "elysee.fr",
        "elysée": "elysee.fr",
        "assemblee nationale": "assemblee-nationale.fr",
        "assemblee-nationale": "assemblee-nationale.fr",
        "senat": "senat.fr",
        "sénat": "senat.fr",
        "conseil constitutionnel": "conseil-constitutionnel.fr",
        "conseil-constitutionnel": "conseil-constitutionnel.fr",
        "conseil etat": "conseil-etat.fr",
        "conseil-etat": "conseil-etat.fr",
        "cour de cassation": "courdecassation.fr",
        "courdecassation": "courdecassation.fr",
        "cour des comptes": "ccomptes.fr",
        "ccomptes": "ccomptes.fr",
        "defense gouv": "defense.gouv.fr",
        "ministere armed forces": "defense.gouv.fr",
        "education gouv": "education.gouv.fr",
        "sante gouv": "sante.gouv.fr",
        "culture gouv": "culture.gouv.fr",
        "ecologie gouv": "ecologie.gouv.fr",
        "transition ecologique": "ecologie.gouv.fr",
        "agriculture gouv": "agriculture.gouv.fr",
        "interieur gouv": "interieur.gouv.fr",
        "europe gouv": "diplomatie.gouv.fr",
        "marches publics": "marches-publics.gouv.fr",
        "boamp": "boamp.fr",
        "place marchés": "marches-publics.gouv.fr",
        "gov uk": "gov.uk",
        "govuk": "gov.uk",
        "usa gov": "usa.gov",
        "whitehouse": "whitehouse.gov",
        "congress gov": "congress.gov",
        "congress": "congress.gov",
        "senate gov": "senate.gov",
        "house gov": "house.gov",
        "supreme court us": "supremecourt.gov",
        "supremecourt": "supremecourt.gov",
        "canada ca": "canada.ca",
        "gob mx": "gob.mx",
        "gov br": "gov.br",
        "gov au": "gov.au",
        "gov nz": "govt.nz",
        "gov in": "gov.in",
        "gov sg": "gov.sg",
        "gov jp": "japan.go.jp",
        "gov kr": "go.kr",
        "gov cn": "gov.cn",
        "bund de": "bund.de",
        "gouvernement belgique": "belgium.be",
        "gouvernement suisse": "admin.ch",
        "admin ch": "admin.ch",
        "gouvernement luxembourg": "gouvernement.lu",
        "gouvernement lu": "gouvernement.lu",
        "gouvernement canada": "canada.ca",
        "europa eu": "europa.eu",
        "europa": "europa.eu",
        "european commission": "ec.europa.eu",
        "commission europeenne": "ec.europa.eu",
        "parliament europe": "europarl.europa.eu",
        "parlement europeen": "europarl.europa.eu",
        "europarl": "europarl.europa.eu",
        "consilium": "consilium.europa.eu",
        "conseil europe": "consilium.europa.eu",
        "ecb": "ecb.europa.eu",
        "bce": "ecb.europa.eu",
        "banque centrale europeenne": "ecb.europa.eu",
        "court of justice eu": "curia.europa.eu",
        "curia": "curia.europa.eu",
        "euipo": "euipo.europa.eu",
        "epo": "epo.org",
        "office brevet europeen": "epo.org",
        "wipo": "wipo.int",
        "ompi": "wipo.int",
        "un org": "un.org",
        "onu": "un.org",
        "unesco": "unesco.org",
        "unicef": "unicef.org",
        "undp": "undp.org",
        "world bank": "worldbank.org",
        "banque mondiale": "worldbank.org",
        "imf": "imf.org",
        "fmi": "imf.org",
        "oecd": "oecd.org",
        "ocde": "oecd.org",
        "wto": "wto.org",
        "omc": "wto.org",
    }
    adds(gov_sites)

    # ── Retro gaming & émulation (ressources légales) ──
    retro = {
        "retrogames cc": "retrogames.cc",
        "retrogames": "retrogames.cc",
        "archive gaming": "archive.org/details/softwarelibrary",
        "my abandonware": "myabandonware.com",
        "myabandonware": "myabandonware.com",
        "abandonware dos": "abandonwaredos.com",
        "classic reload": "classicreload.com",
        "classicreload": "classicreload.com",
        "dosgames com": "dosgames.com",
        "dosgames": "dosgames.com",
        "play classic games": "playclassic.games",
        "playclassic": "playclassic.games",
        "emulator games net": "emulatorgames.net",
        "coolrom": "coolrom.com.au",
        "romsmania": "romsmania.cc",
        "vimm net": "vimm.net",
        "vimm": "vimm.net",
        "citra emulator": "citra-emu.org",
        "citra": "citra-emu.org",
        "yuzu": "yuzu-emu.org",
        "ryujinx": "ryujinx.org",
        "dolphin emulator": "dolphin-emu.org",
        "dolphin": "dolphin-emu.org",
        "pcsx2": "pcsx2.net",
        "rpcs3": "rpcs3.net",
        "xemu": "xemu.app",
        "cemu": "cemu.info",
        "duckstation": "duckstation.org",
        "retroarch": "retroarch.com",
        "launchbox": "launchbox-app.com",
        "hyperspin": "hyperspin-fe.com",
        "mame": "mamedev.org",
        "openemu": "openemu.org",
        "ppsspp": "ppsspp.org",
        "desmume": "desmume.org",
        "melonds": "melonds.kuribo64.net",
        "cemu wiki": "cemu.info",
        "emulation wiki": "emulation.gametechwiki.com",
        "gametechwiki": "emulation.gametechwiki.com",
        "speedrun wiki": "speedrunwiki.com",
        "tasvideos": "tasvideos.org",
        "rpgmaker net": "rpgmakerweb.com",
        "rmw": "rpgmakerweb.com",
        "srpg studio": "srpgstudio.com",
        "wolf rpg editor": "wolf-rpg.com",
        "rpg maker vx ace": "rpgmakerweb.com",
        "rpg maker mv": "rpgmakerweb.com",
        "rpg maker mz": "rpgmakerweb.com",
        "gbstudio": "gbstudio.dev",
        "bitsy": "ledoux.itch.io/bitsy",
        "pico8": "lexaloffle.com/pico-8.php",
        "pico-8": "lexaloffle.com/pico-8.php",
        "tic80": "tic80.com",
        "tic-80": "tic80.com",
        "splore": "lexaloffle.com/pico-8.php",
        "lexaloffle": "lexaloffle.com",
        "voxatron": "lexaloffle.com/voxatron.php",
        "dreamcast wiki": "segaretro.org",
        "segaretro": "segaretro.org",
        "tcrf": "tcrf.net",
        "hidden palace": "hiddenpalace.org",
        "hiddenpalace": "hiddenpalace.org",
        "vgmrips": "vgmrips.net",
        "khinsider": "downloads.khinsider.com",
        "zophar": "zophar.net",
        "emuparadise": "emuparadise.me",
    }
    adds(retro)

    # ── Génération : pays ISO → site tourisme / gouvernement ──
    countries = {
        "france": "gouvernement.fr",
        "allemagne": "bund.de",
        "germany": "bund.de",
        "italie": "governo.it",
        "italy": "governo.it",
        "espagne": "lamoncloa.gob.es",
        "spain": "lamoncloa.gob.es",
        "portugal": "portugal.gov.pt",
        "belgique": "belgium.be",
        "belgium": "belgium.be",
        "suisse": "admin.ch",
        "switzerland": "admin.ch",
        "luxembourg": "gouvernement.lu",
        "pays bas": "government.nl",
        "netherlands": "government.nl",
        "hollande": "government.nl",
        "royaume uni": "gov.uk",
        "uk": "gov.uk",
        "irlande": "gov.ie",
        "ireland": "gov.ie",
        "danemark": "denmark.dk",
        "denmark": "denmark.dk",
        "suede": "sweden.se",
        "sweden": "sweden.se",
        "norvege": "regjeringen.no",
        "norway": "regjeringen.no",
        "finlande": "valtioneuvosto.fi",
        "finland": "valtioneuvosto.fi",
        "pologne": "gov.pl",
        "poland": "gov.pl",
        "republique tcheque": "vlada.cz",
        "czech republic": "vlada.cz",
        "slovaquie": "vlada.gov.sk",
        "slovakia": "vlada.gov.sk",
        "hongrie": "kormany.hu",
        "hungary": "kormany.hu",
        "roumanie": "gov.ro",
        "romania": "gov.ro",
        "bulgarie": "gov.bg",
        "bulgaria": "gov.bg",
        "grece": "gov.gr",
        "greece": "gov.gr",
        "turquie": "tccb.gov.tr",
        "turkey": "tccb.gov.tr",
        "russie": "government.ru",
        "russia": "government.ru",
        "ukraine": "president.gov.ua",
        "japon": "japan.go.jp",
        "japan": "japan.go.jp",
        "coree du sud": "go.kr",
        "south korea": "go.kr",
        "chine": "gov.cn",
        "china": "gov.cn",
        "inde": "gov.in",
        "india": "gov.in",
        "australie": "gov.au",
        "australia": "gov.au",
        "nouvelle zelande": "govt.nz",
        "new zealand": "govt.nz",
        "canada": "canada.ca",
        "mexique": "gob.mx",
        "mexico": "gob.mx",
        "bresil": "gov.br",
        "brazil": "gov.br",
        "argentine": "argentina.gob.ar",
        "argentina": "argentina.gob.ar",
        "chili": "gob.cl",
        "chile": "gob.cl",
        "colombie": "gov.co",
        "colombia": "gov.co",
        "afrique du sud": "gov.za",
        "south africa": "gov.za",
        "maroc": "gov.ma",
        "morocco": "gov.ma",
        "algerie": "el-mouradia.dz",
        "algeria": "el-mouradia.dz",
        "tunisie": "carthage.tn",
        "tunisia": "carthage.tn",
        "egypte": "presidency.eg",
        "egypt": "presidency.eg",
        "israel": "gov.il",
        "arabie saoudite": "my.gov.sa",
        "saudi arabia": "my.gov.sa",
        "emirats arabes unis": "u.ae",
        "uae": "u.ae",
        "qatar gov": "gov.qa",
        "singapour": "gov.sg",
        "singapore": "gov.sg",
        "malaisie": "malaysia.gov.my",
        "malaysia": "malaysia.gov.my",
        "thailande": "thaigov.go.th",
        "thailand": "thaigov.go.th",
        "vietnam": "chinhphu.vn",
        "indonesie": "indonesia.go.id",
        "indonesia": "indonesia.go.id",
        "philippines": "gov.ph",
    }
    adds(countries)

    return d
