"""Catalogue massif d'alias sites — batch 4."""
from __future__ import annotations

from urllib.parse import quote_plus


def get_batch4() -> dict[str, str]:
    d: dict[str, str] = {}

    def add(alias: str, domain: str) -> None:
        d[alias.strip().lower()] = domain

    def adds(items: dict[str, str]) -> None:
        for k, v in items.items():
            add(k, v)

    adds({
        # Échecs & jeux de société en ligne
        "lichess": "lichess.org",
        "chess com": "chess.com",
        "chess.com": "chess.com",
        "chess24": "chess24.com",
        "chessbase": "chessbase.com",
        "chessgames": "chessgames.com",
        "fide": "fide.com",
        "ffe": "ffe.fr",
        "federation francaise echecs": "ffe.fr",
        "echecs": "ffe.fr",
        "échecs": "ffe.fr",
        "chessable": "chessable.com",
        "chess tempo": "chesstempo.com",
        "chesstempo": "chesstempo.com",
        "online go": "online-go.com",
        "online-go": "online-go.com",
        "ogb": "online-go.com",
        "woogles": "woogles.io",
        "funbridge": "funbridge.fr",
        "bridgebase": "bridgebase.com",
        "pokerstars": "pokerstars.fr",
        "winamax": "winamax.fr",
        "pmu": "pmu.fr",
        "unibet": "unibet.fr",
        "betclic": "betclic.fr",
        "parions sport": "parionssport.fdj.fr",
        "fdj": "fdj.fr",
        # Fitness & outdoor
        "strava": "strava.com",
        "zwift": "zwift.com",
        "mywhoosh": "mywhoosh.com",
        "trainerroad": "trainerroad.com",
        "intervals icu": "intervals.icu",
        "intervals": "intervals.icu",
        "trainingpeaks": "trainingpeaks.com",
        "komoot": "komoot.com",
        "alltrails": "alltrails.com",
        "visorando": "visorando.com",
        "ffrandonnee": "ffrandonnee.fr",
        "ffcam": "ffcam.fr",
        "ffme": "ffme.fr",
        "myfitnesspal": "myfitnesspal.com",
        "fatsecret": "fatsecret.fr",
        "yazio": "yazio.com",
        "strong app": "strong.app",
        "hevy": "hevy.app",
        "freeletics": "freeletics.com",
        "peloton": "onepeloton.com",
        "basic fit": "basic-fit.com",
        "basicfit": "basic-fit.com",
        "fitness park": "fitnesspark.fr",
        "keepcool": "keepcool.fr",
        "neoness": "neoness.fr",
        # Cuisine
        "marmiton": "marmiton.org",
        "750g": "750g.com",
        "cuisine az": "cuisineaz.com",
        "cuisineaz": "cuisineaz.com",
        "ptitchef": "ptitchef.com",
        "chefclub": "chefclub.tv",
        "cookpad": "cookpad.com",
        "allrecipes": "allrecipes.com",
        "serious eats": "seriouseats.com",
        "seriouseats": "seriouseats.com",
        "bon appetit": "bonappetit.com",
        "tasty": "tasty.co",
        "bbc good food": "bbcgoodfood.com",
        "guide michelin": "guide.michelin.com",
        "gault millau": "gaultmillau.com",
        "lafourchette": "lafourchette.com",
        "thefork": "thefork.fr",
        "yelp": "yelp.fr",
        "swile": "swile.co",
        "edenred": "edenred.fr",
        # Santé FR
        "sante publique france": "santepubliquefrance.fr",
        "spf": "santepubliquefrance.fr",
        "ansm": "ansm.sante.fr",
        "anses": "anses.fr",
        "medisite": "medisite.fr",
        "topsante": "topsante.com",
        "vaccination info service": "vaccination-info-service.fr",
        "qare": "qare.fr",
        "livi": "livi.fr",
        "medadom": "medadom.com",
        "petit bambou": "petitbambou.com",
        "petitbambou": "petitbambou.com",
        "headspace": "headspace.com",
        "calm": "calm.com",
        "insight timer": "insighttimer.com",
        "waking up": "wakingup.com",
        "oura": "ouraring.com",
        "whoop": "whoop.com",
        "withings": "withings.com",
        # Photo & vidéo pro
        "500px": "500px.com",
        "flickr pro": "flickr.com",
        "smugmug": "smugmug.com",
        "photoshelter": "photoshelter.com",
        "1x": "1x.com",
        "viewbug": "viewbug.com",
        "photocrowd": "photocrowd.com",
        "35mmc": "35mmc.com",
        "petapixel": "petapixel.com",
        "dpreview": "dpreview.com",
        "digital photography review": "dpreview.com",
        "cameralabs": "cameralabs.com",
        "lensrentals": "lensrentals.com",
        "borrowlenses": "borrowlenses.com",
        "mpb": "mpb.com",
        "digikey photo": "digikey.fr",
        "bh photo": "bhphotovideo.com",
        "bhphoto": "bhphotovideo.com",
        "adorama": "adorama.com",
        "manfrotto": "manfrotto.com",
        "gitzo": "gitzo.com",
        "peak design": "peakdesign.com",
        "peakdesign": "peakdesign.com",
        "moment lens": "shopmoment.com",
        "moment": "shopmoment.com",
        "gopro": "gopro.com",
        "dji store": "store.dji.com",
        "insta360": "insta360.com",
        "blackmagic design": "blackmagicdesign.com",
        "blackmagic": "blackmagicdesign.com",
        "red digital cinema": "red.com",
        "red camera": "red.com",
        "arri": "arri.com",
        "sony alpha": "alphauniverse.com",
        "canon fr": "canon.fr",
        "nikon fr": "nikon.fr",
        "fujifilm": "fujifilm-x.com",
        "fuji x": "fujifilm-x.com",
        "olympus cameras": "omsystem.com",
        "om system": "omsystem.com",
        "panasonic lumix": "panasonic.com/global/consumer/lumix.html",
        "lumix": "panasonic.com/global/consumer/lumix.html",
        "leica": "leica-camera.com",
        "hasselblad": "hasselblad.com",
        "phase one": "phaseone.com",
        "capture one": "captureone.com",
        "captureone": "captureone.com",
        "lightroom": "adobe.com/products/photoshop-lightroom.html",
        "dxo": "dxo.com",
        "topaz labs": "topazlabs.com",
        "topazlabs": "topazlabs.com",
        "luminar": "skylum.com",
        "skylum": "skylum.com",
        "on1 photo": "on1.com",
        "on1": "on1.com",
        "affinity photo": "affinity.serif.com/photo",
        "affinity": "affinity.serif.com",
        "serif": "affinity.serif.com",
        "pixlr": "pixlr.com",
        "photopea": "photopea.com",
        "remove background": "remove.bg",
        "bigjpg": "bigjpg.com",
        "waifu2x": "waifu2x.booru.pics",
        "realesrgan": "github.com/xinntao/Real-ESRGAN",
        "ffmpeg wiki": "trac.ffmpeg.org",
        "handbrake": "handbrake.fr",
        "shutter encoder": "shutterencoder.com",
        "losslesscut": "github.com/mifi/lossless-cut",
        "kdenlive": "kdenlive.org",
        "shotcut": "shotcut.org",
        "openshot": "openshot.org",
        "olive editor": "olivevideoeditor.org",
        "olive": "olivevideoeditor.org",
        "blender video": "blender.org",
        "hitfilm": "fxhome.com",
        "fxhome": "fxhome.com",
        "motion array": "motionarray.com",
        "motionarray": "motionarray.com",
        "artlist": "artlist.io",
        "epidemic sound": "epidemicsound.com",
        "epidemicsound": "epidemicsound.com",
        "audiojungle": "audiojungle.net",
        "envato audio": "elements.envato.com/audio",
        "pond5": "pond5.com",
        "storyblocks": "storyblocks.com",
        "videoblocks": "storyblocks.com",
        # Musique & audio
        "bandlab": "bandlab.com",
        "soundtrap": "soundtrap.com",
        "soundation": "soundation.com",
        "audiotool": "audiotool.com",
        "lmms": "lmms.io",
        "musescore": "musescore.com",
        "flat io": "flat.io",
        "flat": "flat.io",
        "noteflight": "noteflight.com",
        "soundbetter": "soundbetter.com",
        "fiverr music": "fiverr.com/categories/music-audio",
        "beatport": "beatport.com",
        "traxsource": "traxsource.com",
        "juno download": "junodownload.com",
        "junodownload": "junodownload.com",
        "resident advisor": "ra.co",
        "ra": "ra.co",
        "mixcloud": "mixcloud.com",
        "hearthis": "hearthis.at",
        "8tracks": "8tracks.com",
        "songkick": "songkick.com",
        "bandsintown": "bandsintown.com",
        "dice fm": "dice.fm",
        "dice": "dice.fm",
        "shotgun": "shotgun.live",
        "shotgun live": "shotgun.live",
        "fnac spectacles": "fnacspectacles.com",
        "ticketmaster": "ticketmaster.fr",
        "ticketmaster fr": "ticketmaster.fr",
        "see tickets": "seetickets.com",
        "seetickets": "seetickets.com",
        "eventbrite": "eventbrite.fr",
        "eventbrite fr": "eventbrite.fr",
        "weezevent": "weezevent.com",
        "billetweb": "billetweb.fr",
        "helloasso events": "helloasso.com",
        # Legal & juridique FR
        "legifrance journal officiel": "legifrance.gouv.fr",
        "journal officiel": "legifrance.gouv.fr",
        "jo": "legifrance.gouv.fr",
        "service public entreprise": "entreprendre.service-public.fr",
        "entreprendre service public": "entreprendre.service-public.fr",
        "bpifrance": "bpifrance.fr",
        "bpifrance creation": "bpifrance-creation.fr",
        "france active": "franceactive.org",
        "initiative france": "initiative-france.fr",
        "reseau entreprendre": "reseau-entreprendre.org",
        "chambre commerce": "cci.fr",
        "cci": "cci.fr",
        "chambre metiers": "cmaclub.fr",
        "cma": "artisanat.fr",
        "artisanat fr": "artisanat.fr",
        "greffe tribunal": "infogreffe.fr",
        "tribunal commerce": "infogreffe.fr",
        "tribunal judiciaire": "justice.fr",
        "cour appel": "courdecassation.fr",
        "avocat fr": "avocat.fr",
        "notaires fr": "notaires.fr",
        "notaire fr": "notaires.fr",
        "huissier justice": "huissier-justice.fr",
        "huissier": "huissier-justice.fr",
        "justice fr": "justice.fr",
        "ejustice": "ejustice.fr",
        "e justice": "ejustice.fr",
        "droit fin": "droit-finances.commentcamarche.net",
        "commentcamarche": "commentcamarche.net",
        "comment ca marche": "commentcamarche.net",
        "ccm": "commentcamarche.net",
        "journal du net": "journaldunet.com",
        "jdn": "journaldunet.com",
        "silicon": "silicon.fr",
        "usine digitale": "usine-digitale.fr",
        "usinedigitale": "usine-digitale.fr",
        "l usine nouvelle": "usinenouvelle.com",
        "usinenouvelle": "usinenouvelle.com",
        "industrie mag": "industrie-mag.com",
        "industrie mag": "industrie-mag.com",
        # CMS & no-code
        "wordpress org": "wordpress.org",
        "wordpress com": "wordpress.com",
        "ghost cms": "ghost.org",
        "ghost": "ghost.org",
        "contentful": "contentful.com",
        "sanity io": "sanity.io",
        "sanity": "sanity.io",
        "strapi": "strapi.io",
        "directus": "directus.io",
        "payload cms": "payloadcms.com",
        "payload": "payloadcms.com",
        "keystonejs": "keystonejs.com",
        "keystone": "keystonejs.com",
        "prismic": "prismic.io",
        "storyblok": "storyblok.com",
        "butter cms": "buttercms.com",
        "buttercms": "buttercms.com",
        "datocms": "datocms.com",
        "hygraph": "hygraph.com",
        "graphcms": "hygraph.com",
        "webiny": "webiny.com",
        "tina cms": "tina.io",
        "tina": "tina.io",
        "decap cms": "decapcms.org",
        "decap": "decapcms.org",
        "netlify cms": "decapcms.org",
        "forestry": "tina.io",
        "builder io": "builder.io",
        "builder": "builder.io",
        "plasmic": "plasmic.app",
        "bubble io": "bubble.io",
        "bubble": "bubble.io",
        "glide apps": "glideapps.com",
        "glide": "glideapps.com",
        "softr": "softr.io",
        "stacker": "stackerhq.com",
        "retool": "retool.com",
        "appsmith": "appsmith.com",
        "tooljet": "tooljet.com",
        "budibase": "budibase.com",
        "weWeb": "weweb.io",
        "weweb": "weweb.io",
        "draftbit": "draftbit.com",
        "adalo": "adalo.com",
        "thunkable": "thunkable.com",
        "appgyver": "appgyver.com",
        "flutterflow": "flutterflow.io",
        "bravo studio": "bravostudio.app",
        "bravo": "bravostudio.app",
        # Scheduling & meetings
        "calendly": "calendly.com",
        "cal com": "cal.com",
        "cal": "cal.com",
        "savvycal": "savvycal.com",
        "tidycal": "tidycal.com",
        "doodle poll": "doodle.com",
        "doodle": "doodle.com",
        "when2meet": "when2meet.com",
        "lettucemeet": "lettucemeet.com",
        "reclaim ai": "reclaim.ai",
        "reclaim": "reclaim.ai",
        "motion app": "usemotion.com",
        "usemotion": "usemotion.com",
        "sunsama": "sunsama.com",
        "akiflow": "akiflow.com",
        "sorted app": "sortedapp.com",
        "fantastical": "flexibits.com/fantastical",
        "morgen": "morgen.so",
        "vimcal": "vimcal.com",
        "cron calendar": "cron.com",
        "cron": "cron.com",
        "notion calendar": "notion.so/product/calendar",
        # PDF & documents
        "ilovepdf": "ilovepdf.com",
        "smallpdf": "smallpdf.com",
        "pdf24": "pdf24.org",
        "sejda pdf": "sejda.com",
        "sejda": "sejda.com",
        "pdfescape": "pdfescape.com",
        "pdf candy": "pdfcandy.com",
        "pdfcandy": "pdfcandy.com",
        "docuSign": "docusign.com",
        "docusign": "docusign.com",
        "yousign": "yousign.com",
        "hellosign": "dropbox.com/sign",
        "pandadoc": "pandadoc.com",
        "signnow": "signnow.com",
        "signrequest": "signrequest.com",
        "adobe sign": "adobe.com/sign",
        "pdf architect": "pdfarchitect.com",
        "foxit pdf": "foxit.com",
        "foxit": "foxit.com",
        "nitro pdf": "gonitro.com",
        "nitro": "gonitro.com",
        "pdfelement": "pdf.wondershare.com",
        "wondershare pdf": "pdf.wondershare.com",
        "ocr space": "ocr.space",
        "ocrspace": "ocr.space",
        "tesseract ocr": "github.com/tesseract-ocr/tesseract",
        "tesseract": "github.com/tesseract-ocr/tesseract",
        "abbyy": "abbyy.com",
        "nanonets": "nanonets.com",
        "docparser": "docparser.com",
        "parseur": "parseur.com",
        "rossum": "rossum.ai",
        # OCR & traduction complément
        "google lens": "lens.google.com",
        "lens google": "lens.google.com",
        "microsoft translator": "translator.microsoft.com",
        "microsoft translate": "translator.microsoft.com",
        "amazon translate": "aws.amazon.com/translate",
        "modernmt": "modernmt.com",
        "mate translate": "gikken.co/mate-translate",
        "mate": "gikken.co/mate-translate",
        "itranslate": "itranslate.com",
        "promt": "promt.com",
        "systran": "systransoft.com",
        "papago": "papago.naver.com",
        "naver translate": "papago.naver.com",
        "yandex translate": "translate.yandex.com",
        "yandex traduction": "translate.yandex.com",
        "dict cc": "dict.cc",
        "dictcc": "dict.cc",
        "leo dict": "dict.leo.org",
        "leo": "dict.leo.org",
        "pons": "pons.com",
        "babla": "babla.fr",
        "collins dictionary": "collinsdictionary.com",
        "collins": "collinsdictionary.com",
        "merriam webster": "merriam-webster.com",
        "merriam": "merriam-webster.com",
        "dictionary com": "dictionary.com",
        "dictionary.com": "dictionary.com",
        "thesaurus com": "thesaurus.com",
        "thesaurus.com": "thesaurus.com",
        "urbandictionary": "urbandictionary.com",
        "urban dictionary": "urbandictionary.com",
        "ud": "urbandictionary.com",
        # Calculatrices & convertisseurs
        "wolfram alpha pro": "wolframalpha.com",
        "symbolab": "symbolab.com",
        "mathway": "mathway.com",
        "photomath": "photomath.com",
        "geogebra calculator": "geogebra.org/calculator",
        "calculatrice": "google.com/search?q=calculator",
        "google calculator": "google.com/search?q=calculator",
        "unit converter": "unitconverters.net",
        "unitconverters": "unitconverters.net",
        "convert units": "convertunits.com",
        "xe currency": "xe.com",
        "xe": "xe.com",
        "oanda": "oanda.com",
        "currency converter google": "google.com/finance",
        "google finance": "google.com/finance",
        "timeanddate": "timeanddate.com",
        "time and date": "timeanddate.com",
        "world clock": "timeanddate.com/worldclock",
        "timezone converter": "timeanddate.com/worldclock/converter.html",
        "epoch converter": "epochconverter.com",
        "epochconverter": "epochconverter.com",
        "unix timestamp": "unixtimestamp.com",
        "crontab guru": "crontab.guru",
        "crontabguru": "crontab.guru",
        "cron expression": "crontab.guru",
        # Enfants & éducation jeunesse
        "lumni primaire": "lumni.fr/primaire",
        "lumni college": "lumni.fr/college",
        "lumni lycee": "lumni.fr/lycee",
        "maxicours": "maxicours.com",
        "schoolmouv": "schoolmouv.fr",
        "kartable": "kartable.fr",
        "les bons profs": "lesbonsprofs.com",
        "lesbonsprofs": "lesbonsprofs.com",
        "digischool": "digischool.fr",
        "digi school": "digischool.fr",
        "supbiotech": "supbiotech.fr",
        "annabac": "annabac.com",
        "bac pro": "onisep.fr",
        "mon orientation en ligne": "monorientationenligne.fr",
        "moodle": "moodle.org",
        "moodle cloud": "moodle.com",
        "canvas lms": "instructure.com/canvas",
        "canvas instructure": "instructure.com/canvas",
        "blackboard": "blackboard.com",
        "google classroom help": "support.google.com/classroom",
        "padlet": "padlet.com",
        "genially": "genial.ly",
        "genial ly": "genial.ly",
        "mentimeter": "mentimeter.com",
        "kahoot": "kahoot.com",
        "quizizz": "quizizz.com",
        "quizizz fr": "quizizz.com",
        "baamboozle": "baamboozle.com",
        "wordwall": "wordwall.net",
        "liveworksheets": "liveworksheets.com",
        "nearpod": "nearpod.com",
        "peardeck": "peardeck.com",
        "flip": "flip.com",
        "flipgrid": "flip.com",
        "edpuzzle": "edpuzzle.com",
        "screencastomatic": "screencast-o-matic.com",
        "screencast o matic": "screencast-o-matic.com",
        "screencastify edu": "screencastify.com",
        # Animaux
        "wamiz chien": "wamiz.com/chien",
        "wamiz chat": "wamiz.com/chat",
        "chien com": "chien.com",
        "chien.com": "chien.com",
        "chats du monde": "chatsdumonde.com",
        "eleveurs online": "eleveurs-online.com",
        "eleveur": "eleveurs-online.com",
        "centrale canine": "centrale-canine.fr",
        "centralecanine": "centrale-canine.fr",
        "lof": "centrale-canine.fr",
        "scc": "centrale-canine.fr",
        "spa france": "la-spa.fr",
        "la spa": "la-spa.fr",
        "spa": "la-spa.fr",
        "30 millions amis": "30millionsdamis.fr",
        "30millionsdamis": "30millionsdamis.fr",
        "refuge": "la-spa.fr",
        "adoption chien": "la-spa.fr",
        "adoption chat": "la-spa.fr",
        "vetoavenue": "vetoavenue.com",
        "vetolib": "vetolib.fr",
        "planete vet": "planetvet.fr",
        "planetvet": "planetvet.fr",
        "wikipet": "wikipet.fr",
        "wiki pet": "wikipet.fr",
        "zoo fr": "parczoo.fr",
        "zoo paris": "zoo-paris.com",
        "beauval": "zoo-parc-beauval.com",
        "zoo beauval": "zoo-parc-beauval.com",
        "zoo de la fleche": "zoo-delafleche.com",
        "zoo la fleche": "zoo-delafleche.com",
        "zoo amneville": "zoo-amneville.com",
        "zoo amnéville": "zoo-amneville.com",
        "aquarium paris": "aquariumdeparis.com",
        "oceanopolis": "oceanopolis.com",
        "oceanopolis brest": "oceanopolis.com",
        "nausicaa": "nausicaa.fr",
        "nausicaa boulogne": "nausicaa.fr",
        # Parentalité
        "magicmaman": "magicmaman.com",
        "magic maman": "magicmaman.com",
        "marmottons": "marmottons.com",
        "parents fr": "parents.fr",
        "parents": "parents.fr",
        "aufeminin maman": "aufeminin.com",
        "aufeminin": "aufeminin.com",
        "maman pour la vie": "mamanpourlavie.com",
        "mamanpourlavie": "mamanpourlavie.com",
        "pregnancy app": "whattoexpect.com",
        "what to expect": "whattoexpect.com",
        "whattoexpect": "whattoexpect.com",
        "baby center": "babycenter.com",
        "babycenter": "babycenter.com",
        "baby connect": "baby-connect.com",
        "babyconnect": "baby-connect.com",
        "huckleberry": "huckleberrycare.com",
        "huckleberry sleep": "huckleberrycare.com",
        "filao": "filao.fr",
        "filao parentalite": "filao.fr",
        "maison des parents": "maisondesparents.org",
        "maisondesparents": "maisondesparents.org",
        "caf famille": "caf.fr",
        "monenfant fr": "monenfant.fr",
        "mon enfant fr": "monenfant.fr",
        "monenfant": "monenfant.fr",
        "pajemploi": "pajemploi.urssaf.fr",
        "paj emploi": "pajemploi.urssaf.fr",
        "creche": "service-public.fr/particuliers/vosdroits/N19681",
        "assistante maternelle": "service-public.fr/particuliers/vosdroits/N133",
        # Immobilier & colocation complément
        "seloger neuf": "seloger.com/immobilier/neuf",
        "seloger location": "seloger.com/immobilier/location",
        "seloger achat": "seloger.com/immobilier/achat",
        "seloger vente": "seloger.com/immobilier/achat",
        "seloger investissement": "seloger.com/immobilier/investissement",
        "seloger estimation": "seloger.com/estimation-immobiliere",
        "meilleurs agents": "meilleursagents.com",
        "meilleursagents": "meilleursagents.com",
        "immobilier notaires": "immobilier.notaires.fr",
        "notaires immobilier": "immobilier.notaires.fr",
        "figaro immobilier": "immobilier.lefigaro.fr",
        "explorimmo": "explorimmo.com",
        "explor immo": "explorimmo.com",
        "avendrealouer": "avendrealouer.fr",
        "a vendre a louer": "avendrealouer.fr",
        "avendre alouer": "avendrealouer.fr",
        "belles demeures": "bellesdemeures.com",
        "bellesdemeures": "bellesdemeures.com",
        "lux residence": "lux-residence.com",
        "luxresidence": "lux-residence.com",
        "proprietes le figaro": "proprietes.lefigaro.fr",
        "proprietes figaro": "proprietes.lefigaro.fr",
        "colocation fr": "colocation.fr",
        "colocation": "colocation.fr",
        "lacartedescolocs": "lacartedescolocs.fr",
        "la carte des colocs": "lacartedescolocs.fr",
        "appartager": "appartager.com",
        "roomlala": "roomlala.com",
        "room lala": "roomlala.com",
        "flatshare": "flatshare.com",
        "spareroom": "spareroom.co.uk",
        "idealista": "idealista.com",
        "idealista fr": "idealista.fr",
        "immobilienscout24": "immobilienscout24.de",
        "immowelt": "immowelt.de",
        "rightmove": "rightmove.co.uk",
        "zoopla": "zoopla.co.uk",
        "redfin": "redfin.com",
        "zillow": "zillow.com",
        "realtor com": "realtor.com",
        "realtor.com": "realtor.com",
        "trulia": "trulia.com",
        "apartments com": "apartments.com",
        "apartments.com": "apartments.com",
        "streeteasy": "streeteasy.com",
        # Marine & voile
        "meteo marine": "meteo-marine.com",
        "meteo-marine": "meteo-marine.com",
        "meteomarine": "meteo-marine.com",
        "shom": "shom.fr",
        "service hydrographique": "shom.fr",
        "navionics": "navionics.com",
        "cmap": "c-map.com",
        "c map": "c-map.com",
        "opencpn": "opencpn.org",
        "open cpn": "opencpn.org",
        "predictwind": "predictwind.com",
        "windy marine": "windy.com",
        "passage weather": "passageweather.com",
        "passageweather": "passageweather.com",
        "sailgrib": "sailgrib.com",
        "ffvoile": "ffvoile.fr",
        "ff voile": "ffvoile.fr",
        "voile pratique": "voilepratique.com",
        "voilepratique": "voilepratique.com",
        "voile magazine": "voilemagazine.com",
        "voilemagazine": "voilemagazine.com",
        "yachting world": "yachtingworld.com",
        "yachtingworld": "yachtingworld.com",
        "sail magazine": "sailmagazine.com",
        "sailmagazine": "sailmagazine.com",
        "boat show": "parisboatshow.com",
        "salon nautique paris": "parisboatshow.com",
        "salon nautique": "parisboatshow.com",
        "grand pavois": "grandpavois.com",
        "grandpavois": "grandpavois.com",
        "les sables vendee": "lessablesdolonne.com",
        "vendee globe": "vendeeglobe.org",
        "vendeeglobe": "vendeeglobe.org",
        "route du rhum": "routedurhum.com",
        "routedurhum": "routedurhum.com",
        "transat jacques vabre": "transatjacquesvabre.org",
        "transat": "transatjacquesvabre.org",
        "solitaire du figaro": "lasolitaire.fr",
        "solitaire figaro": "lasolitaire.fr",
        "mini transat": "minitransat.fr",
        "minitransat": "minitransat.fr",
        "beneteau": "beneteau.com",
        "jeanneau": "jeanneau.com",
        "dufour": "dufour-yachts.com",
        "dufour yachts": "dufour-yachts.com",
        "bavaria yachts": "bavariayachts.com",
        "bavaria": "bavariayachts.com",
        "hanse": "hanse-yachts.com",
        "hanse yachts": "hanse-yachts.com",
        "lagoon catamaran": "catamarans-lagoon.com",
        "lagoon": "catamarans-lagoon.com",
        "fountaine pajot": "fountaine-pajot.com",
        "fountaine-pajot": "fountaine-pajot.com",
        "catana": "catana-group.com",
        "outremer": "outremer-yachting.com",
        "outremer yachting": "outremer-yachting.com",
        "multihull": "multihulls-world.com",
        "multihulls world": "multihulls-world.com",
        # RC & modélisme
        "modelisme com": "modelisme.com",
        "modelism": "modelisme.com",
        "model aircraft": "modelaircraft.org",
        "ama": "modelaircraft.org",
        "faa recreational": "faa.gov/uas/recreational_flyers",
        "faa drone": "faa.gov/uas",
        "faa uas": "faa.gov/uas",
        "drone zone faa": "faadronezone.faa.gov",
        "faadronezone": "faadronezone.faa.gov",
        "alphatango drone": "alphatango.aviation-civile.gouv.fr",
        "drone entreprises": "drone.entreprises.gouv.fr",
        "fpv fr": "fpv-france.com",
        "fpv france": "fpv-france.com",
        "fpv": "fpv-france.com",
        "oscarliang": "oscarliang.com",
        "oscar liang": "oscarliang.com",
        "getfpv": "getfpv.com",
        "get fpv": "getfpv.com",
        "race day quads": "racedayquads.com",
        "rdq": "racedayquads.com",
        "pyrodrone": "pyrodrone.com",
        "iflight": "iflight-rc.com",
        "iflight rc": "iflight-rc.com",
        "geprc": "geprc.com",
        "geprc fpv": "geprc.com",
        "tbs crossfire": "team-blacksheep.com",
        "team blacksheep": "team-blacksheep.com",
        "tbs": "team-blacksheep.com",
        "expresslrs": "expresslrs.org",
        "express lrs": "expresslrs.org",
        "elrs": "expresslrs.org",
        "rotorbuilds": "rotorbuilds.com",
        "rotor builds": "rotorbuilds.com",
        "fpv compare": "fpvcompare.com",
        "fpvcompare": "fpvcompare.com",
        "speedybee": "speedybee.com",
        "speedy bee": "speedybee.com",
        "radiomaster": "radiomasterrc.com",
        "radio master": "radiomasterrc.com",
        "radiomaster rc": "radiomasterrc.com",
        "jumper rc": "jumper-rc.com",
        "jumperrc": "jumper-rc.com",
        "betafpv": "betafpv.com",
        "beta fpv": "betafpv.com",
        "emax": "emaxmodel.com",
        "emax model": "emaxmodel.com",
        "happymodel": "happymodel.com",
        "happy model": "happymodel.com",
        "caddx": "caddxfpv.com",
        "caddx fpv": "caddxfpv.com",
        "runCam": "runcam.com",
        "runcam": "runcam.com",
        "foxeer": "foxeer.com",
        "foxeer fpv": "foxeer.com",
        "tattu": "genstattu.com",
        "genstattu": "genstattu.com",
        "cnhl": "cnhlshop.com",
        "cnhl shop": "cnhlshop.com",
        "rcgroups": "rcgroups.com",
        "rc groups": "rcgroups.com",
        "rc universe": "rcuniverse.com",
        "rcuniverse": "rcuniverse.com",
        "f3a": "fai.org/sport-aviation/aerobatics",
        "fai aerobatics": "fai.org/sport-aviation/aerobatics",
        "f3p": "fai.org/sport-aviation/indoor-aerobatics",
        "fai indoor": "fai.org/sport-aviation/indoor-aerobatics",
        "f3f": "fai.org/sport-aviation/gliding",
        "fai gliding": "fai.org/sport-aviation/gliding",
        "f5j": "fai.org/sport-aviation/gliding",
        "fai rc": "fai.org/sport-aviation",
        "fai": "fai.org",
        "ffam rc": "ffam.asso.fr",
        "ffam modelisme": "ffam.asso.fr",
        "ffam aeromodelisme": "ffam.asso.fr",
    })

    # ── Génération : modules Go populaires ──
    go_modules = [
        "gin", "echo", "fiber", "chi", "gorilla/mux", "net/http",
        "cobra", "viper", "logrus", "zap", "zerolog", "slog",
        "gorm", "sqlx", "ent", "migrate", "testify", "mock",
        "wire", "fx", "dig", "grpc", "protobuf", "connect",
        "redis/go-redis", "go-chi/chi", "go-playground/validator",
        "spf13/cobra", "stretchr/testify", "golang/mock",
    ]
    for mod in go_modules:
        add(f"go {mod}", f"pkg.go.dev/{mod}")
        add(f"pkg {mod}", f"pkg.go.dev/{mod}")

    # ── Génération : Dart/Flutter packages ──
    dart_packages = [
        "flutter", "provider", "riverpod", "bloc", "get", "dio",
        "http", "shared_preferences", "path_provider", "sqflite",
        "firebase_core", "firebase_auth", "cloud_firestore",
        "google_fonts", "flutter_svg", "cached_network_image",
        "go_router", "auto_route", "freezed", "json_serializable",
        "build_runner", "flutter_hooks", "hooks_riverpod",
    ]
    for pkg in dart_packages:
        add(f"dart {pkg}", f"pub.dev/packages/{pkg}")
        add(f"flutter pkg {pkg}", f"pub.dev/packages/{pkg}")

    # ── Génération : Ruby gems populaires ──
    gems = [
        "rails", "sinatra", "rack", "puma", "sidekiq", "redis",
        "pg", "mysql2", "sqlite3", "activerecord", "devise",
        "pundit", "rspec", "minitest", "capybara", "rubocop",
        "bundler", "rake", "thor", "faraday", "nokogiri",
    ]
    for gem in gems:
        add(f"gem {gem}", f"rubygems.org/gems/{gem}")
        add(f"ruby {gem}", f"rubygems.org/gems/{gem}")

    # ── Génération : Composer PHP ──
    composer = [
        "laravel/framework", "symfony/symfony", "slim/slim",
        "doctrine/orm", "monolog/monolog", "guzzlehttp/guzzle",
        "phpunit/phpunit", "fakerphp/faker", "twig/twig",
        "league/flysystem", "predis/predis", "swiftmailer/swiftmailer",
    ]
    for pkg in composer:
        short = pkg.split("/")[-1]
        add(f"composer {short}", f"packagist.org/packages/{pkg}")
        add(f"php {short}", f"packagist.org/packages/{pkg}")

    # ── Génération : Maven artifacts Java ──
    maven = [
        "spring-boot", "spring-framework", "hibernate", "junit",
        "mockito", "lombok", "jackson", "gson", "okhttp",
        "retrofit", "rxjava", "reactor", "kafka-clients",
        "elasticsearch", "log4j", "slf4j", "apache-commons",
    ]
    for art in maven:
        add(f"maven {art}", f"mvnrepository.com/search?q={art}")
        add(f"java {art}", f"mvnrepository.com/search?q={art}")

    # ── Dev, CRM, ERP, compta ──
    adds({
        "css tricks": "css-tricks.com",
        "csstricks": "css-tricks.com",
        "smashing magazine": "smashingmagazine.com",
        "smashingmagazine": "smashingmagazine.com",
        "sitepoint": "sitepoint.com",
        "daily dev": "app.daily.dev",
        "dailydev": "app.daily.dev",
        "lobsters": "lobste.rs",
        "syntax fm": "syntax.fm",
        "syntax": "syntax.fm",
        "shopify dev": "shopify.dev",
        "resend": "resend.com",
        "postmark": "postmarkapp.com",
        "loops": "loops.so",
        "klaviyo": "klaviyo.com",
        "pipedrive": "pipedrive.com",
        "folk crm": "folk.app",
        "folk": "folk.app",
        "attio": "attio.com",
        "odoo": "odoo.com",
        "erpnext": "erpnext.com",
        "dolibarr": "dolibarr.org",
        "xero": "xero.com",
        "wave accounting": "waveapps.com",
        "wave": "waveapps.com",
        "freshbooks": "freshbooks.com",
        "ynab": "ynab.com",
        "bankin": "bankin.com",
        "linxo": "linxo.com",
        "finary": "finary.com",
        "finary invest": "finary.com",
        "finary patrimoine": "finary.com",
    })

    # ── Génération : jeux Steam populaires (slug) ──
    steam_games = [
        "counter-strike 2", "dota 2", "pUBG", "apex legends", "gta v",
        "elden ring", "baldur's gate 3", "cyberpunk 2077", "witcher 3",
        "red dead redemption 2", "hogwarts legacy", "starfield",
        "the finals", "helldivers 2", "palworld", "monster hunter world",
        "dark souls 3", "sekiro", "bloodborne", "lies of p",
        "armored core 6", "fromsoftware", "resident evil 4",
        "street fighter 6", "tekken 8", "mortal kombat 1",
        "f1 24", "forza horizon 5", "assetto corsa competizione",
        "iracing", "euro truck simulator 2", "american truck simulator",
        "farming simulator 22", "cities skylines 2", "planet coaster 2",
        "rimworld", "factorio", "satisfactory", "dyson sphere program",
        "terraria", "stardew valley", "hades", "hades 2",
        "dead cells", "slay the spire", "balatro", "inscryption",
        "portal 2", "half-life 2", "team fortress 2", "left 4 dead 2",
        "valheim", "v rising", "enshrouded", "sons of the forest",
        "no man's sky", "elite dangerous", "star citizen",
        "war thunder", "world of tanks", "world of warships",
        "total war warhammer 3", "civilization 6", "civilization 7",
        "age of empires 4", "age of empires 2", "starcraft 2",
        "diablo 4", "path of exile", "path of exile 2",
        "destiny 2", "warframe", "the division 2",
        "rainbow six siege", "payday 3", "deep rock galactic",
        "lethal company", "content warning", "among us",
        "fall guys", "rocket league", "overwatch 2",
        "marvel rivals", "final fantasy xiv", "final fantasy xvi",
        "persona 5", "yakuza", "like a dragon",
        "microsoft flight simulator", "x-plane 12", "dcs world",
        "il-2 sturmovik", "warbirds", "aces high",
    ]
    for game in steam_games:
        q = quote_plus(game)
        add(game, f"store.steampowered.com/search/?term={q}")
        add(f"steam {game}", f"store.steampowered.com/search/?term={q}")

    # ── Génération : chaînes YouTube tech (domaine youtube) ──
    yt_channels = [
        "mkbhd", "linus tech tips", "ltt", "fireship", "theo t3 gg",
        "traversy media", "freecodecamp", "corey schafer", "techworld with nana",
        "networkchuck", "david bombal", "cisco", "aws", "google cloud tech",
        "microsoft developer", "vercel", "supabase", "firebase",
        "three js journey", "bruno simon", "simon dev", "dan abramov",
        "theo browne", "josh tried coding", "web dev simplified",
        "javascript mastery", "developedbyed", "design course",
        "flux academy", "charli marie", "the futur", "spoony quine",
        "quartering", "gopher academy", "justforfunc", "anthony gg",
        "nocode mba", "bubble tutorial", "france tv info",
        "bfmtv", "le monde", "le figaro", "france 24",
        "stella montis", "impero game", "impero jeu",
    ]
    for ch in yt_channels:
        q = ch.replace(" ", "+")
        add(f"youtube {ch}", f"youtube.com/results?search_query={q}")
        add(f"yt {ch}", f"youtube.com/results?search_query={q}")

    return d
