"""Catalogue massif d'alias sites — batch 5."""
from __future__ import annotations


def get_batch5() -> dict[str, str]:
    d: dict[str, str] = {}

    def add(alias: str, domain: str) -> None:
        d[alias.strip().lower()] = domain

    def adds(items: dict[str, str]) -> None:
        for k, v in items.items():
            add(k, v)

    adds({
        # Musées & culture FR
        "louvre": "louvre.fr",
        "musee du louvre": "louvre.fr",
        "orsay": "musee-orsay.fr",
        "musee orsay": "musee-orsay.fr",
        "centre pompidou": "centrepompidou.fr",
        "pompidou": "centrepompidou.fr",
        "musee rodin": "musee-rodin.fr",
        "rodin": "musee-rodin.fr",
        "musee picasso": "museepicassoparis.fr",
        "picasso paris": "museepicassoparis.fr",
        "musee d orsay": "musee-orsay.fr",
        "musee quai branly": "quai-branly.fr",
        "quai branly": "quai-branly.fr",
        "musee arts decoratifs": "madparis.fr",
        "mad paris": "madparis.fr",
        "palais tokyo": "palaisdetokyo.com",
        "palaisdetokyo": "palaisdetokyo.com",
        "fondation louis vuitton": "fondationlouisvuitton.fr",
        "flv": "fondationlouisvuitton.fr",
        "musee du quai branly": "quai-branly.fr",
        "musee carnavalet": "carnavalet.paris.fr",
        "carnavalet": "carnavalet.paris.fr",
        "musee de l armee": "musee-armee.fr",
        "invalides": "musee-armee.fr",
        "musee cluny": "musee-moyenage.fr",
        "musee moyen age": "musee-moyenage.fr",
        "conciergerie": "paris-conciergerie.fr",
        "sainte chapelle": "sainte-chapelle.fr",
        "sainte-chapelle": "sainte-chapelle.fr",
        "versailles chateau": "chateauversailles.fr",
        "chateau versailles": "chateauversailles.fr",
        "chateauversailles": "chateauversailles.fr",
        "fontainebleau chateau": "chateaudefontainebleau.fr",
        "chateau fontainebleau": "chateaudefontainebleau.fr",
        "musee d arts de nantes": "museums.nantesmetropole.fr",
        "musee d arts nantes": "museums.nantesmetropole.fr",
        "musee naval": "musee-marine.fr",
        "musee marine": "musee-marine.fr",
        "musee national marine": "musee-marine.fr",
        "cite des sciences": "citedessciences.fr",
        "citedessciences": "citedessciences.fr",
        "cite des sciences paris": "citedessciences.fr",
        "palais decouverte": "palais-decouverte.fr",
        "palais-decouverte": "palais-decouverte.fr",
        "musee air espace": "museeairespace.fr",
        "musee air et espace": "museeairespace.fr",
        "musee air espace le bourget": "museeairespace.fr",
        "musee aeronautique": "museeairespace.fr",
        "musee aeronautique le bourget": "museeairespace.fr",
        "musee des arts et metiers": "arts-et-metiers.net",
        "arts et metiers musee": "arts-et-metiers.net",
        "musee arts et metiers": "arts-et-metiers.net",
        "musee confluences": "museedesconfluences.fr",
        "confluences lyon": "museedesconfluences.fr",
        "mucem": "mucem.org",
        "musee civilisations europe": "mucem.org",
        "musee marseille": "musees.marseille.fr",
        "musee fabre": "museefabre.fr",
        "musee fabre montpellier": "museefabre.fr",
        "musee des beaux arts lyon": "mba-lyon.fr",
        "mba lyon": "mba-lyon.fr",
        "musee des beaux arts bordeaux": "musee-aquitanine.fr",
        "musee d aquitaine": "musee-aquitanine.fr",
        "musee d aquitaine bordeaux": "musee-aquitanine.fr",
        "musee des beaux arts rennes": "mbar.fr",
        "mbar": "mbar.fr",
        "musee des beaux arts rennes mbar": "mbar.fr",
        "musee des beaux arts lille": "pba-lille.fr",
        "pba lille": "pba-lille.fr",
        "musee des beaux arts rouen": "mbarouen.fr",
        "mbarouen": "mbarouen.fr",
        "musee des beaux arts dijon": "musees-bourgogne.fr",
        "musee des beaux arts strasbourg": "musees.strasbourg.eu",
        "musee alsacien": "musees.strasbourg.eu",
        "musee de l oeuvre notre dame": "musees.strasbourg.eu",
        "musee historique": "musees.strasbourg.eu",
        "musee zoologique strasbourg": "musees.strasbourg.eu",
        # Science & recherche
        "cnrs": "cnrs.fr",
        "inria": "inria.fr",
        "cea": "cea.fr",
        "cern": "home.cern",
        "cern fr": "home.cern",
        "esa space": "esa.int",
        "nasa fr": "nasa.gov",
        "cnes fr": "cnes.fr",
        "onera": "onera.fr",
        "ifremer": "ifremer.fr",
        "ird": "ird.fr",
        "inrae": "inrae.fr",
        "inserm fr": "inserm.fr",
        "pasteur": "pasteur.fr",
        "institut pasteur": "pasteur.fr",
        "curie institute": "curie.fr",
        "institut curie": "curie.fr",
        "espci": "espci.fr",
        "sorbonne universite recherche": "sorbonne-universite.fr",
        "max planck": "mpg.de",
        "mpg": "mpg.de",
        "francis crick": "crick.ac.uk",
        "crick institute": "crick.ac.uk",
        "wellcome trust": "wellcome.org",
        "wellcome": "wellcome.org",
        "nih": "nih.gov",
        "cdc": "cdc.gov",
        "who fr": "who.int",
        "oms": "who.int",
        "eurosurveillance": "eurosurveillance.org",
        "sci hub": "sci-hub.se",
        "scihub": "sci-hub.se",
        "libgen": "libgen.is",
        "library genesis": "libgen.is",
        "annas archive": "annas-archive.org",
        "annasarchive": "annas-archive.org",
        "z library": "z-lib.org",
        "zlib": "z-lib.org",
        # Vin & gastronomie
        "lavinia": "lavinia.fr",
        "nicolas": "nicolas.com",
        "millésima": "milésima.fr",
        "millesima": "milésima.fr",
        "idealwine": "idealwine.com",
        "ideal wine": "idealwine.com",
        "wine searcher": "wine-searcher.com",
        "winesearcher": "wine-searcher.com",
        "vivino": "vivino.com",
        "cellar tracker": "cellartracker.com",
        "cellartracker": "cellartracker.com",
        "guide hachette vins": "guide-hachette-des-vins.com",
        "guide hachette": "guide-hachette-des-vins.com",
        "revue du vin de france": "larvf.com",
        "larvf": "larvf.com",
        "rvf": "larvf.com",
        "bettane desseauve": "bettane-desseauve.com",
        "bettane desseauve": "bettane-desseauve.com",
        "champagne fr": "champagne.fr",
        "champagne": "champagne.fr",
        "interprofession champagne": "champagne.fr",
        "cognac fr": "cognac.fr",
        "cognac": "cognac.fr",
        "interprofession cognac": "cognac.fr",
        "armagnac": "armagnac.fr",
        "calvados": "calvados.fr",
        "rhum fr": "rhum-francais.com",
        "rhum francais": "rhum-francais.com",
        "whisky fr": "whisky.fr",
        "whisky france": "whisky.fr",
        "pernod ricard": "pernod-ricard.com",
        "pernodricard": "pernod-ricard.com",
        "remy cointreau": "remy-cointreau.com",
        "remy cointreau": "remy-cointreau.com",
        "lvmh": "lvmh.com",
        "kering": "kering.com",
        "hermes": "hermes.com",
        "hermès": "hermes.com",
        "chanel": "chanel.com",
        "dior": "dior.com",
        "loreal": "loreal.com",
        "l oreal": "loreal.com",
        "l'oreal": "loreal.com",
        "sephora pro": "sephora.fr",
        "nocibe pro": "nocibe.fr",
        "marionnaud pro": "nocibe.fr",
        # Montres & joaillerie
        "rolex": "rolex.com",
        "omega": "omegawatches.com",
        "tag heuer": "tagheuer.com",
        "tagheuer": "tagheuer.com",
        "breitling": "breitling.com",
        "iwc": "iwc.com",
        "panerai": "panerai.com",
        "cartier montres": "cartier.com",
        "cartier": "cartier.com",
        "tiffany": "tiffany.fr",
        "bulgari": "bulgari.com",
        "hublot": "hublot.com",
        "zenith": "zenith-watches.com",
        "tudor": "tudorwatch.com",
        "longines": "longines.com",
        "tissot": "tissotwatches.com",
        "swatch": "swatch.com",
        "casio watches": "casio.com/watches",
        "gshock": "gshock.com",
        "g shock": "gshock.com",
        "seiko": "seikowatches.com",
        "citizen watch": "citizenwatch.com",
        "citizen": "citizenwatch.com",
        "orient watch": "orientwatch.com",
        "orient": "orientwatch.com",
        "nomos": "nomos-glashuette.com",
        "sinn": "sinn.de",
        "stowa": "stowa.de",
        "chrono24": "chrono24.fr",
        "chrono 24": "chrono24.fr",
        "watchfinder": "watchfinder.co.uk",
        "hodinkee": "hodinkee.com",
        "fratello watches": "fratellowatches.com",
        "fratello": "fratellowatches.com",
        "worn and wound": "wornandwound.com",
        "wornandwound": "wornandwound.com",
        # Jardinage & nature
        "truffaut jardin": "truffaut.com",
        "jardiland jardin": "jardiland.com",
        "gamm vert jardin": "gammvert.fr",
        "botanic jardin": "botanic.com",
        "promesse de fleurs": "promessedefleurs.com",
        "promessedefleurs": "promessedefleurs.com",
        "bakker": "bakker.com/fr",
        "jardins de brocéliande": "brocéliande.fr",
        "inrae jardin": "inrae.fr",
        "tela botanica": "tela-botanica.org",
        "telabotanica": "tela-botanica.org",
        "inaturalist": "inaturalist.org",
        "inaturalist fr": "inaturalist.org",
        "inaturalist france": "inaturalist.org",
        "observation.org": "observation.org",
        "ornithomedia": "ornithomedia.com",
        "ornitho": "ornithomedia.com",
        "ligue protection oiseaux": "lpo.fr",
        "lpo": "lpo.fr",
        "ffep": "ffep.org",
        "federation francaise etudes protection": "ffep.org",
        # Monitoring & observabilité
        "grafana cloud": "grafana.com/products/cloud",
        "grafana labs": "grafana.com",
        "new relic": "newrelic.com",
        "newrelic": "newrelic.com",
        "dynatrace": "dynatrace.com",
        "appdynamics": "appdynamics.com",
        "elastic cloud": "cloud.elastic.co",
        "elastic observability": "elastic.co/observability",
        "splunk": "splunk.com",
        "sumo logic": "sumologic.com",
        "sumologic": "sumologic.com",
        "honeycomb io": "honeycomb.io",
        "honeycomb": "honeycomb.io",
        "lightstep": "lightstep.com",
        "service now": "servicenow.com",
        "servicenow": "servicenow.com",
        "pagerduty": "pagerduty.com",
        "opsgenie": "atlassian.com/software/opsgenie",
        "statuspage": "statuspage.io",
        "status page": "statuspage.io",
        "uptime robot": "uptimerobot.com",
        "uptimerobot": "uptimerobot.com",
        "pingdom": "pingdom.com",
        "better uptime": "betteruptime.com",
        "betteruptime": "betteruptime.com",
        "healthchecks io": "healthchecks.io",
        "healthchecks": "healthchecks.io",
        "cronitor": "cronitor.io",
        "checkly": "checklyhq.com",
        "incident io": "incident.io",
        "incidentio": "incident.io",
        "rootly": "rootly.com",
        "firehydrant": "firehydrant.io",
        "blameless": "blameless.com",
        "cortex io": "cortex.io",
        "cortex": "cortex.io",
        "port io": "getport.io",
        "getport": "getport.io",
        "backstage io": "backstage.io",
        "backstage": "backstage.io",
        "opslevel": "opslevel.com",
        "ops level": "opslevel.com",
        "humanitec": "humanitec.com",
        "qovery": "qovery.com",
        "northflank": "northflank.com",
        "coolify": "coolify.io",
        "caprover": "caprover.com",
        "kamal deploy": "kamal-deploy.org",
        "kamal": "kamal-deploy.org",
        "dokku": "dokku.com",
        "heroku": "heroku.com",
        "heroku dashboard": "dashboard.heroku.com",
        "platform.sh": "platform.sh",
        "platformsh": "platform.sh",
        "clever cloud": "clever-cloud.com",
        "clevercloud": "clever-cloud.com",
        "scalingo": "scalingo.com",
        "alwaysdata": "alwaysdata.com",
        "o2switch": "o2switch.fr",
        "o2 switch": "o2switch.fr",
        "infomaniak hosting": "infomaniak.com",
        "infomaniak": "infomaniak.com",
        "gandi hosting": "gandi.net",
        "planethoster": "planethoster.com",
        "planet hoster": "planethoster.com",
        "ex2": "ex2.com",
        "ex2 hosting": "ex2.com",
        "lws": "lws.fr",
        "lws hosting": "lws.fr",
        "amen": "amen.fr",
        "amen fr": "amen.fr",
        "online.net hosting": "online.net",
        "kimsufi": "kimsufi.com",
        "soyoustart": "soyoustart.com",
        "so you start": "soyoustart.com",
    })

    # Aéroports (IATA)
    airports = {
        "cdg": "parisaeroport.fr",
        "paris cdg": "parisaeroport.fr",
        "roissy": "parisaeroport.fr",
        "ory": "parisaeroport.fr",
        "orly": "parisaeroport.fr",
        "paris orly": "parisaeroport.fr",
        "lfrs": "nantes.aeroport.fr",
        "nantes atlantique": "nantes.aeroport.fr",
        "aeroport nantes": "nantes.aeroport.fr",
        "lfrn": "nantes.aeroport.fr",
        "lfll": "lyonaeroports.com",
        "lyon saint exupery": "lyonaeroports.com",
        "lyon aeroport": "lyonaeroports.com",
        "lfml": "marseille.aeroport.fr",
        "marseille provence": "marseille.aeroport.fr",
        "lfbo": "toulouse.aeroport.fr",
        "toulouse blagnac": "toulouse.aeroport.fr",
        "lfbd": "bordeaux.aeroport.fr",
        "bordeaux merignac": "bordeaux.aeroport.fr",
        "lfsb": "basel-airport.com",
        "basel mulhouse": "basel-airport.com",
        "euroairport": "basel-airport.com",
        "lfpg": "parisaeroport.fr",
        "lfpo": "parisaeroport.fr",
        "lfmt": "montpellier.aeroport.fr",
        "montpellier mediterranee": "montpellier.aeroport.fr",
        "lfqq": "lille.aeroport.fr",
        "lille lesquin": "lille.aeroport.fr",
        "lfbf": "toulouse.aeroport.fr",
        "lfst": "strasbourg.aeroport.fr",
        "strasbourg entzheim": "strasbourg.aeroport.fr",
        "lfbf nantes": "nantes.aeroport.fr",
        "egll": "heathrow.com",
        "heathrow": "heathrow.com",
        "lgw": "gatwickairport.com",
        "gatwick": "gatwickairport.com",
        "lhr": "heathrow.com",
        "stn": "stanstedairport.com",
        "stansted": "stanstedairport.com",
        "luton": "london-luton.co.uk",
        "ltn": "london-luton.co.uk",
        "jfk": "jfkairport.com",
        "lax": "flylax.com",
        "sfo": "flysfo.com",
        "ord": "flychicago.com",
        "ohare": "flychicago.com",
        "o hare": "flychicago.com",
        "ewr": "newarkairport.com",
        "newark": "newarkairport.com",
        "mia": "miami-airport.com",
        "miami airport": "miami-airport.com",
        "atl": "atlanta-airport.com",
        "atlanta airport": "atlanta-airport.com",
        "dfw": "dfwairport.com",
        "dallas fort worth": "dfwairport.com",
        "den": "flydenver.com",
        "denver airport": "flydenver.com",
        "sea": "portseattle.org/sea-tac",
        "seattle tacoma": "portseattle.org/sea-tac",
        "sea tac": "portseattle.org/sea-tac",
        "ams": "schiphol.nl",
        "schiphol": "schiphol.nl",
        "amsterdam airport": "schiphol.nl",
        "fra": "frankfurt-airport.com",
        "frankfurt airport": "frankfurt-airport.com",
        "muc": "munich-airport.com",
        "munich airport": "munich-airport.com",
        "ber": "berlin-airport.de",
        "berlin brandenburg": "berlin-airport.de",
        "zrh": "zurich-airport.com",
        "zurich airport": "zurich-airport.com",
        "gva": "gva.ch",
        "geneve aeroport": "gva.ch",
        "genève aéroport": "gva.ch",
        "geneva airport": "gva.ch",
        "bcn": "aena.es",
        "barcelona el prat": "aena.es",
        "mad": "aena.es",
        "madrid barajas": "aena.es",
        "lis": "ana.pt",
        "lisbonne aeroport": "ana.pt",
        "lisbon airport": "ana.pt",
        "fco": "adr.it",
        "rome fiumicino": "adr.it",
        "mxp": "milanomalpensa-airport.com",
        "malpensa": "milanomalpensa-airport.com",
        "nrt": "narita-airport.jp",
        "narita": "narita-airport.jp",
        "hnd": "tokyo-haneda.com",
        "haneda": "tokyo-haneda.com",
        "sin": "changiairport.com",
        "changi": "changiairport.com",
        "hkg": "hongkongairport.com",
        "hong kong airport": "hongkongairport.com",
        "dxb": "dubaiairports.ae",
        "dubai airport": "dubaiairports.ae",
        "doh": "dohahamadairport.com",
        "doha airport": "dohahamadairport.com",
        "ist": "istairport.com",
        "istanbul airport": "istairport.com",
        "saw": "sabihaairport.com",
        "sabiha gokcen": "sabihaairport.com",
        "syd": "sydneyairport.com",
        "sydney airport": "sydneyairport.com",
        "mel": "melbourneairport.com.au",
        "melbourne airport": "melbourneairport.com.au",
        "yul": "admtl.com",
        "montreal trudeau": "admtl.com",
        "yyz": "torontopearson.com",
        "toronto pearson": "torontopearson.com",
        "gru": "gru.com.br",
        "sao paulo guarulhos": "gru.com.br",
        "gig": "riogaleao.com",
        "rio galeao": "riogaleao.com",
    }
    adds(airports)

    # Gares & trains européens
    stations = {
        "gare du nord": "sncf-connect.com",
        "gare de lyon": "sncf-connect.com",
        "gare montparnasse": "sncf-connect.com",
        "gare saint lazare": "sncf-connect.com",
        "gare de l est": "sncf-connect.com",
        "gare de l'est": "sncf-connect.com",
        "gare d austerlitz": "sncf-connect.com",
        "gare d'austerlitz": "sncf-connect.com",
        "gare nantes": "sncf-connect.com",
        "gare de nantes": "sncf-connect.com",
        "gare rennes": "sncf-connect.com",
        "gare de rennes": "sncf-connect.com",
        "gare lyon part dieu": "sncf-connect.com",
        "part dieu": "sncf-connect.com",
        "gare marseille saint charles": "sncf-connect.com",
        "saint charles": "sncf-connect.com",
        "gare lille flandres": "sncf-connect.com",
        "gare lille europe": "sncf-connect.com",
        "gare strasbourg": "sncf-connect.com",
        "gare bordeaux saint jean": "sncf-connect.com",
        "gare toulouse matabiau": "sncf-connect.com",
        "eurostar fr": "eurostar.com",
        "thalys fr": "thalys.com",
        "ice deutsche bahn": "bahn.com",
        "deutsche bahn": "bahn.com",
        "db bahn": "bahn.com",
        "obb": "oebb.at",
        "oebb": "oebb.at",
        "sbb cercle": "sbb.ch",
        "sbb": "sbb.ch",
        "cff": "sbb.ch",
        "renfe": "renfe.com",
        "trenitalia": "trenitalia.com",
        "italo": "italotreno.it",
        "italo treno": "italotreno.it",
        "ns international": "nsinternational.com",
        "ns": "ns.nl",
        "eurostar uk": "eurostar.com",
        "national rail uk": "nationalrail.co.uk",
        "nationalrail": "nationalrail.co.uk",
        "trainline uk": "thetrainline.com",
        "omio": "omio.com",
        "goeuro": "omio.com",
        "distribusion": "distribusion.com",
        "flix train": "flixtrain.com",
        "flixtrain": "flixtrain.com",
        "nightjet": "nightjet.com",
        "night jet": "nightjet.com",
    }
    adds(stations)

    # Forums & communautés FR
    adds({
        "hardware fr": "forum.hardware.fr",
        "forum hardware": "forum.hardware.fr",
        "hardwarefr": "forum.hardware.fr",
        "canard pc": "canardpc.com",
        "canardpc": "canardpc.com",
        "cowcotland": "cowcotland.com",
        "forum cowcotland": "forum.cowcotland.com",
        "next inpact": "nextinpact.com",
        "nextinpact": "nextinpact.com",
        "minimachines": "minimachines.net",
        "mini machines": "minimachines.net",
        "korben": "korben.info",
        "korben info": "korben.info",
        "sebsauvage": "sebsauvage.net",
        "seb sauvage": "sebsauvage.net",
        "reflets info": "reflets.info",
        "reflets": "reflets.info",
        "nextcloud fr": "nextcloud.com",
        "nextcloud": "nextcloud.com",
        "owncloud": "owncloud.com",
        "seafile": "seafile.com",
        "syncthing": "syncthing.net",
        "resilio sync": "resilio.com",
        "resilio": "resilio.com",
        "bit torrent": "bittorrent.com",
        "bittorrent": "bittorrent.com",
        "qbittorrent": "qbittorrent.org",
        "qbit torrent": "qbittorrent.org",
        "transmission bt": "transmissionbt.com",
        "transmission": "transmissionbt.com",
        "deluge torrent": "deluge-torrent.org",
        "deluge": "deluge-torrent.org",
        "proton drive": "proton.me/drive",
        "protondrive": "proton.me/drive",
        "icedrive": "icedrive.net",
        "icedrive net": "icedrive.net",
        "filen": "filen.io",
        "filen io": "filen.io",
        "tresorit": "tresorit.com",
        "spideroak": "spideroak.com",
        "spider oak": "spideroak.com",
        "forum libre office": "forum.libreoffice.org",
        "forum libreoffice": "forum.libreoffice.org",
        "forum mozilla": "discourse.mozilla.org",
        "forum debian": "forums.debian.net",
        "forum ubuntu": "ubuntu-fr.org",
        "ubuntu fr": "ubuntu-fr.org",
        "ubuntu-fr": "ubuntu-fr.org",
        "forum archlinux": "bbs.archlinux.org",
        "forum fedora": "discussion.fedoraproject.org",
        "forum opensuse": "forums.opensuse.org",
        "forum raspberry pi": "forums.raspberrypi.com",
        "forum arduino": "forum.arduino.cc",
        "forum home assistant": "community.home-assistant.io",
        "forum homeassistant": "community.home-assistant.io",
        "forum domotique": "forumdomotique.fr",
        "forum domotique fr": "forumdomotique.fr",
        "forum flight simulator": "forums.flightsimulator.com",
        "forum msfs": "forums.flightsimulator.com",
        "forum x plane": "forums.x-plane.org",
        "forum xplane": "forums.x-plane.org",
        "forum vatsim": "forum.vatsim.net",
        "forum ivao": "forum.ivao.aero",
        "forum pilote": "forum-pilote.com",
        "forum pilote fr": "forum-pilote.com",
    })

    # npm packages batch 2
    npm2 = [
        "socket.io", "ws", "ioredis", "bullmq", "amqplib", "kafkajs",
        "nodemailer", "handlebars", "ejs", "pug", "mustache", "nunjucks",
        "sharp", "jimp", "canvas", "pdfkit", "puppeteer-core", "cheerio",
        "jsdom", "supertest", "nock", "msw", "faker", "@faker-js/faker",
        "bcrypt", "argon2", "jsonwebtoken", "passport", "express-session",
        "helmet", "cors", "compression", "morgan", "winston", "pino",
        "dotenv", "config", "convict", "joi", "class-transformer",
        "rxjs", "effect", "fp-ts", "io-ts", "neverthrow", "ts-pattern",
        "swr", "jotai", "valtio", "xstate", "@xstate/react",
        "react-router", "react-router-dom", "@tanstack/router",
        "next-auth", "@auth/core", "lucia", "clerk", "@clerk/nextjs",
        "stripe", "@stripe/stripe-js", "paypal-rest-sdk",
        "algoliasearch", "meilisearch", "typesense", "elasticsearch",
        "@elastic/elasticsearch", "mongoose", "prisma", "@prisma/client",
        "drizzle-orm", "kysely", "slonik", "pg", "mysql2", "better-sqlite3",
        "redis", "ioredis", "bull", "agenda", "node-cron", "cron",
        "sharp", "multer", "formidable", "busboy", "archiver", "unzipper",
    ]
    for pkg in npm2:
        add(f"npm {pkg}", f"npmjs.com/package/{pkg}")
        add(f"{pkg} npm", f"npmjs.com/package/{pkg}")

    # PyPI batch 2
    pypi2 = [
        "django-rest-framework", "djangorestframework", "django-ninja",
        "django-allauth", "django-crispy-forms", "wagtail", "mezzanine",
        "flask-restful", "flask-sqlalchemy", "flask-login", "flask-wtf",
        "flask-migrate", "flask-jwt-extended", "flask-cors", "flask-socketio",
        "starlette-admin", "sqlmodel", "tortoise-orm", "piccolo",
        "motor", "pymongo", "mongoengine", "beanie", "odmantic",
        "boto3", "botocore", "google-cloud-storage", "azure-storage-blob",
        "paramiko", "fabric", "invoke", "ansible-core", "pulumi",
        "prefect", "dagster", "apache-airflow", "luigi", "kedro",
        "optuna", "hyperopt", "ray", "dask", "vaex", "modin",
        "xgboost", "lightgbm", "catboost", "shap", "lime", "eli5",
        "spacy", "nltk", "gensim", "fasttext", "sentencepiece",
        "whisper", "faster-whisper", "openai-whisper", "TTS", "coqui-tts",
        "opencv-python-headless", "ultralytics", "yolov5", "yolov8",
        "detectron2", "mmdetection", "segment-anything", "sam2",
        "onnxruntime", "onnxruntime-gpu", "tensorboard", "torchvision",
        "torchaudio", "torchtext", "lightning", "pytorch-lightning",
        "huggingface-hub", "safetensors", "tokenizers", "sentence-transformers",
        "chromadb", "lancedb", "weaviate-client", "qdrant-client", "pinecone-client",
        "langchain-community", "langchain-openai", "langchain-anthropic",
        "instructor", "marvin", "guidance", "outlines", "lm-format-enforcer",
    ]
    for pkg in pypi2:
        add(f"pypi {pkg}", f"pypi.org/project/{pkg}")
        add(f"{pkg} pypi", f"pypi.org/project/{pkg}")

    # Départements FR -> préfecture
    depts = {
        "01": "ain.gouv.fr", "02": "aisne.gouv.fr", "03": "allier.gouv.fr",
        "04": "alpes-de-haute-provence.gouv.fr", "05": "hautes-alpes.gouv.fr",
        "06": "alpes-maritimes.gouv.fr", "07": "ardeche.gouv.fr",
        "08": "ardennes.gouv.fr", "09": "ariege.gouv.fr", "10": "aube.gouv.fr",
        "11": "aude.gouv.fr", "12": "aveyron.gouv.fr", "13": "bouches-du-rhone.gouv.fr",
        "14": "calvados.gouv.fr", "15": "cantal.gouv.fr", "16": "charente.gouv.fr",
        "17": "charente-maritime.gouv.fr", "18": "cher.gouv.fr", "19": "correze.gouv.fr",
        "21": "cote-dor.gouv.fr", "22": "cotes-darmor.gouv.fr", "23": "creuse.gouv.fr",
        "24": "dordogne.gouv.fr", "25": "doubs.gouv.fr", "26": "drome.gouv.fr",
        "27": "eure.gouv.fr", "28": "eure-et-loir.gouv.fr", "29": "finistere.gouv.fr",
        "2a": "corse-du-sud.gouv.fr", "2b": "haute-corse.gouv.fr",
        "30": "gard.gouv.fr", "31": "haute-garonne.gouv.fr", "32": "gers.gouv.fr",
        "33": "gironde.gouv.fr", "34": "herault.gouv.fr", "35": "ille-et-vilaine.gouv.fr",
        "36": "indre.gouv.fr", "37": "indre-et-loire.gouv.fr", "38": "isere.gouv.fr",
        "39": "jura.gouv.fr", "40": "landes.gouv.fr", "41": "loir-et-cher.gouv.fr",
        "42": "loire.gouv.fr", "43": "haute-loire.gouv.fr", "44": "loire-atlantique.gouv.fr",
        "45": "loiret.gouv.fr", "46": "lot.gouv.fr", "47": "lot-et-garonne.gouv.fr",
        "48": "lozere.gouv.fr", "49": "maine-et-loire.gouv.fr", "50": "manche.gouv.fr",
        "51": "marne.gouv.fr", "52": "haute-marne.gouv.fr", "53": "mayenne.gouv.fr",
        "54": "meurthe-et-moselle.gouv.fr", "55": "meuse.gouv.fr", "56": "morbihan.gouv.fr",
        "57": "moselle.gouv.fr", "58": "nievre.gouv.fr", "59": "nord.gouv.fr",
        "60": "oise.gouv.fr", "61": "orne.gouv.fr", "62": "pas-de-calais.gouv.fr",
        "63": "puy-de-dome.gouv.fr", "64": "pyrenees-atlantiques.gouv.fr",
        "65": "hautes-pyrenees.gouv.fr", "66": "pyrenees-orientales.gouv.fr",
        "67": "bas-rhin.gouv.fr", "68": "haut-rhin.gouv.fr", "69": "rhone.gouv.fr",
        "70": "haute-saone.gouv.fr", "71": "saone-et-loire.gouv.fr", "72": "sarthe.gouv.fr",
        "73": "savoie.gouv.fr", "74": "haute-savoie.gouv.fr", "75": "paris.fr",
        "76": "seine-maritime.gouv.fr", "77": "seine-et-marne.gouv.fr",
        "78": "yvelines.gouv.fr", "79": "deux-sevres.gouv.fr", "80": "somme.gouv.fr",
        "81": "tarn.gouv.fr", "82": "tarn-et-garonne.gouv.fr", "83": "var.gouv.fr",
        "84": "vaucluse.gouv.fr", "85": "vendee.gouv.fr", "86": "vienne.gouv.fr",
        "87": "haute-vienne.gouv.fr", "88": "vosges.gouv.fr", "89": "yonne.gouv.fr",
        "90": "territoire-de-belfort.gouv.fr", "91": "essonne.gouv.fr",
        "92": "hauts-de-seine.gouv.fr", "93": "seine-saint-denis.gouv.fr",
        "94": "val-de-marne.gouv.fr", "95": "val-doise.gouv.fr",
        "971": "guadeloupe.gouv.fr", "972": "martinique.gouv.fr",
        "973": "guyane.gouv.fr", "974": "la-reunion.gouv.fr", "976": "mayotte.gouv.fr",
    }
    dept_names = {
        "ain": "01", "aisne": "02", "allier": "03", "alpes de haute provence": "04",
        "hautes alpes": "05", "alpes maritimes": "06", "ardeche": "07", "ardennes": "08",
        "ariege": "09", "aube": "10", "aude": "11", "aveyron": "12",
        "bouches du rhone": "13", "calvados": "14", "cantal": "15", "charente": "16",
        "charente maritime": "17", "cher": "18", "correze": "19", "cote d or": "21",
        "cotes d armor": "22", "creuse": "23", "dordogne": "24", "doubs": "25",
        "drome": "26", "eure": "27", "eure et loir": "28", "finistere": "29",
        "corse du sud": "2a", "haute corse": "2b", "gard": "30", "haute garonne": "31",
        "gers": "32", "gironde": "33", "herault": "34", "ille et vilaine": "35",
        "indre": "36", "indre et loire": "37", "isere": "38", "jura": "39",
        "landes": "40", "loir et cher": "41", "loire": "42", "haute loire": "43",
        "loire atlantique": "44", "loiret": "45", "lot": "46", "lot et garonne": "47",
        "lozere": "48", "maine et loire": "49", "manche": "50", "marne": "51",
        "haute marne": "52", "mayenne": "53", "meurthe et moselle": "54", "meuse": "55",
        "morbihan": "56", "moselle": "57", "nievre": "58", "nord": "59",
        "oise": "60", "orne": "61", "pas de calais": "62", "puy de dome": "63",
        "pyrenees atlantiques": "64", "hautes pyrenees": "65", "pyrenees orientales": "66",
        "bas rhin": "67", "haut rhin": "68", "rhone": "69", "haute saone": "70",
        "saone et loire": "71", "sarthe": "72", "savoie": "73", "haute savoie": "74",
        "paris dept": "75", "seine maritime": "76", "seine et marne": "77",
        "yvelines": "78", "deux sevres": "79", "somme": "80", "tarn": "81",
        "tarn et garonne": "82", "var": "83", "vaucluse": "84", "vendee": "85",
        "vienne": "86", "haute vienne": "87", "vosges": "88", "yonne": "89",
        "territoire de belfort": "90", "essonne": "91", "hauts de seine": "92",
        "seine saint denis": "93", "val de marne": "94", "val d oise": "95",
        "guadeloupe": "971", "martinique": "972", "guyane": "973",
        "la reunion": "974", "mayotte": "976",
    }
    for num, domain in depts.items():
        add(f"prefecture {num}", domain)
        add(f"departement {num}", domain)
        add(f"département {num}", domain)
    for name, num in dept_names.items():
        domain = depts[num]
        add(f"prefecture {name}", domain)
        add(f"departement {name}", domain)
        add(f"département {name}", domain)

    return d
