"""Génère le bloc _ALIASES_EXTRA pour browser.py (usage one-shot)."""
from __future__ import annotations

EXTRA: dict[str, str] = {
    # News FR/EU
    "20minutes": "20minutes.fr",
    "ouest france": "ouest-france.fr",
    "ouest-france": "ouest-france.fr",
    "charente libre": "charentelibre.fr",
    "sud ouest": "sudouest.fr",
    "la tribune": "latribune.fr",
    "challenges": "challenges.fr",
    "capital": "capital.fr",
    "lexpress": "lexpress.fr",
    "l express": "lexpress.fr",
    "point": "lepoint.fr",
    "le point": "lepoint.fr",
    "marianne": "marianne.net",
    "valeurs actuelles": "valeursactuelles.com",
    "mediapart": "mediapart.fr",
    "streetpress": "streetpress.com",
    "blast": "blast-info.fr",
    "france 24": "france24.com",
    "france24": "france24.com",
    "rfi": "rfi.fr",
    "tv5monde": "tv5monde.com",
    "euronews": "euronews.com",
    "politico": "politico.com",
    "axios": "axios.com",
    "ap news": "apnews.com",
    "apnews": "apnews.com",
    "npr": "npr.org",
    "pbs": "pbs.org",
    "guardian": "theguardian.com",
    "the guardian": "theguardian.com",
    "independent": "independent.co.uk",
    "daily mail": "dailymail.co.uk",
    "telegraph": "telegraph.co.uk",
    "economist": "economist.com",
    "forbes": "forbes.com",
    "wired": "wired.com",
    "arstechnica": "arstechnica.com",
    "engadget": "engadget.com",
    "gizmodo": "gizmodo.com",
    "mashable": "mashable.com",
    "zdnet": "zdnet.com",
    "cnet": "cnet.com",
    "tomshardware": "tomshardware.com",
    "anandtech": "anandtech.com",
    "pcmag": "pcmag.com",
    "techradar": "techradar.com",
    "01net": "01net.com",
    "numerama": "numerama.com",
    "journal du geek": "journaldugeek.com",
    "jdg": "journaldugeek.com",
    "clubic": "clubic.com",
    "tomsguide": "tomsguide.fr",
    "phonandroid": "phonandroid.com",
    "frandroid": "frandroid.com",
    "macg": "macg.co",
    "igen": "igen.fr",
    "iphon": "iphon.fr",
    "watchgeneration": "watchgeneration.fr",
    # Streaming extra
    "crunchyroll": "crunchyroll.com",
    "wakanim": "wakanim.tv",
    "adn": "animationdigitalnetwork.fr",
    "prime video": "primevideo.com",
    "apple tv": "tv.apple.com",
    "appletv": "tv.apple.com",
    "hbo": "max.com",
    "hbo max": "max.com",
    "max": "max.com",
    "paramount": "paramountplus.com",
    "paramount plus": "paramountplus.com",
    "peacock": "peacocktv.com",
    "hulu": "hulu.com",
    "pluto tv": "pluto.tv",
    "pluto": "pluto.tv",
    "tubi": "tubi.tv",
    "plex": "plex.tv",
    "emby": "emby.media",
    "jellyfin": "jellyfin.org",
    "stremio": "stremio.com",
    "justwatch": "justwatch.com",
    "allocine": "allocine.fr",
    "senscritique": "senscritique.com",
    "imdb": "imdb.com",
    "rotten tomatoes": "rottentomatoes.com",
    "rt": "rottentomatoes.com",
    "letterboxd": "letterboxd.com",
    "myanimelist": "myanimelist.net",
    "mal": "myanimelist.net",
    "anilist": "anilist.co",
    # E-commerce extra
    "zalando": "zalando.fr",
    "asos": "asos.com",
    "shein": "shein.com",
    "temu": "temu.com",
    "wish": "wish.com",
    "rakuten": "fr.shopping.rakuten.com",
    "rueducommerce": "rueducommerce.fr",
    "boulanger": "boulanger.com",
    "but": "but.fr",
    "conforama": "conforama.fr",
    "ikea": "ikea.com",
    "leroy merlin": "leroymerlin.fr",
    "leroymerlin": "leroymerlin.fr",
    "castorama": "castorama.fr",
    "brico depot": "bricodepot.fr",
    "bricodepot": "bricodepot.fr",
    "manomano": "manomano.fr",
    "backmarket": "backmarket.fr",
    "refurbed": "refurbed.fr",
    "swappie": "swappie.com",
    "apple store": "apple.com",
    "samsung": "samsung.com",
    "microsoft store": "microsoft.com",
    "mi store": "mi.com",
    "xiaomi": "mi.com",
    "decathlon": "decathlon.fr",
    "go sport": "go-sport.com",
    "gosport": "go-sport.com",
    "intersport": "intersport.fr",
    "foot locker": "footlocker.fr",
    "nike": "nike.com",
    "adidas": "adidas.fr",
    "puma": "puma.com",
    "uniqlo": "uniqlo.com",
    "zara": "zara.com",
    "h&m": "hm.com",
    "hm": "hm.com",
    "mango": "mango.com",
    "pull bear": "pullandbear.com",
    "sephora": "sephora.fr",
    "marionnaud": "marionnaud.fr",
    "nocibe": "nocibe.fr",
    # Food delivery
    "uber eats": "ubereats.com",
    "ubereats": "ubereats.com",
    "deliveroo": "deliveroo.fr",
    "just eat": "just-eat.fr",
    "justeat": "just-eat.fr",
    "frichti": "frichti.co",
    "quitoque": "quitoque.fr",
    "hellofresh": "hellofresh.fr",
    "foodchéri": "foodcheri.com",
    # Banks FR
    "bnp": "mabanque.bnpparibas",
    "bnpparibas": "mabanque.bnpparibas",
    "societe generale": "particuliers.sg.fr",
    "sg": "particuliers.sg.fr",
    "credit agricole": "credit-agricole.fr",
    "ca": "credit-agricole.fr",
    "credit mutuel": "creditmutuel.fr",
    "lcl": "lcl.fr",
    "banque postale": "labanquepostale.fr",
    "hello bank": "hellobank.fr",
    "boursorama banque": "boursorama-banque.com",
    "n26": "n26.com",
    "bunq": "bunq.com",
    "lydia": "lydia-app.com",
    # Dev tools extra 2
    "cloudflare": "cloudflare.com",
    "cloudflare dash": "dash.cloudflare.com",
    "fastly": "fastly.com",
    "akamai": "akamai.com",
    "bunnycdn": "bunny.net",
    "imgur": "imgur.com",
    "imgbb": "imgbb.com",
    "cloudinary": "cloudinary.com",
    "uploadthing": "uploadthing.com",
    "wetransfer": "wetransfer.com",
    "mega": "mega.nz",
    "dropbox": "dropbox.com",
    "box": "box.com",
    "pcloud": "pcloud.com",
    "todoist": "todoist.com",
    "ticktick": "ticktick.com",
    "toggl": "toggl.com",
    "clockify": "clockify.me",
    "1password": "1password.com",
    "bitwarden": "bitwarden.com",
    "dashlane": "dashlane.com",
    "lastpass": "lastpass.com",
    "protonmail": "proton.me",
    "proton vpn": "protonvpn.com",
    "protonvpn": "protonvpn.com",
    "mullvad": "mullvad.net",
    "nordvpn": "nordvpn.com",
    "expressvpn": "expressvpn.com",
    "tailscale": "tailscale.com",
    "ngrok": "ngrok.com",
    # Frameworks extra
    "solidjs": "solidjs.com",
    "qwik": "qwik.builder",
    "preact": "preactjs.com",
    "lit": "lit.dev",
    "alpinejs": "alpinejs.dev",
    "htmx": "htmx.org",
    "jquery": "jquery.com",
    "lodash": "lodash.com",
    "dayjs": "day.js.org",
    "date-fns": "date-fns.org",
    "zod": "zod.dev",
    "react hook form": "react-hook-form.com",
    "formik": "formik.org",
    "tanstack": "tanstack.com",
    "react query": "tanstack.com/query",
    "redux": "redux.js.org",
    "zustand": "zustand.docs.pmnd.rs",
    "jotai": "jotai.org",
    "recoil": "recoiljs.org",
    "mobx": "mobx.js.org",
    "pinia": "pinia.vuejs.org",
    "rxjs": "rxjs.dev",
    # Python libs
    "requests docs": "requests.readthedocs.io",
    "httpx": "python-httpx.org",
    "aiohttp": "docs.aiohttp.org",
    "websockets": "websockets.readthedocs.io",
    "beautifulsoup": "beautiful-soup-4.readthedocs.io",
    "scrapy": "scrapy.org",
    "pytest": "docs.pytest.org",
    "black": "black.readthedocs.io",
    "ruff": "docs.astral.sh/ruff",
    "mypy": "mypy.readthedocs.io",
    "poetry": "python-poetry.org",
    "uv": "docs.astral.sh/uv",
    # Gaming
    "roblox": "roblox.com",
    "minecraft": "minecraft.net",
    "fortnite": "fortnite.com",
    "valorant": "playvalorant.com",
    "league of legends": "leagueoflegends.com",
    "lol": "leagueoflegends.com",
    "cs2": "counter-strike.net",
    "counter strike": "counter-strike.net",
    "dota2": "dota2.com",
    "overwatch": "overwatch.blizzard.com",
    "apex": "ea.com/games/apex-legends",
    "pubg": "pubg.com",
    "warzone": "callofduty.com/warzone",
    "cod": "callofduty.com",
    "gta v": "rockstargames.com/gta-v",
    "cyberpunk": "cyberpunk.net",
    "witcher": "thewitcher.com",
    "baldurs gate": "baldursgate3.game",
    "bg3": "baldursgate3.game",
    "starfield": "bethesda.net/en/game/starfield",
    "skyrim": "elderscrolls.bethesda.net/skyrim",
    "zelda": "zelda.com",
    "pokemon": "pokemon.com",
    "wow": "worldofwarcraft.blizzard.com",
    "ffxiv": "finalfantasyxiv.com",
    "ff14": "finalfantasyxiv.com",
    "destiny 2": "bungie.net",
    "halo": "halowaypoint.com",
    "forza": "forza.net",
    "iracing": "iracing.com",
    "assetto corsa": "assettocorsa.gg",
    "beamng": "beamng.com",
    "ets2": "eurotrucksimulator2.com",
    "factorio": "factorio.com",
    "satisfactory": "satisfactorygame.com",
    "terraria": "terraria.org",
    "stardew": "stardewvalley.net",
    "hollow knight": "hollowknight.com",
    "hades": "supergiantgames.com/games/hades",
    "balatro": "playbalatro.com",
    "elite dangerous": "elitedangerous.com",
    "star citizen": "robertsspaceindustries.com",
    "eve online": "eveonline.com",
    "war thunder": "warthunder.com",
    "wot": "worldoftanks.eu",
    # Aviation extra 2
    "checkwx": "checkwx.com",
    "1800wxbrief": "1800wxbrief.com",
    "fltplan": "fltplan.com",
    "garmin": "garmin.com",
    "airnav": "airnav.com",
    "opensky": "opensky-network.org",
    "adsb exchange": "adsbexchange.com",
    "adsbexchange": "adsbexchange.com",
    "planefinder": "planefinder.net",
    "radarbox": "radarbox.com",
    "jetphotos": "jetphotos.com",
    "airliners": "airliners.net",
    "avweb": "avweb.com",
    "aopa france": "aopa.fr",
    "ffplum": "ffplum.fr",
    "ffam": "ffam.asso.fr",
    "aerobuzz": "aerobuzz.fr",
    "air journal": "air-journal.fr",
    "ops group": "ops.group",
    "boldmethod": "boldmethod.com",
    "mzeroa": "mzeroa.com",
    "sportys": "sportys.com",
    # Education FR
    "sorbonne": "sorbonne-universite.fr",
    "polytechnique": "polytechnique.edu",
    "centrale": "centralesupelec.fr",
    "ens": "ens.fr",
    "sciences po": "sciencespo.fr",
    "sciencespo": "sciencespo.fr",
    "hec": "hec.edu",
    "essec": "essec.edu",
    "escp": "escp.eu",
    "edhec": "edhec.edu",
    "insa lyon": "insa-lyon.fr",
    "42 paris": "42.fr",
    "ecole 42": "42.fr",
    "epita": "epita.fr",
    "epitech": "epitech.eu",
    "ynov": "ynov.com",
    "isep": "isep.fr",
    # Science
    "nature": "nature.com",
    "science mag": "science.org",
    "arxiv": "arxiv.org",
    "scholar": "scholar.google.com",
    "google scholar": "scholar.google.com",
    "semanticscholar": "semanticscholar.org",
    "pubmed": "pubmed.ncbi.nlm.nih.gov",
    "researchgate": "researchgate.net",
    "academia": "academia.edu",
    "ieee": "ieee.org",
    "acm": "acm.org",
    "sciencedirect": "sciencedirect.com",
    # Sports
    "lequipe": "lequipe.fr",
    "l equipe": "lequipe.fr",
    "rmc sport": "rmcsport.bfmtv.com",
    "eurosport": "eurosport.fr",
    "bein sport": "beinsports.com",
    "footmercato": "footmercato.net",
    "transfermarkt": "transfermarkt.fr",
    "sofascore": "sofascore.com",
    "flashscore": "flashscore.fr",
    "ligue 1": "ligue1.fr",
    "uefa": "uefa.com",
    "fifa": "fifa.com",
    # Transport
    "velib": "velib-metropole.fr",
    "lime": "li.me",
    "bolt": "bolt.eu",
    "heetch": "heetch.com",
    "citymapper": "citymapper.com",
    "waze": "waze.com",
    "moovit": "moovit.com",
    "via michelin": "viamichelin.fr",
    "park4night": "park4night.com",
    # Admin FR
    "ants": "ants.gouv.fr",
    "france visas": "france-visas.gouv.fr",
    "diplomatie": "diplomatie.gouv.fr",
    "cnil": "cnil.fr",
    "anssi": "ssi.gouv.fr",
    "cybermalveillance": "cybermalveillance.gouv.fr",
    # Music production
    "ableton": "ableton.com",
    "fl studio": "image-line.com",
    "flstudio": "image-line.com",
    "reaper": "reaper.fm",
    "audacity": "audacityteam.org",
    "bandlab": "bandlab.com",
    "splice": "splice.com",
    "distrokid": "distrokid.com",
    # Design extra
    "sketch": "sketch.com",
    "miro": "miro.com",
    "lucidchart": "lucidchart.com",
    "figjam": "figma.com/figjam",
    "adobe": "adobe.com",
    "photoshop": "adobe.com/products/photoshop.html",
    "premiere": "adobe.com/products/premiere.html",
    "after effects": "adobe.com/products/aftereffects.html",
    "davinci resolve": "blackmagicdesign.com/products/davinciresolve",
    "capcut": "capcut.com",
    # AI extra 3
    "deepseek": "deepseek.com",
    "deep seek": "deepseek.com",
    "lm studio": "lmstudio.ai",
    "lmstudio": "lmstudio.ai",
    "gpt4all": "gpt4all.io",
    "openrouter": "openrouter.ai",
    "fireworks": "fireworks.ai",
    "leonardo": "leonardo.ai",
    "ideogram": "ideogram.ai",
    "black forest labs": "blackforestlabs.ai",
    "comfyui": "github.com/comfyanonymous/ComfyUI",
    # Personal / local
    "lfrs": "metar-taf.com/LFRS",
    "nantes aeroport": "nantes.aeroport.fr",
    "nantes": "nantes.fr",
    "metropole nantes": "metropole.nantes.fr",
}

# Batch 2 — pour atteindre ~640 entrées supplémentaires
EXTRA.update({
    "le parisien": "leparisien.fr",
    "parisien": "leparisien.fr",
    "paris normandie": "paris-normandie.fr",
    "l est republicain": "estrepublicain.fr",
    "est republicain": "estrepublicain.fr",
    "le progres": "leprogres.fr",
    "progres": "leprogres.fr",
    "le dauphine": "ledauphine.com",
    "dauphine": "ledauphine.com",
    "nice matin": "nicematin.com",
    "var matin": "varmatin.com",
    "la provence": "laprovence.com",
    "provence": "laprovence.com",
    "midilibre": "midilibre.fr",
    "l independant": "lindependant.fr",
    "independant": "lindependant.fr",
    "l humanite": "humanite.fr",
    "humanite": "humanite.fr",
    "courrier international": "courrierinternational.com",
    "atlantico": "atlantico.fr",
    "causeur": "causeur.fr",
    "upr": "upr.fr",
    "lci": "lci.fr",
    "c8": "c8.fr",
    "m6": "m6.fr",
    "w9": "w9.fr",
    "tmc": "tmc.tv",
    "nrj12": "nrj12.fr",
    "gulli": "gulli.fr",
    "rmc": "rmc.bfmtv.com",
    "rtl": "rtl.fr",
    "europe 1": "europe1.fr",
    "europe1": "europe1.fr",
    "france inter": "franceinter.fr",
    "franceinter": "franceinter.fr",
    "france culture": "franceculture.fr",
    "franceculture": "franceculture.fr",
    "france musique": "francemusique.fr",
    "francemusique": "francemusique.fr",
    "fip": "fip.fr",
    "radio france": "radiofrance.fr",
    "radiofrance": "radiofrance.fr",
    "skyrock": "skyrock.com",
    "virgin radio": "virginradio.fr",
    "fun radio": "funradio.fr",
    "nostalgie": "nostalgie.fr",
    "nrj": "nrj.fr",
    "chérie fm": "cheriefm.fr",
    "cheriefm": "cheriefm.fr",
    "rfm": "rfm.fr",
    "rtl2": "rtl2.fr",
    "ouifm": "ouifm.fr",
    "tsf jazz": "tsfjazz.com",
    "jazz radio": "jazzradio.fr",
    "apple music": "music.apple.com",
    "amazon music": "music.amazon.fr",
    "tidal": "tidal.com",
    "qobuz": "qobuz.com",
    "napster": "napster.com",
    "lastfm": "last.fm",
    "last fm": "last.fm",
    "discogs": "discogs.com",
    "rateyourmusic": "rateyourmusic.com",
    "rym": "rateyourmusic.com",
    "musixmatch": "musixmatch.com",
    "genius": "genius.com",
    "shazam": "shazam.com",
    "bandcamp": "bandcamp.com",
    "reverb": "reverb.com",
    "thomann": "thomann.de",
    "woodbrass": "woodbrass.com",
    "michenaud": "michenaud.com",
    "star's music": "stars-music.fr",
    "star's": "stars-music.fr",
    "carrefour": "carrefour.fr",
    "auchan": "auchan.fr",
    "leclerc": "e.leclerc",
    "intermarche": "intermarche.com",
    "casino": "casino.fr",
    "monoprix": "monoprix.fr",
    "franprix": "franprix.fr",
    "picard": "picard.fr",
    "biocoop": "biocoop.fr",
    "naturalia": "naturalia.fr",
    "grand frais": "grandfrais.com",
    "metro": "metro.fr",
    "action": "action.com",
    "gifi": "gifi.fr",
    "normal": "normal.fr",
    "primark": "primark.com",
    "primark fr": "primark.com/fr-fr",
    "cultura": "cultura.com",
    "furet du nord": "furet.com",
    "gibert": "gibert.com",
    "gibert joseph": "gibert.com",
    "momox": "momox-shop.fr",
    "recyclivre": "recyclivre.com",
    "momie": "momie.fr",
    "micromania": "micromania.fr",
    "fnac jeux": "fnac.com/Jeux-Video",
    "playmobil": "playmobil.fr",
    "lego": "lego.com",
    "bricklink": "bricklink.com",
    "brickset": "brickset.com",
    "rebrickable": "rebrickable.com",
    "scalemates": "scalemates.com",
    "modelisme": "modelisme.com",
    "hornet hobby": "hornet-hobby.fr",
    "aerobase": "aerobase.fr",
    "aerojumble": "aerojumble.com",
    "airfix": "airfix.com",
    "revell": "revell.com",
    "tamiya": "tamiya.com",
    "horizon hobby": "horizonhobby.com",
    "hobbyking": "hobbyking.com",
    "banggood": "banggood.com",
    "gearbest": "gearbest.com",
    "dx": "dx.com",
    "farnell": "farnell.com",
    "mouser": "mouser.fr",
    "digikey": "digikey.fr",
    "rs components": "fr.rs-online.com",
    "conrad": "conrad.fr",
    "gotronic": "gotronic.fr",
    "lextronic": "lextronic.fr",
    "kubii": "kubii.com",
    "arduino": "arduino.cc",
    "raspberry pi": "raspberrypi.com",
    "raspberrypi": "raspberrypi.com",
    "adafruit": "adafruit.com",
    "sparkfun": "sparkfun.com",
    "espressif": "espressif.com",
    "platformio": "platformio.org",
    "platform io": "platformio.org",
    "micropython": "micropython.org",
    "circuitpython": "circuitpython.org",
    "hackaday": "hackaday.com",
    "hackster": "hackster.io",
    "instructables": "instructables.com",
    "thingiverse": "thingiverse.com",
    "printables": "printables.com",
    "makerworld": "makerworld.com",
    "prusaprint": "prusaprint.com",
    "prusaslicer": "prusaslicer.com",
    "octoprint": "octoprint.org",
    "bambu lab": "bambulab.com",
    "bambulab": "bambulab.com",
    "creality": "creality.com",
    "ultimaker": "ultimaker.com",
    "fusion360": "autodesk.com/products/fusion-360",
    "fusion 360": "autodesk.com/products/fusion-360",
    "autodesk": "autodesk.com",
    "solidworks": "solidworks.com",
    "onshape": "onshape.com",
    "freecad": "freecad.org",
    "openscad": "openscad.org",
    "blender": "blender.org",
    "zbrush": "pixologic.com",
    "substance": "adobe.com/products/substance3d",
    "unity": "unity.com",
    "unreal": "unrealengine.com",
    "unreal engine": "unrealengine.com",
    "godot": "godotengine.org",
    "gamemaker": "gamemaker.io",
    "construct": "construct.net",
    "rpg maker": "rpgmakerweb.com",
    "twine": "twinery.org",
    "ink": "inklestudios.com/ink",
    "renpy": "renpy.org",
    "libreoffice": "libreoffice.org",
    "openoffice": "openoffice.org",
    "onlyoffice": "onlyoffice.com",
    "wps": "wps.com",
    "zoho": "zoho.com",
    "zoho mail": "mail.zoho.com",
    "fastmail": "fastmail.com",
    "tutanota": "tutanota.com",
    "mailbox": "mailbox.org",
    "hey": "hey.com",
    "superhuman": "superhuman.com",
    "spark mail": "sparkmailapp.com",
    "front app": "front.com",
    "missive": "missiveapp.com",
    "supernotes": "supernotes.app",
    "standard notes": "standardnotes.com",
    "joplin": "joplinapp.org",
    "simplenote": "simplenote.com",
    "bear": "bear.app",
    "ulysses": "ulysses.app",
    "ia writer": "iawriter.com",
    "typora": "typora.io",
    "marktext": "marktext.app",
    "zettlr": "zettlr.com",
    "logseq": "logseq.com",
    "remnote": "remnote.com",
    "roam research": "roamresearch.com",
    "roam": "roamresearch.com",
    "capacities": "capacities.io",
    "reflect": "reflect.app",
    "mem ai": "mem.ai",
    "craft docs": "craft.do",
    "craft": "craft.do",
    "slite": "slite.com",
    "gitbook": "gitbook.com",
    "readme": "readme.com",
    "docusaurus": "docusaurus.io",
    "mkdocs": "mkdocs.org",
    "vitepress": "vitepress.dev",
    "docsify": "docsify.js.org",
    "swagger": "swagger.io",
    "openapi": "openapis.org",
    "postman": "postman.com",
    "insomnia": "insomnia.rest",
    "hoppscotch": "hoppscotch.io",
    "httpie": "httpie.io",
    "bruno": "usebruno.com",
    "paw": "paw.cloud",
    "rapidapi": "rapidapi.com",
    "public apis": "publicapis.dev",
    "apis guru": "apis.guru",
    "npm trends": "npmtrends.com",
    "socket dev": "socket.dev",
    "deps dev": "deps.dev",
    "libraries io": "libraries.io",
    "libhunt": "libhunt.com",
    "awesome python": "github.com/vinta/awesome-python",
    "awesome js": "github.com/sindresorhus/awesome",
    "roadmap sh": "roadmap.sh",
    "roadmap": "roadmap.sh",
    "freecodecamp": "freecodecamp.org",
    "codecademy": "codecademy.com",
    "scrimba": "scrimba.com",
    "frontend mentor": "frontendmentor.io",
    "exercism": "exercism.org",
    "leetcode": "leetcode.com",
    "hackerrank": "hackerrank.com",
    "codewars": "codewars.com",
    "codinGame": "codingame.com",
    "codingame": "codingame.com",
    "advent of code": "adventofcode.com",
    "aoc": "adventofcode.com",
    "project euler": "projecteuler.net",
    "euler": "projecteuler.net",
    "topcoder": "topcoder.com",
    "atcoder": "atcoder.jp",
    "codeforces": "codeforces.com",
    "spoj": "spoj.com",
    "uri online judge": "urionlinejudge.com.br",
    "beecrowd": "beecrowd.com",
    "rosalind": "rosalind.info",
    "bioinformatics": "bioinformatics.org",
    "ncbi blast": "blast.ncbi.nlm.nih.gov",
    "uniprot": "uniprot.org",
    "pdb": "rcsb.org",
    "protein data bank": "rcsb.org",
    "chembl": "ebi.ac.uk/chembl",
    "pubchem": "pubchem.ncbi.nlm.nih.gov",
    "materials project": "materialsproject.org",
    "nasa": "nasa.gov",
    "esa": "esa.int",
    "cnes": "cnes.fr",
    "spacex": "spacex.com",
    "blue origin": "blueorigin.com",
    "rocket lab": "rocketlabusa.com",
    "starship": "spacex.com/vehicles/starship",
    "iss tracker": "spotthestation.nasa.gov",
    "heavens above": "heavens-above.com",
    "stellarium web": "stellarium-web.org",
    "stellarium": "stellarium.org",
    "telescope live": "telescope.live",
    "astronomy picture": "apod.nasa.gov",
    "apod": "apod.nasa.gov",
    "space weather": "spaceweather.com",
    "solarham": "solarham.net",
    "ham radio": "qrz.com",
    "qrz": "qrz.com",
    "eham": "eham.net",
    "radio reference": "radioreference.com",
    "flight sim to cockpit": "flightsim.to",
    "flightsim to": "flightsim.to",
    "fselite": "fselite.net",
    "fs news": "fsnews.eu",
    "fslabs": "flightsimlabs.com",
    "pmdg": "pmdg.com",
    "fenixsim": "fenixsim.com",
    "iniBuilds": "inibuilds.com",
    "inibuilds": "inibuilds.com",
    "orbx": "orbxsystems.com",
    "rex": "rexsimulations.com",
    "rex sim": "rexsimulations.com",
    "simmarket": "simmarket.com",
    "simshack": "simshack.net",
    "just flight": "justflight.com",
    "aerosoft": "aerosoft.com",
    "x plane": "x-plane.com",
    "xplane": "x-plane.com",
    "laminar research": "x-plane.com",
    "xp11": "x-plane.com",
    "xp12": "x-plane.com",
    "prepar3d": "prepar3d.com",
    "p3d": "prepar3d.com",
    "fsx": "flightsimulator.com",
    "fs2020": "flightsimulator.com",
    "fs2024": "flightsimulator.com",
    "msfs marketplace": "flightsimulator.com/marketplace",
    "orbx central": "orbxsystems.com/orbxcentral",
    "vatsim map": "map.vatsim.net",
    "stat vatsim": "stats.vatsim.net",
    "ivao map": "map.ivao.aero",
    "pilot portal": "pilotportal.de",
    "skybrary": "skybrary.aero",
    "icao": "icao.int",
    "iata": "iata.org",
    "aip france": "aip.aero",
    "sia aip": "sia.aviation-civile.gouv.fr",
    "aip": "aip.aero",
    "ais france": "sia.aviation-civile.gouv.fr",
    "sia bulletins": "sia.aviation-civile.gouv.fr",
    "metar decoder": "metar-taf.com",
    "metar taf com": "metar-taf.com",
    "aviation weather center": "aviationweather.gov",
    "awc": "aviationweather.gov",
    "duats": "1800wxbrief.com",
    "1800 wxbrief": "1800wxbrief.com",
    "skyvector charts": "skyvector.com",
    "vfrnav": "vfrnav.com",
    "easyvfr": "easyvfr.com",
    "airnav pro": "airnavsystems.com",
    "airnav systems": "airnavsystems.com",
    "wingx": "hiltonsoftware.com",
    "hilton software": "hiltonsoftware.com",
    "flightsafe": "flightsafe.io",
    "flight logger": "flightlogger.net",
    "logten pro": "coradine.com",
    "mypilotlog": "mypilotlog.com",
    "flylog": "flylog.io",
    "cloudahoy": "cloudahoy.com",
    "garmin connect": "connect.garmin.com",
    "garmin pilot web": "fly.garmin.com",
    "dynon skyview": "dynonavionics.com",
    "g3x": "garmin.com",
    "foreflight logbook": "plan.foreflight.com",
    "flight plan go": "flightplan.com",
    "wingtra": "wingtra.com",
    "dji": "dji.com",
    "dronedeploy": "dronedeploy.com",
    "pix4d": "pix4d.com",
    "opendronemap": "opendronemap.org",
    "betaflight": "betaflight.com",
    "inav": "github.com/iNavFlight/inav",
    "ardupilot": "ardupilot.org",
    "px4": "px4.io",
    "dronecode": "dronecode.org",
    "uav coach": "uavcoach.com",
    "drone pilot ground school": "dronepilotgroundschool.com",
    "dgac drone": "drone.entreprises.gouv.fr",
    "alpha tango": "alphatango.aviation-civile.gouv.fr",
    "alphatango": "alphatango.aviation-civile.gouv.fr",
    "ffam brevet": "ffam.asso.fr",
    "ulm france": "ffplum.fr",
    "aeroclub": "aeroclub.fr",
    "aeroclubs": "aeroclub.fr",
    "aero club": "aeroclub.fr",
    "aero-club": "aeroclub.fr",
    "ffvp": "ffvp.fr",
    "parachutisme": "ffp.asso.fr",
    "ffp": "ffp.asso.fr",
    "uspa": "uspa.org",
    "dropzone": "dropzone.com",
    "paraclub": "paraclub.net",
    "windguru": "windguru.cz",
    "windfinder": "windfinder.com",
    "windy app": "windy.app",
    "yr no": "yr.no",
    "yr": "yr.no",
    "weather underground": "wunderground.com",
    "wunderground": "wunderground.com",
    "weather gov": "weather.gov",
    "noaa": "noaa.gov",
    "met office": "metoffice.gov.uk",
    "dwd": "dwd.de",
    "aemet": "aemet.es",
    "meteo paris": "meteofrance.com/previsions-meteo-france/paris/75000",
    "meteo nantes": "meteofrance.com/previsions-meteo-france/nantes/44000",
    "meteo lyon": "meteofrance.com/previsions-meteo-france/lyon/69000",
    "meteo marseille": "meteofrance.com/previsions-meteo-france/marseille/13000",
    "meteo toulouse": "meteofrance.com/previsions-meteo-france/toulouse/31000",
    "meteo bordeaux": "meteofrance.com/previsions-meteo-france/bordeaux/33000",
    "meteo lille": "meteofrance.com/previsions-meteo-france/lille/59000",
    "meteo strasbourg": "meteofrance.com/previsions-meteo-france/strasbourg/67000",
    "meteo nice": "meteofrance.com/previsions-meteo-france/nice/06000",
    "meteo rennes": "meteofrance.com/previsions-meteo-france/rennes/35000",
    "meteo montpellier": "meteofrance.com/previsions-meteo-france/montpellier/34000",
    "meteo grenoble": "meteofrance.com/previsions-meteo-france/grenoble/38000",
    "meteo coueron": "meteofrance.com/previsions-meteo-france/coueron/44220",
    "openstreetmap": "openstreetmap.org",
    "osm": "openstreetmap.org",
    "mapbox": "mapbox.com",
    "here maps": "here.com",
    "here": "here.com",
    "tomtom": "tomtom.com",
    "ign maps": "geoportail.gouv.fr",
    "geoportail": "geoportail.gouv.fr",
    "ign france": "ign.fr",
    "cadastre": "cadastre.gouv.fr",
    "cadastre gouv": "cadastre.gouv.fr",
    "immobilier gouv": "data.gouv.fr/fr/datasets/demandes-de-valeurs-foncieres",
    "seloger": "seloger.com",
    "leboncoin immo": "leboncoin.fr/c/immobilier",
    "bien ici": "bienici.com",
    "bienici": "bienici.com",
    "logic immo": "logic-immo.com",
    "logicimmo": "logic-immo.com",
    "pap": "pap.fr",
    "paru vendu": "paruvendu.fr",
    "paruvendu": "paruvendu.fr",
    "orpi": "orpi.com",
    "century 21": "century21.fr",
    "laforet": "laforet.com",
    "guy hoquet": "guy-hoquet.com",
    "foncia": "foncia.com",
    "nexity": "nexity.fr",
    "bouygues immo": "bouygues-immobilier.com",
    "kaufman broad": "kaufmanbroad.com",
    "maif": "maif.fr",
    "macif": "macif.fr",
    "matmut": "matmut.fr",
    "groupama": "groupama.fr",
    "axa": "axa.fr",
    "allianz": "allianz.fr",
    "generali": "generali.fr",
    "swiss life": "swisslife.fr",
    "april": "april.fr",
    "harmonie mutuelle": "harmonie-mutuelle.fr",
    "mgen": "mgen.fr",
    "lcl assurance": "lcl.fr",
    "direct assurance": "direct-assurance.fr",
    "assurland": "assurland.com",
    "lesfurets": "lesfurets.com",
    "meilleurtaux": "meilleurtaux.com",
    "credit agricole immo": "credit-agricole.fr",
    "credit foncier": "creditfoncier.fr",
    "bnp immo": "bnppre.fr",
    "orange": "orange.fr",
    "sfr": "sfr.fr",
    "bouygues telecom": "bouyguestelecom.fr",
    "free mobile": "mobile.free.fr",
    "free": "free.fr",
    "red by sfr": "red-by-sfr.fr",
    "red sfr": "red-by-sfr.fr",
    "sosh": "sosh.fr",
    "b&you": "bouyguestelecom.fr",
    "byou": "bouyguestelecom.fr",
    "laposte mobile": "lapostemobile.fr",
    "prixtel": "prixtel.com",
    "coriolis": "coriolis.com",
    "nrj mobile": "nrjmobile.fr",
    "la poste": "laposte.fr",
    "laposte": "laposte.fr",
    "colissimo": "colissimo.fr",
    "chronopost": "chronopost.fr",
    "mondial relay": "mondialrelay.fr",
    "mondialrelay": "mondialrelay.fr",
    "relais colis": "relaiscolis.com",
    "ups": "ups.com",
    "dhl": "dhl.com",
    "fedex": "fedex.com",
    "gls": "gls-group.eu",
    "dpd": "dpd.com",
    "amazon logistics": "amazon.fr",
    "cdiscount marketplace": "marketplace.cdiscount.com",
    "manomano pro": "pro.manomano.fr",
    "bricomarché": "bricomarche.com",
    "bricomarche": "bricomarche.com",
    "point p": "pointp.fr",
    "pointp": "pointp.fr",
    "cedeo": "cedeo.fr",
    "saint maclou": "saint-maclou.com",
    "lapeyre": "lapeyre.fr",
    "hilti": "hilti.fr",
    "wurth": "wurth.fr",
    "facom": "facom.com",
    "stanley": "stanleytools.fr",
    "dewalt": "dewalt.fr",
    "makita": "makita.fr",
    "bosch pro": "bosch-professional.com",
    "festool": "festool.com",
    "metabo": "metabo.com",
    "karcher": "karcher.com",
    "nilfisk": "nilfisk.com",
    "dyson": "dyson.fr",
    "rowenta": "rowenta.fr",
    "seb": "groupeseb.com",
    "moulinex": "moulinex.fr",
    "tefal": "tefal.fr",
    "krups": "krups.fr",
    "delonghi": "delonghi.com",
    "nespresso": "nespresso.com",
    "illy": "illy.com",
    "lavazza": "lavazza.com",
    "starbucks": "starbucks.fr",
    "mcdo": "mcdonalds.fr",
    "mcdonalds": "mcdonalds.fr",
    "burger king": "burgerking.fr",
    "kfc": "kfc.fr",
    "subway": "subway.com",
    "dominos": "dominos.fr",
    "pizza hut": "pizzahut.fr",
    "sushi shop": "sushishop.fr",
    "sushishop": "sushishop.fr",
    "paul": "paul.fr",
    "brioche doree": "briochedoree.fr",
    "starbucks reserve": "starbucks.fr",
    "carrefour contact": "carrefour.fr",
    "monop daily": "monoprix.fr",
    "franprix shop": "franprix.fr",
    "match": "supermarchesmatch.fr",
    "super u": "magasins-u.com",
    "superu": "magasins-u.com",
    "systeme u": "systeme-u.com",
    "systemeu": "systeme-u.com",
    "corapro": "corapro.fr",
    "bricomarché pro": "bricomarche.com",
    "bricoman": "bricoman.fr",
    "weldom": "weldom.fr",
    "mr bricolage": "mr-bricolage.fr",
    "mr brico": "mr-bricolage.fr",
    "truffaut": "truffaut.com",
    "jardiland": "jardiland.com",
    "gamm vert": "gammvert.fr",
    "gammvert": "gammvert.fr",
    "botanic": "botanic.com",
    "dehner": "dehner.de",
    "obi": "obi.fr",
    "hagebau": "hagebau.fr",
    "animalis": "animalis.com",
    "maxi zoo": "maxizoo.fr",
    "maxizoo": "maxizoo.fr",
    "zolux": "zolux.com",
    "wanimo": "wanimo.com",
    "wamiz": "wamiz.com",
    "chats du monde": "chatsdumonde.com",
    "doctissimo": "doctissimo.fr",
    "passeportsante": "passeportsante.net",
    "ameli pro": "ameli.fr",
    "ordre medecins": "conseil-national.medecin.fr",
    "ordre infirmiers": "ordre-infirmiers.fr",
    "pharmanet": "pharmanet.fr",
    "doctipharma": "doctipharma.fr",
    "pharmacie": "pharmacie.fr",
    "mon pharmacien": "monpharmacien.fr",
    "médicament": "base-donnees-publique.medicaments.gouv.fr",
    "base medicaments": "base-donnees-publique.medicaments.gouv.fr",
    "ameli dentaire": "ameli.fr",
    "mutuelle": "mutuelle.fr",
    "harmonie": "harmonie-mutuelle.fr",
    "mgen etudiant": "mgen.fr",
    "lmd santé": "lmdsante.fr",
    "lmdsante": "lmdsante.fr",
    "etudiant gouvernement": "etudiant.gouv.fr",
    "etudiant gouv": "etudiant.gouv.fr",
    "crous": "crous.fr",
    "crous nantes": "crous-nantes.fr",
    "mess services": "messervices.etudiant.gouv.fr",
    "messervices": "messervices.etudiant.gouv.fr",
    "mon master": "monmaster.gouv.fr",
    "monmaster": "monmaster.gouv.fr",
    "dossierapprentissage": "dossierapprentissage.fr",
    "apprentissage": "alternance.emploi.gouv.fr",
    "alternance": "alternance.emploi.gouv.fr",
    "1jeune1solution": "1jeune1solution.gouv.fr",
    "apec": "apec.fr",
    "apecita": "apecita.com",
    "indeed": "fr.indeed.com",
    "linkedin jobs": "linkedin.com/jobs",
    "welcometothejungle": "welcometothejungle.com",
    "wttj": "welcometothejungle.com",
    "hellowork": "hellowork.com",
    "regionsjob": "regionsjob.com",
    "cadremploi": "cadremploi.fr",
    "jobteaser": "jobteaser.com",
    "monster": "monster.fr",
    "glassdoor": "glassdoor.fr",
    "teamtailor": "teamtailor.com",
    "greenhouse": "greenhouse.io",
    "lever": "lever.co",
    "workday": "workday.com",
    "smartrecruiters": "smartrecruiters.com",
    "france compétences": "francecompetences.fr",
    "france competences": "francecompetences.fr",
    "france travail emploi": "francetravail.fr",
    "pole emploi fr": "francetravail.fr",
    "mission locale": "missionlocale.fr",
    "cap emploi": "capemploi.info",
    "agefiph": "agefiph.fr",
    "unedic": "unedic.org",
    "assurance chomage": "assurance-chomage.fr",
    "assurance chômage": "assurance-chomage.fr",
    "urssaf auto": "autoentrepreneur.urssaf.fr",
    "autoentrepreneur": "autoentrepreneur.urssaf.fr",
    "auto entrepreneur": "autoentrepreneur.urssaf.fr",
    "statut auto": "autoentrepreneur.urssaf.fr",
    "infogreffe": "infogreffe.fr",
    "societe com": "societe.com",
    "societe.com": "societe.com",
    "pappers": "pappers.fr",
    "verif": "verif.com",
    "manageo": "manageo.fr",
    "annuaire entreprises": "annuaire-entreprises.data.gouv.fr",
    "entreprises gouv": "annuaire-entreprises.data.gouv.fr",
    "bodacc": "bodacc.fr",
    "monidenum": "monidenum.fr",
    "idenum": "monidenum.fr",
    "dougs": "dougs.fr",
    "indy": "indy.fr",
    "pennylane": "pennylane.com",
    "quickbooks": "quickbooks.intuit.com",
    "sage": "sage.com",
    "cegid": "cegid.com",
    "ebp": "ebp.com",
    "tiime": "tiime.fr",
    "shine": "shine.fr",
    "qonto": "qonto.com",
    "manager one": "manager.one",
    "managerone": "manager.one",
    "blank": "blank.app",
    "legalstart": "legalstart.fr",
    "legalplace": "legalplace.fr",
    "captain contrat": "captaincontrat.com",
    "captaincontrat": "captaincontrat.com",
    "impots pro": "impots.gouv.fr",
    "net entreprises": "net-entreprises.fr",
    "netentreprises": "net-entreprises.fr",
    "chorus pro": "chorus-pro.gouv.fr",
    "choruspro": "chorus-pro.gouv.fr",
    "facture gouv": "portail-facture.gouv.fr",
    "portail facture": "portail-facture.gouv.fr",
    "dgefp": "dgefp.gouv.fr",
    "travail gouv": "travail-emploi.gouv.fr",
    "travail emploi": "travail-emploi.gouv.fr",
    "code travail": "code.travail.gouv.fr",
    "legifrance travail": "legifrance.gouv.fr",
    "inrs": "inrs.fr",
    "anact": "anact.fr",
    "opco atlas": "opco-atlas.fr",
    "opco ep": "opcoep.fr",
    "opco 2i": "opco2i.fr",
    "opco commerce": "opcommerce.fr",
    "opco mobilites": "opcomobilites.fr",
    "opco sante": "opco-sante.fr",
    "mon compte formation": "moncompteformation.gouv.fr",
    "moncompteformation": "moncompteformation.gouv.fr",
    "transitions pro": "transitionspro-na.fr",
    "transitionspro na": "transitionspro-na.fr",
    "region pays de la loire": "paysdelaloire.fr",
    "pays de la loire": "paysdelaloire.fr",
    "loire atlantique": "loire-atlantique.fr",
    "loireatlantique": "loire-atlantique.fr",
    "nantes metropole": "metropole.nantes.fr",
    "nantesmetropole": "metropole.nantes.fr",
    "coueron mairie": "coueron.fr",
    "reze": "reze.fr",
    "saint herblain": "saintherblain.fr",
    "saintherblain": "saintherblain.fr",
    "orvault": "orvault.fr",
    "vertou": "vertou.fr",
    "carquefou": "carquefou.fr",
    "bouguenais": "bouguenais.fr",
    "treillieres": "treillieres.fr",
    "treillières": "treillieres.fr",
    "indre": "indre.fr",
    "indre loire": "indre.fr",
    "chateaubriant": "chateaubriant.fr",
    "ancenis": "ancenis.fr",
    "clisson": "clisson.fr",
    "pornic": "pornic.fr",
    "la baule": "labaule.fr",
    "labaule": "labaule.fr",
    "saint nazaire": "saintnazaire.fr",
    "saintnazaire": "saintnazaire.fr",
    "vannes": "vannes.fr",
    "lorient": "lorient.fr",
    "quimper": "quimper.bzh",
    "brest": "brest.fr",
    "rennes metropole": "metropole.rennes.fr",
    "rennesmetropole": "metropole.rennes.fr",
    "sem nantes": "sem-nantes.fr",
    "tan": "tan.fr",
    "transdev": "transdev.com",
    "keolis": "keolis.com",
    "ilevia": "ilevia.fr",
    "tisseo": "tisseo.fr",
    "rtm": "rtm.fr",
    "tcl": "tcl.fr",
    "ratp info": "ratp.fr",
    "sncf voyageurs": "sncf-voyageurs.com",
    "oui sncf": "sncf-connect.com",
    "trainline": "trainline.fr",
    "thetrainline": "thetrainline.com",
    "rail europe": "raileurope.com",
    "raileurope": "raileurope.com",
    "thalys": "thalys.com",
    "eurostar": "eurostar.com",
    "tgv": "sncf-connect.com",
    "ter": "sncf-connect.com",
    "idtgv": "sncf-connect.com",
    "inoui": "sncf-connect.com",
    "in oui": "sncf-connect.com",
    "sncf reseau": "sncf-reseau.com",
    "vinci autoroutes": "vinci-autoroutes.com",
    "sanef": "sanef.com",
    "aprr": "aprr.fr",
    "area": "area.eu",
    "cofiroute": "cofiroute.fr",
    "bison futé": "bison-fute.gouv.fr",
    "bison fute": "bison-fute.gouv.fr",
    "viamichelin trafic": "viamichelin.fr",
    "waze live map": "waze.com/live-map",
    "google flights": "google.com/travel/flights",
    "skyscanner": "skyscanner.fr",
    "kayak": "kayak.fr",
    "momondo": "momondo.fr",
    "liligo": "liligo.fr",
    "swoodoo": "swoodoo.com",
    "expedia": "expedia.fr",
    "hotels com": "hotels.com",
    "hotels.com": "hotels.com",
    "trivago": "trivago.fr",
    "hostelworld": "hostelworld.com",
    "couchsurfing": "couchsurfing.com",
    "workaway": "workaway.info",
    "wwoof": "wwoof.net",
    "visiteradar": "visiteradar.com",
    "routard": "routard.com",
    "lonely planet": "lonelyplanet.com",
    "guide du routard": "routard.com",
    "voyage prive": "voyage-prive.com",
    "voyageprive": "voyage-prive.com",
    "promovacances": "promovacances.com",
    "lastminute": "lastminute.com",
    "govoyages": "govoyages.com",
    "opodo": "opodo.fr",
    "edreams": "edreams.fr",
    "volotea": "volotea.com",
    "vueling": "vueling.com",
    "tap air": "flytap.com",
    "lufthansa": "lufthansa.com",
    "british airways": "britishairways.com",
    "ba": "britishairways.com",
    "klm": "klm.fr",
    "iberia": "iberia.com",
    "sas": "flysas.com",
    "finnair": "finnair.com",
    "norwegian": "norwegian.com",
    "wizz air": "wizzair.com",
    "wizzair": "wizzair.com",
    "jet2": "jet2.com",
    "tui": "tui.fr",
    "corsair": "corsair.fr",
    "french bee": "frenchbee.com",
    "frenchbee": "frenchbee.com",
    "level": "flylevel.com",
    "flylevel": "flylevel.com",
    "hop": "airfrance.fr",
    "air corsica": "aircorsica.com",
    "aircorsica": "aircorsica.com",
    "binter": "bintercanarias.com",
    "luxair": "luxair.lu",
    "swiss": "swiss.com",
    "austrian": "austrian.com",
    "brussels airlines": "brusselsairlines.com",
    "lot": "lot.com",
    "turkish airlines": "turkishairlines.com",
    "turkish": "turkishairlines.com",
    "qatar airways": "qatarairways.com",
    "qatar": "qatarairways.com",
    "emirates": "emirates.com",
    "etihad": "etihad.com",
    "saudia": "saudia.com",
    "singapore airlines": "singaporeair.com",
    "cathay": "cathaypacific.com",
    "cathay pacific": "cathaypacific.com",
    "ana": "ana.co.jp",
    "jal": "jal.co.jp",
    "korean air": "koreanair.com",
    "china eastern": "ceair.com",
    "air china": "airchina.com",
    "eva air": "evaair.com",
    "thai airways": "thaiairways.com",
    "vietnam airlines": "vietnamairlines.com",
    "air india": "airindia.com",
    "indigo": "goindigo.in",
    "airasia": "airasia.com",
    "cebu pacific": "cebupacificair.com",
    "jetstar": "jetstar.com",
    "virgin atlantic": "virginatlantic.com",
    "virgin australia": "virginaustralia.com",
    "jetblue": "jetblue.com",
    "southwest": "southwest.com",
    "delta": "delta.com",
    "united": "united.com",
    "american airlines": "aa.com",
    "aa": "aa.com",
    "alaska airlines": "alaskaair.com",
    "spirit": "spirit.com",
    "frontier": "flyfrontier.com",
    "allegiant": "allegiantair.com",
    "hawaiian": "hawaiianairlines.com",
    "air canada": "aircanada.com",
    "westjet": "westjet.com",
    "latam": "latam.com",
    "avianca": "avianca.com",
    "copa": "copaair.com",
    "aeromexico": "aeromexico.com",
    "volaris": "volaris.com",
    "gol": "voegol.com.br",
    "azul": "voeazul.com.br",
    "ethiopian": "ethiopianairlines.com",
    "kenya airways": "kenya-airways.com",
    "royal air maroc": "royalairmaroc.com",
    "ram": "royalairmaroc.com",
    "tunisair": "tunisair.com",
    "air algerie": "airalgerie.dz",
    "airalgerie": "airalgerie.dz",
    "egyptair": "egyptair.com",
    "el al": "elal.com",
    "elal": "elal.com",
    "arkia": "arkia.com",
    "israir": "israir.co.il",
    "flydubai": "flydubai.com",
    "air arabia": "airarabia.com",
    "airarabia": "airarabia.com",
    "flynas": "flynas.com",
    "pegasus": "flypgs.com",
    "sunexpress": "sunexpress.com",
    "corendon": "corendon.com",
    "transavia holland": "transavia.com",
    "tui fly": "tuifly.com",
    "condor": "condor.com",
    "eurowings": "eurowings.com",
    "air baltic": "airbaltic.com",
    "airbaltic": "airbaltic.com",
    "air serbia": "airserbia.com",
    "airserbia": "airserbia.com",
    "croatia airlines": "croatiaairlines.com",
    "aegean": "aegeanair.com",
    "olympic air": "olympicair.com",
    "tarom": "tarom.ro",
    "wideroe": "wideroe.no",
    "sas connect": "flysas.com",
    "finnair plus": "finnair.com",
    "miles and more": "miles-and-more.com",
    "flying blue": "flyingblue.com",
    "flyingblue": "flyingblue.com",
    "oneworld": "oneworld.com",
    "skyteam": "skyteam.com",
    "star alliance": "staralliance.com",
    "staralliance": "staralliance.com",
})


def _merge_extra() -> dict[str, str]:
    import importlib
    import re
    from pathlib import Path

    merged = dict(EXTRA)
    scripts_dir = Path(__file__).resolve().parent
    batch_nums = sorted(
        int(m.group(1))
        for p in scripts_dir.glob("aliases_batch*.py")
        if (m := re.fullmatch(r"aliases_batch(\d+)", p.stem))
    )
    for n in batch_nums:
        mod = importlib.import_module(f"scripts.aliases_batch{n}")
        if getattr(mod, "SQL_DOUBLED", False):
            continue
        fn = getattr(mod, f"get_batch{n}")
        for key, domain in fn().items():
            merged.setdefault(key, domain)
    return merged


def format_dict(d: dict[str, str], indent: str = "    ") -> str:
    lines = ["_ALIASES_EXTRA: dict[str, str] = {"]
    for k, v in d.items():
        lines.append(f'{indent}"{k}": "{v}",')
    lines.append("}")
    return "\n".join(lines)


if __name__ == "__main__":
    from pathlib import Path

    merged = _merge_extra()
    count = len(merged)
    out_path = Path(__file__).resolve().parent.parent / "actions" / "site_aliases_extra.py"
    sys_path = Path(__file__).resolve().parent.parent
    import sys

    if str(sys_path) not in sys.path:
        sys.path.insert(0, str(sys_path))
    from actions.alias_store import count as db_count, sync_missing_prefixes

    sync_missing_prefixes()
    total = db_count()
    out_path.write_text(
        "# Auto-generated — alias stockés dans data/site_aliases.db\n"
        "from __future__ import annotations\n\n"
        f"ALIAS_COUNT = {total}\n"
        "_ALIASES_EXTRA: dict[str, str] = {}  # voir actions/alias_store.py\n",
        encoding="utf-8",
    )
    print(f"entries: {total}")
    print(f"wrote {out_path.name} (stub)")
    print(f"index: data/site_aliases.db")
